// Real native controls, fictional records, disposable browser contexts only.
import assert from 'node:assert/strict';
import {chromium} from '../../portal/node_modules/playwright/index.mjs';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
const base=process.argv[2]??'http://127.0.0.1:4197/';const dir='/opt/utilibre/reports/knit-newton-20261009';await mkdir(dir,{recursive:true,mode:0o700});const browser=await chromium.launch();const results=[];
const names=['Ada Example','Ben Example','Cleo Example','Dani Example'];
function monitor(p){const requests=[],errors=[];p.on('request',r=>requests.push(r.url()));p.on('pageerror',e=>errors.push(e.message));p.on('dialog',d=>d.accept());p.setDefaultTimeout(15000);return {requests,errors};}
try{for(const[locale,width]of[['en-GB',1280],['es-GT',390]]){
 const c=await browser.newContext({locale,viewport:{width,height:1000},isMobile:width===390,hasTouch:width===390,acceptDownloads:true});const p=await c.newPage();const checks=monitor(p);await p.goto(base);await p.locator('summary').click();assert(await p.locator('[lang="es"]').isVisible());await p.locator('summary').click();
 const title=`Fictional Cup ${locale}`;await p.locator('#tournamentName').fill(title);await p.locator('#setupCreateBtn').click();await p.getByRole('button',{name:'Player Registration',exact:true}).click();
 for(const name of names){await p.getByRole('button',{name:'+ New player',exact:true}).click();await p.locator('#pfShort').fill(name);await p.locator('#pfSave').click();}
 await p.locator('.nav').getByRole('button',{name:'Tournament Bracket',exact:true}).click();for(const name of names){await p.getByRole('button',{name,exact:true}).click();await p.waitForTimeout(100);}await p.keyboard.press('Escape');
 await p.locator('button[onclick="generateBracket(\'SE\')"]').click();await p.getByRole('button',{name:'Generate',exact:true}).click();await p.waitForFunction(()=>matches.length===4&&players.every(p=>p.paid));assert.equal(await p.evaluate(()=>tournament.format),'SE');
 assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.screenshot({path:`${dir}/newton-${locale}.png`});await p.locator('#tournament button[onclick="showPage(\'setup\')"]').click();const d=p.waitForEvent('download');await p.getByRole('button',{name:'Export tournament',exact:true}).click();const file=`${dir}/newton-${locale}.json`;await(await d).saveAs(file);const data=JSON.parse(await readFile(file,'utf8'));assert.equal(data.players.length,4);assert.equal(data.matches.length,4);assert.equal(data.format,'SE');assert(data.playerDatabase);assert(!('remoteApiKey' in data.config.server));
 // Reload verifies browser persistence without an export/import.
 await p.reload();await p.waitForFunction(()=>tournament?.name.startsWith('Fictional Cup'));assert.equal(await p.evaluate(()=>players.length),4);
 // Open Analytics to exercise the server-discovery suppression, not merely initial readiness.
 await p.locator('.nav').getByRole('button',{name:'Analytics',exact:true}).click();await p.waitForTimeout(300);assert.deepEqual(checks.errors,[]);assert(checks.requests.every(u=>new URL(u).origin===new URL(base).origin&&!/\/api\/|\/licensed\/|\/fonts\//.test(new URL(u).pathname)));await c.close();
 const fresh=await browser.newContext({locale,viewport:{width,height:1000},acceptDownloads:true});const q=await fresh.newPage();const restore=monitor(q);await q.goto(base);await q.locator('#importFile').setInputFiles(file);await q.locator('#confirmImportBtn').click();await q.waitForFunction(()=>players.length===4&&matches.length===4);assert.equal(await q.evaluate(()=>tournament.name),title);assert.equal(await q.evaluate(()=>tournament.format),'SE');
 // Native deletion requires first switching away from the tournament being deleted.
 await q.locator('.nav').getByRole('button',{name:'Tournament Setup',exact:true}).click();await q.getByRole('button',{name:'New tournament',exact:true}).click();await q.locator('#tournamentName').fill('Fictional cleanup placeholder');await q.locator('#setupCreateBtn').click();await q.getByRole('button',{name:'Delete '+title,exact:true}).click();await q.locator('#deleteTournamentModal').getByRole('button',{name:'Delete Tournament',exact:true}).click();assert.equal(await q.evaluate(t=>JSON.parse(localStorage.getItem('dartsTournaments')).some(x=>x.name===t),title),false);
 assert.deepEqual(restore.errors,[]);assert(restore.requests.every(u=>new URL(u).origin===new URL(base).origin&&!/\/api\/|\/licensed\/|\/fonts\//.test(new URL(u).pathname)));results.push({locale,width,nativeFourPlayerBracket:true,jsonExportIndependentImport:true,browserReloadPersistence:true,nativeTournamentDeletion:true,exportVersion:data.exportVersion,exportFields:Object.keys(data),noHorizontalOverflow:true,requests:[...checks.requests,...restore.requests],externalOrApiRequests:[],errors:[]});await fresh.close();
}await writeFile(`${dir}/newton-results.json`,JSON.stringify({date:new Date().toISOString(),base,results},null,2));console.log('PASS NewTon native four-player bracket, JSON export/import, reload, deletion, desktop/390px and no external/API requests.');}finally{await browser.close();}
