FROM ghcr.io/reactive-resume/reactive-resume:v6.0.0@sha256:29f418bd46d23f1d7cd9a73ec7f6bc46681926cb1ff617ac388064f45ee790d0
USER root
COPY prepare-resume-no-tracking.mjs /opt/utilibre-build/prepare-resume-no-tracking.mjs
RUN node /opt/utilibre-build/prepare-resume-no-tracking.mjs /app
USER node
