FROM python:3.13-slim@sha256:3dd7cc108ec1493442514f5c2a871af6af0ec31d768ff6e378a93340c3b3db5f AS build
WORKDIR /work
RUN pip install --no-cache-dir jupyterlite-core==0.8.5 jupyterlite-pyodide-kernel==0.8.6 jupyter-server==2.21.1 jupyterlab-server==2.28.1 jupyterlab-language-pack-es-ES==4.5.post3
COPY jupyter/ /work/
# Native kernel dependency omitted by the Pyodide distribution: bundle it using
# JupyterLite's supported wheel index instead of allowing a visitor's PyPI call.
ADD --chmod=644 --checksum=sha256:c615d91d75f7f04f095b30d1c1711babd43bdc6419c1be9886a85f2f4e489417 https://files.pythonhosted.org/packages/60/97/891a0971e1e4a8c5d2b20bbe0e524dc04548d2307fee33cdeba148fd4fc7/comm-0.2.3-py3-none-any.whl /wheels/comm-0.2.3-py3-none-any.whl
RUN jupyter lite build --contents contents --output-dir /site --piplite-wheels /wheels/comm-0.2.3-py3-none-any.whl && pip freeze > /site/build-requirements.txt
WORKDIR /work/es
RUN jupyter lite build --contents ../contents --output-dir /site/es --piplite-wheels /wheels/comm-0.2.3-py3-none-any.whl
ADD --checksum=sha256:fd25b21567f83f83b0b8bb1780a5458c6d4dd10bb07a22004424194022037f00 https://github.com/pyodide/pyodide/releases/download/314.0.6/pyodide-314.0.6.tar.bz2 /tmp/utilibre-pyodide.tar.bz2
RUN python -c "import tarfile; a=tarfile.open('/tmp/utilibre-pyodide.tar.bz2'); assert all(m.name=='pyodide' or m.name.startswith('pyodide/') for m in a.getmembers()); a.extractall('/site', filter='data')" && rm /tmp/utilibre-pyodide.tar.bz2
FROM nginxinc/nginx-unprivileged:1.28-alpine@sha256:7377697a821c131a924a7105fafbe7414db4e9fcc77a6f08f776f33f141ec3f8
COPY --from=build /site /usr/share/nginx/html
ENTRYPOINT ["nginx", "-g", "daemon off;"]
