FROM nginxinc/nginx-unprivileged:1.28-alpine@sha256:7377697a821c131a924a7105fafbe7414db4e9fcc77a6f08f776f33f141ec3f8
COPY dist /usr/share/nginx/html
COPY LICENSE /usr/share/nginx/html/LICENSE.txt
ENTRYPOINT ["nginx", "-g", "daemon off;"]
