// CryptPad 2026.9.0 / cryptpad-server 1.0.1 supported server configuration.
module.exports = {
  installMethod: 'source',
  preferredLanguage: 'es',
  adminEmail: 'admin@utilibre.org',
  blockDailyCheck: true,
  logIP: false,
  logFeedback: false,
  logToStdout: process.env.PACK_DIAGNOSTIC === '1',
  logPath: undefined,
  provideAggregateStatistics: false,
  listMyInstance: false,
  consentToContact: false,
  removeDonateButton: true,
  allow_subscriptions: false,
  defaultStorageLimit: 25 * 1024 * 1024,
  maxUploadSize: 5 * 1024 * 1024,
  inactiveTime: 90,
  archiveRetentionTime: 15,
  accountRetentionTime: 365,
  disableIntegratedEviction: false,
  maxWorkers: {http: 1, core: 2, storage: 2, 'storage-http': 2},
  filePath: './datastore/', archivePath: './data/archive',
  pinPath: './data/pins', taskPath: './data/tasks', blockPath: './block',
  blobPath: './blob', blobStagingPath: './data/blobstage', decreePath: './data/decrees',
};
