FROM rust:1.90-bookworm@sha256:3914072ca0c3b8aad871db9169a651ccfce30cf58303e5d6f2db16d1d8a7e58f AS build
ENV CARGO_BUILD_JOBS=2
RUN rustup target add wasm32-unknown-unknown && cargo install wasm-bindgen-cli --version 0.2.100 --locked
WORKDIR /source
COPY . .
WORKDIR /source/numbat-wasm
ENV RUSTFLAGS='--cfg getrandom_backend="wasm_js"'
RUN cargo build --locked --release --target wasm32-unknown-unknown && wasm-bindgen --target web --out-dir www/pkg target/wasm32-unknown-unknown/release/numbat_wasm.wasm
FROM scratch AS output
COPY --from=build /source/numbat-wasm/www /
