[global]
error_log = /proc/self/fd/2
daemonize = no
[www]
listen = 0.0.0.0:9000
listen.allowed_clients = 172.29.85.20
pm = ondemand
pm.max_children = 6
pm.process_idle_timeout = 10s
pm.max_requests = 150
request_terminate_timeout = 25s
clear_env = yes
catch_workers_output = yes
decorate_workers_output = no
php_admin_value[memory_limit] = 32M
php_admin_value[max_execution_time] = 22
php_admin_value[output_buffering] = 65536
php_admin_value[error_log] = /proc/self/fd/2
php_admin_flag[log_errors] = on
php_admin_flag[display_errors] = off
php_admin_flag[expose_php] = off
php_admin_flag[file_uploads] = off
php_admin_flag[allow_url_fopen] = off
php_admin_value[open_basedir] = /app:/etc/ssl/certs:/tmp:/proc/self/fd
php_admin_value[disable_functions] = exec,passthru,shell_exec,system,proc_open,popen
