FROM alpine:3.23@sha256:85fe1e81d6758c208f3e1eed4338a1997e19d4be002d4dd32d3100c9a8c010a0
RUN apk add --no-cache tor=0.4.9.13-r0 curl \
    && mkdir -p /var/lib/tor /run/onion \
    && chown 101:101 /var/lib/tor /run/onion
USER 101:101
ENTRYPOINT ["tor", "-f", "/etc/tor/torrc"]
