FROM node:24-alpine@sha256:ebfe2f90462722a7a4de65e91990e97fe0d401c70e0e762c5b53302f905ec1c1 AS vendor
WORKDIR /vendor
COPY vendor/package*.json ./
RUN npm ci --ignore-scripts
FROM nginxinc/nginx-unprivileged:1.28-alpine@sha256:7377697a821c131a924a7105fafbe7414db4e9fcc77a6f08f776f33f141ec3f8
COPY public/ /usr/share/nginx/html/
COPY LICENSE /usr/share/nginx/html/LICENSE.txt
COPY --from=vendor /vendor/node_modules/jszip/dist/jszip.min.js /usr/share/nginx/html/js/libs/jszip.min.js
COPY --from=vendor /vendor/node_modules/jszip/LICENSE.markdown /usr/share/nginx/html/js/libs/JSZIP-LICENSE.txt
COPY --from=vendor /vendor/node_modules/jspdf/dist/jspdf.umd.min.js /usr/share/nginx/html/js/libs/jspdf.umd.min.js
COPY --from=vendor /vendor/node_modules/jspdf/LICENSE /usr/share/nginx/html/js/libs/JSPDF-LICENSE.txt
ENTRYPOINT ["nginx", "-g", "daemon off;"]
