[global]
pid = /run/php/php-fpm.pid
error_log = /proc/self/fd/2
daemonize = no
[rssbridge]
listen = /run/php/rssbridge.sock
pm = ondemand
pm.max_children = 3
pm.process_idle_timeout = 10s
request_terminate_timeout = 45s
clear_env = no
catch_workers_output = yes
php_admin_value[memory_limit] = 64M
php_admin_value[display_errors] = Off
php_admin_value[log_errors] = On
