[global]
error_log = /proc/self/fd/2
daemonize = no
[www]
listen = 0.0.0.0:9000
listen.allowed_clients = 172.29.89.20
chdir = /app/public
pm = ondemand
pm.max_children = 6
pm.process_idle_timeout = 10s
pm.max_requests = 100
request_terminate_timeout = 45s
clear_env = yes
env[ENABLED_ENGINES] = $ENABLED_ENGINES
env[PREF_TL] = en
catch_workers_output = no
php_admin_value[memory_limit] = 48M
php_admin_value[max_execution_time] = 40
php_admin_value[post_max_size] = 24K
php_admin_value[max_input_vars] = 80
php_admin_value[error_log] = /dev/null
php_admin_flag[log_errors] = off
php_admin_flag[display_errors] = off
php_admin_flag[expose_php] = off
php_admin_flag[file_uploads] = off
php_admin_flag[allow_url_fopen] = off
php_admin_value[open_basedir] = /app:/etc/ssl/certs:/tmp:/dev/null
php_admin_value[disable_functions] = exec,passthru,shell_exec,system,proc_open,popen
php_admin_value[session.save_path] = /tmp
php_admin_value[session.gc_maxlifetime] = 300
php_admin_value[session.gc_probability] = 1
php_admin_value[session.gc_divisor] = 1
php_admin_flag[session.use_strict_mode] = on
php_admin_flag[session.use_only_cookies] = on
php_admin_flag[session.cookie_secure] = on
php_admin_flag[session.cookie_httponly] = on
php_admin_value[session.cookie_samesite] = Lax
php_admin_value[apc.shm_size] = 8M
