FROM ghcr.io/jordan-dalby/bytestash:1.5.14@sha256:b684e4df3214594035f45c8f202cf9602ac80e4d2dc5c938a73cfcc0a0bb5d3f
COPY server/src/routes/oidcRoutes.js /app/src/routes/oidcRoutes.js
COPY client/build/ /client/build/
