FROM python:3.13-slim@sha256:3dd7cc108ec1493442514f5c2a871af6af0ec31d768ff6e378a93340c3b3db5f AS build
RUN apt-get update && apt-get install -y --no-install-recommends build-essential pkg-config libssl-dev ca-certificates curl \
 && rm -rf /var/lib/apt/lists/*
WORKDIR /build
RUN curl -fsSL https://github.com/squid-cache/squid/releases/download/SQUID_7_7/squid-7.7.tar.gz -o squid.tar.gz \
 && echo '5b05417d681c3cca275bc48ede12ee50a3e7d60cb47fb94522ee3a66022a8c59  squid.tar.gz' | sha256sum -c - \
 && tar -xzf squid.tar.gz \
 && cd squid-7.7 \
 && ./configure --prefix=/opt/squid --with-openssl --disable-icmp --disable-snmp --disable-wccp --disable-wccpv2 --disable-auth --disable-external-acl-helpers --disable-url-rewrite-helpers --disable-log-daemon-helpers --without-libxml2 --disable-esi --with-default-user=nobody \
 && make -j2 \
 && make install
FROM python:3.13-slim@sha256:3dd7cc108ec1493442514f5c2a871af6af0ec31d768ff6e378a93340c3b3db5f
COPY --from=build /opt/squid /opt/squid
USER 65534:65534
CMD ["/opt/squid/sbin/squid", "--foreground", "-f", "/etc/squid/squid.conf", "-N"]
