// Synthetic, bounded functional/security checks. No visitor data or outside calls.
import { createRequire } from 'node:module';
import { strict as assert } from 'node:assert';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
const require = createRequire(new URL('../../portal/package.json', import.meta.url));
const { chromium } = require('@playwright/test');
const base = process.env.MARKMAP_TEST_URL || 'http://10.10.1.43:3168';
const shots = '/home/ubuntu/freetools/.impeccable/captures/markmap';
await mkdir(shots, { recursive: true });
const browser = await chromium.launch({ headless: true });
const context = await browser.newContext({ viewport: { width: 1365, height: 1000 }, acceptDownloads: true });
const page = await context.newPage();
const failures = []; const outside = []; const requests = [];
page.on('pageerror', e => failures.push(e.message));
page.on('request', r => { requests.push(r.url()); if (!r.url().startsWith(base) && !r.url().startsWith('blob:')) outside.push(r.url()); });
page.on('dialog', d => d.accept());
const ready = async () => { await page.locator('#svg:enabled').waitFor(); assert.equal(await page.locator('#error').isVisible(), false, await page.locator('#error').textContent()); };
try {
  const response = await page.goto(`${base}/?lang=en`); assert.equal(response.status(), 200);
  const csp = response.headers()['content-security-policy']; assert(csp.includes("connect-src 'none'")); assert(!csp.includes('unsafe-eval')); assert(!csp.includes("script-src 'self' 'unsafe-inline'"));
  await ready(); assert((await page.locator('#map').textContent()).includes('Study plan'));
  assert.equal(await page.evaluate(() => localStorage.length), 0);
  await page.screenshot({ path: `${shots}/desktop-en.png`, fullPage: true });
  const fixture = '# Práctica ficticia\n\n## Preparar\n- Leer: año, acción, ñ\n\n## Revisar\n- Guardar una copia\n';
  await page.locator('#outline').fill(fixture); await ready();
  const mdDownload = page.waitForEvent('download'); await page.locator('#markdown').click();
  const md = await mdDownload; assert.equal(await readFile(await md.path(), 'utf8'), fixture);
  await page.locator('#remember').check(); await ready(); await page.reload(); await ready();
  assert.equal(await page.locator('#outline').inputValue(), fixture);
  await page.locator('#remember').uncheck(); await ready(); assert.equal(await page.evaluate(() => localStorage.length), 0);
  await page.locator('#clear').click(); assert.equal(await page.locator('#outline').inputValue(), '');
  await page.locator('#file').setInputFiles({ name: 'outline.md', mimeType: 'text/markdown', buffer: Buffer.from(fixture) }); await ready();
  assert.equal(await page.locator('#outline').inputValue(), fixture);
  const svgDownload = page.waitForEvent('download'); await page.locator('#svg').click();
  const svg = await readFile(await (await svgDownload).path(), 'utf8');
  await writeFile(`${shots}/export.svg`, svg);
  assert(svg.includes('Práctica')); assert(!/<script|<iframe|<image|\son\w+=|(?:href|src)=["']https?:/i.test(svg));
  const exportPage = await context.newPage();
  await exportPage.route('https://synthetic-export.example/map.svg', route => route.fulfill({ status: 200, contentType: 'image/svg+xml', body: svg }));
  await exportPage.goto('https://synthetic-export.example/map.svg');
  assert.equal(await exportPage.locator('parsererror').count(), 0);
  assert((await exportPage.locator('foreignObject').count()) >= 5);
  await exportPage.screenshot({ path: `${shots}/svg-export.png`, fullPage: false, timeout: 10000 }); await exportPage.close();
  const hostile = '---\nmarkmap:\n  extraJs: [https://attacker.invalid/a.js]\n  extraCss: [https://attacker.invalid/a.css]\n  htmlParser: {selector: script}\n---\n# Safe title\n\n- <img src="https://attacker.invalid/leak" onerror="window.__pwned=1">\n- [click](javascript:alert(1))\n- ![image](https://attacker.invalid/image)\n- <svg onload="window.__pwned=1"></svg>\n- **Good text**\n';
  await page.locator('#outline').fill(hostile); await ready();
  assert.equal(await page.evaluate(() => window.__pwned), undefined);
  assert.equal(await page.locator('#map img, #map script, #map a, #map iframe, #map svg svg').count(), 0);
  assert((await page.locator('#map').textContent()).includes('Good text'));
  const tooBig = Buffer.alloc(400001, 'a');
  await page.locator('#file').setInputFiles({ name: 'large.md', mimeType: 'text/markdown', buffer: tooBig });
  assert(await page.locator('#error').isVisible()); assert.equal(await page.locator('#outline').inputValue(), hostile);
  await page.locator('#file').setInputFiles({ name: 'invalid.md', mimeType: 'text/markdown', buffer: Buffer.from([0xff, 0xfe]) });
  assert(await page.locator('#error').isVisible());
  await page.locator('#language').selectOption('es'); await page.locator('#outline').fill(fixture); await ready();
  assert.equal(await page.locator('html').getAttribute('lang'), 'es');
  await page.setViewportSize({ width: 390, height: 844 });
  assert(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await page.screenshot({ path: `${shots}/mobile-es.png`, fullPage: true });
  await context.setOffline(true);
  await page.locator('#outline').fill('# Sin conexión\n- Ensayo local'); await ready();
  assert((await page.locator('#map').textContent()).includes('Sin conexión'));
  await context.setOffline(false);
  // Draft consent must remain effective even when the renderer rejects input.
  await page.locator('#outline').fill(fixture); await ready();
  await page.locator('#remember').check(); await ready();
  await page.locator('#outline').fill('# Large synthetic map\n' + '- item\n'.repeat(2010));
  await page.locator('#error').filter({ hasText: /2000|2,000/ }).waitFor();
  await page.locator('#remember').uncheck();
  assert.equal(await page.evaluate(() => localStorage.getItem('utilibre-markmap-draft-v1')), null);
  await page.reload(); await ready();
  assert(!(await page.locator('#outline').inputValue()).includes('Large synthetic map'));
  await page.locator('#remember').check(); await ready();
  await page.evaluate(() => { Storage.prototype.setItem = () => { throw new DOMException('Synthetic quota failure', 'QuotaExceededError'); }; });
  await page.locator('#outline').fill('# Draft not saved\n- Keep this text');
  await page.locator('#error').filter({ hasText: /almacenamiento/ }).waitFor();
  assert.equal(await page.evaluate(() => {
    const event = new Event('beforeunload', { cancelable: true }); window.dispatchEvent(event); return event.defaultPrevented;
  }), true);
  await page.evaluate(() => { Storage.prototype.removeItem = () => { throw new DOMException('Synthetic denial', 'SecurityError'); }; });
  await page.locator('#clear').click();
  assert(await page.locator('#error').isVisible());
  assert(!(await page.locator('#status').textContent()).includes('eliminó'));
  assert.deepEqual(outside, []); assert.deepEqual(failures, []);
  assert.equal((await context.request.get(`${base}/missing-page`)).status(), 404);
  assert.equal((await context.request.post(`${base}/`, { data: 'fictional' })).status(), 405);
  console.log(JSON.stringify({ result: 'PASS', date: new Date().toISOString(), base, checks: ['EN/ES', 'Markdown roundtrip', 'opt-in draft/reload/removal', 'render failure still removes draft', 'quota failure protects unsaved edits', 'storage denial never claims deletion', 'SVG reopen', 'hostile imports', 'oversize/invalid UTF8', '390px layout', 'already-loaded offline editing', 'strict CSP', '404/405'], externalRequests: outside, pageErrors: failures, requests: [...new Set(requests)], screenshots: shots }, null, 2));
} finally { await browser.close(); }
