FROM docker.io/corentinth/it-tools:2024.10.22-7ca5933@sha256:8b8128748339583ca951af03dfe02a9a4d7363f61a216226fc28030731a5a61f AS upstream
FROM node:24-alpine@sha256:ebfe2f90462722a7a4de65e91990e97fe0d401c70e0e762c5b53302f905ec1c1 AS assets
WORKDIR /app
COPY --from=upstream /usr/share/nginx/html /app
COPY prepare-secure-random.mjs secure-random.mjs /integration/
RUN node /integration/prepare-secure-random.mjs ittools
FROM nginxinc/nginx-unprivileged:1.28-alpine@sha256:7377697a821c131a924a7105fafbe7414db4e9fcc77a6f08f776f33f141ec3f8
COPY --from=assets /app /usr/share/nginx/html
ENTRYPOINT ["nginx", "-g", "daemon off;"]
