FROM node:22-alpine@sha256:0a7108bf6c7bf5de370ffb1a3ed6be93d405b43ff159f681a8d18c0e2bc2e402 AS build
WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1 NODE_OPTIONS=--openssl-legacy-provider
COPY . .
RUN npm ci --legacy-peer-deps --no-audit --no-fund
RUN npm run build
FROM nginxinc/nginx-unprivileged:1.28-alpine@sha256:7377697a821c131a924a7105fafbe7414db4e9fcc77a6f08f776f33f141ec3f8
COPY --from=build /app/out /usr/share/nginx/html
COPY --from=build /app/LICENSE /usr/share/nginx/html/LICENSE.txt
ENTRYPOINT ["nginx", "-g", "daemon off;"]
