FROM node:22-alpine@sha256:0a7108bf6c7bf5de370ffb1a3ed6be93d405b43ff159f681a8d18c0e2bc2e402 AS unpack
WORKDIR /app
RUN wget -q https://github.com/jgraph/drawio/releases/download/v32.0.2/draw.war -O draw.war && echo '3cb8abec8e9bfc7504760c9cdc9194ecf7e8de178aa2a1d668801c32ecf1a1a7  draw.war' | sha256sum -c - && unzip -q draw.war -d public
COPY drawio-PreConfig.js public/js/PreConfig.js
COPY version-drawio-config.mjs /app/version-drawio-config.mjs
RUN node /app/version-drawio-config.mjs /app/public
FROM nginxinc/nginx-unprivileged:1.28-alpine@sha256:7377697a821c131a924a7105fafbe7414db4e9fcc77a6f08f776f33f141ec3f8
COPY --from=unpack /app/public /usr/share/nginx/html
ENTRYPOINT ["nginx", "-g", "daemon off;"]
