#!/usr/bin/env python3
"""MIT-licensed build asset generator: no recordings or third-party samples.
Creates deterministic white/pink/brown noise loops, a short sine alarm, and silence.
The resulting generated audio is offered under CC0-1.0.
"""
import array, math, pathlib, random, sys, wave
root=pathlib.Path(sys.argv[1]); (root/'noise').mkdir(parents=True,exist_ok=True)
rate=22050
rng=random.Random(20261009)
n=rate*30
white=[rng.uniform(-1,1) for _ in range(n)]
brown=[]; accumulator=0.0
pink=[]; filters=[0.0]*6
for x in white:
 accumulator=(accumulator+0.02*x)/1.02; brown.append(accumulator)
 for j in range(6):
  alpha=2**(-j-1); filters[j]=(1-alpha)*filters[j]+alpha*x
 pink.append(sum(filters))
def save(name,values,peak=0.18):
 maximum=max(max(abs(v) for v in values),1e-12)
 pcm=array.array('h',(int(max(-1,min(1,v/maximum*peak))*32767) for v in values))
 if sys.byteorder!='little':pcm.byteswap()
 with wave.open(str(root/name),'wb') as f:
  f.setnchannels(1);f.setsampwidth(2);f.setframerate(rate);f.writeframes(pcm.tobytes())
for name,values in [('white',white),('pink',pink),('brown',brown)]:save('noise/'+name+'-noise.wav',values)
save('alarm.wav',[math.sin(2*math.pi*660*i/rate)*math.sin(math.pi*i/rate)**2 for i in range(rate)],0.15)
save('silence.wav',[0.0]*rate)
(root/'LICENSE.txt').write_text('Generated by generate-moodist-audio.py; no recordings or third-party samples.\nTo the extent copyright applies, this generated audio is dedicated under CC0-1.0: https://creativecommons.org/publicdomain/zero/1.0/\n')
