import assert from 'node:assert/strict';import {readFile,writeFile} from 'node:fs/promises';import {execFileSync} from 'node:child_process';
process.umask(0o077);const origin='https://kitchen.utilibre.org',report='/opt/utilibre/reports/kitchenowl-20261009';const tokens=JSON.parse(await readFile('/opt/utilibre/kitchenowl/private/qa-tokens.json','utf8'));const headers={Authorization:'Bearer '+tokens.access_token,'Content-Type':'application/json'};
async function api(path,method='GET',data){const r=await fetch(origin+'/api'+path,{method,headers,body:data?JSON.stringify(data):undefined});const text=await r.text();assert(r.ok,`${method} ${path}: ${r.status}`);return text?JSON.parse(text):null;}
const user=await api('/user');assert.equal(user.username,'utilibre-check-a');assert(!user.admin);
const a=await api('/household','POST',{name:'Utilibre fictional kitchen A 20261009'});const b=await api('/household','POST',{name:'Utilibre fictional kitchen B 20261009'});await writeFile(report+'/fixture.json',JSON.stringify({userId:user.id,householdA:a.id,householdB:b.id}));
const example={items:[{name:'Fictional apples',category:'Fictional pantry'}],recipes:[{name:'Fictional apple bowl',description:'Cut fictional apples and serve.',yields:2,items:[{name:'Fictional apples',description:'2 pieces'}],tags:['Fictional']}],shoppinglists:['Fictional groceries']};await api(`/household/${a.id}/import`,'POST',example);
const exported=await api(`/household/${a.id}/export`);assert(exported.items.some(x=>x.name==='Fictional apples'));assert(exported.recipes.some(x=>x.name==='Fictional apple bowl'));await writeFile(report+'/export.json',JSON.stringify(exported,null,2));await api(`/household/${b.id}/import`,'POST',exported);const imported=await api(`/household/${b.id}/export`);assert(imported.recipes.some(x=>x.name==='Fictional apple bowl'));assert(imported.items.some(x=>x.name==='Fictional apples'));
const denied=await fetch(origin+`/api/household/${a.id}/export`);assert.equal(denied.status,401);
const snapshot=execFileSync('python3',['deployment/kitchenowl/backup.py'],{encoding:'utf8'}).trim();const restored=JSON.parse(await readFile(snapshot+'/RESTORE-VERIFIED.json','utf8'));assert(restored.counts.household>=2);assert(restored.counts.recipe>=2);
await api(`/household/${a.id}`,'DELETE');await api(`/household/${b.id}`,'DELETE');await api('/user','DELETE');const revoked=await fetch(origin+'/api/user',{headers});assert([401,422].includes(revoked.status));
await writeFile(report+'/data-result.json',JSON.stringify({checkedAt:new Date().toISOString(),nativeOidc:true,nativeJsonExport:true,nativeImportIntoSecondHousehold:true,checkedItemsAndRecipes:true,anonymousExportDenied:true,isolatedBackupRestore:true,nativeHouseholdAndAccountDeletion:true,tokenRevoked:true,publicHttps:true},null,2));console.log('KitchenOwl fictional native export/import/isolated restore/household+account deletion passed.');
