FROM node:24.14.0-alpine3.23@sha256:7fddd9ddeae8196abf4a3ef2de34e11f7b1a722119f91f28ddf1e99dcafdf114 AS build
WORKDIR /app
COPY package.json pnpm-lock.yaml ./
RUN npm exec --yes --package=pnpm@10.30.3 -- pnpm install --frozen-lockfile
COPY . .
ENV VITE_SITE_URL=https://calendar.utilibre.org \
    CALINO_ENABLE_SW=false \
    CALINO_CONTACT_EMAIL=admin@utilibre.org \
    CALINO_SELF_HOSTED=false
RUN npm exec --yes --package=pnpm@10.30.3 -- pnpm build
FROM scratch AS assets
COPY --from=build /app/dist /dist
