[server]
hosts = 0.0.0.0:5232
max_connections = 20
max_content_length = 10485760
max_resource_size = 1048576
timeout = 30

[auth]
type = htpasswd
htpasswd_filename = /run/radicale/users
htpasswd_encryption = bcrypt
delay = 2

[rights]
type = owner_only

[storage]
filesystem_folder = /var/lib/radicale/collections
folder_umask = 0077

[sharing]
type = none

[logging]
level = warning
mask_passwords = True
bad_put_request_content = False
request_header_on_debug = False
request_content_on_debug = False
response_header_on_debug = False
response_content_on_debug = False
