enabled = true;
rules {
  AUTH_DNS_TEMPFAIL {
    action = "soft reject";
    expression = "DMARC_DNSFAIL | (R_DKIM_TEMPFAIL & !DMARC_POLICY_ALLOW)";
    message = "Temporary authentication DNS failure";
  }
}
