import { test, expect } from '@playwright/test';
test('local selections, keyboard order, export/import, preview and scoped reset', async ({ page, browser }) => {
  await page.goto('/en/my-utilibre');
  await page.getByLabel('Choose a tool to pin').selectOption('drawio'); await page.getByRole('button', { name: 'Pin tool', exact: true }).click();
  await page.getByLabel('Choose a tool to pin').selectOption('rawgraphs'); await page.getByRole('button', { name: 'Pin tool', exact: true }).click();
  const up = page.locator('[data-tool-id="rawgraphs"] button[data-direction="-1"]'); await up.focus(); await page.keyboard.press('Enter');
  await expect(page.locator('.toolkit-list li').first()).toHaveAttribute('data-tool-id', 'rawgraphs');
  await page.getByText('Manage collections', { exact: true }).click();
  await page.getByLabel('Collection name').fill('Workshop <img src=x onerror=alert(1)>'); await page.getByRole('button', { name: 'Rename', exact: true }).click();
  await expect(page.getByLabel('Collection name')).toBeFocused();
  await expect(page.locator('.toolkit-list img')).toHaveCount(0);
  const event = page.waitForEvent('download'); await page.getByRole('button', { name: 'Export all collections' }).click(); const file = await event;
  const link = await page.getByLabel('Collection link', { exact: true }).inputValue();
  const other = await browser.newContext(); const recipient = await other.newPage(); await recipient.goto(link);
  await expect(recipient.getByRole('heading', { name: 'Shared collection preview' })).toBeVisible();
  expect(await recipient.evaluate(() => localStorage.getItem('portal.toolkits.v1'))).toBeNull();
  await recipient.getByRole('button', { name: 'Save a copy to my collections' }).click();
  expect(JSON.parse((await recipient.evaluate(() => localStorage.getItem('portal.toolkits.v1')))! ).collections).toHaveLength(2);
  await other.close();
  await page.evaluate(() => localStorage.setItem('document-example', 'untouched'));
  page.on('dialog', d => d.accept()); await page.getByRole('button', { name: 'Reset only toolkit preferences' }).click();
  expect(await page.evaluate(() => localStorage.getItem('document-example'))).toBe('untouched');
  await page.getByLabel('Import collections').setInputFiles(await file.path() as string);
  await page.getByRole('button', { name: 'Import and replace collections' }).click();
  await expect(page.locator('.toolkit-list li').first()).toHaveAttribute('data-tool-id', 'rawgraphs');
  await page.reload(); await expect(page.locator('.toolkit-list li')).toHaveCount(2);
  const before = await page.evaluate(() => localStorage.getItem('portal.toolkits.v1'));
  await page.getByLabel('Import collections').setInputFiles({ name: 'bad.json', mimeType: 'application/json', buffer: Buffer.from('{"version":999}') });
  await page.getByRole('button', { name: 'Import and replace collections' }).click(); await expect(page.getByRole('status')).toContainText('Import rejected');
  expect(await page.evaluate(() => localStorage.getItem('portal.toolkits.v1'))).toBe(before);
});
test('collection management preserves keyboard position', async ({ page }) => {
  await page.goto('/en/my-utilibre');
  await page.getByText('Manage collections', { exact: true }).click();
  await page.getByRole('button', { name: 'Create another collection' }).click();
  await expect(page.getByLabel('Collection name')).toBeFocused();
  await page.getByRole('button', { name: 'Use as starting collection' }).click();
  await expect(page.locator('#toolkit-collection')).toBeFocused();
  page.on('dialog', d => d.accept());
  await page.getByRole('button', { name: 'Delete this collection' }).click();
  await expect(page.locator('#toolkit-collection')).toBeFocused();
});
test('blocked storage and malformed share are explicit', async ({ page }) => {
  await page.addInitScript(() => { Object.defineProperty(window, 'localStorage', { get: () => { throw new Error('blocked'); } }); });
  await page.goto('/es/mi-utilibre#collection=invalid');
  await expect(page.getByRole('heading', { name: 'Colección compartida inválida' })).toBeVisible();
  await page.getByLabel('Elegí una herramienta para fijar').selectOption('drawio'); await page.getByRole('button', { name: 'Fijar herramienta', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('No se guardó');
  await expect(page.getByRole('button', { name: 'Exportar todas las colecciones' })).toBeEnabled();
});
