import type { PracticalGuide } from './practical-guide-data.ts';

export const accountAdditionGuides: PracticalGuide[] = [
  {
    id: 'opengist', paths: { en: 'guides/git-snippets', es: 'guias/fragmentos-git' },
    tools: [{ id: 'opengist', label: { en: 'Open Opengist', es: 'Abrir Opengist' } }], samples: [], reviewedOn: '2026-10-09',
    copy: {
      en: {
        title: 'Keep code snippets with Git history', intro: "Keep a small code file, compare revisions and choose private, unlisted or public access.", prerequisites: 'Sign in with an approved, verified Utilibre account. Begin with fictional code containing no passwords or keys.',
        steps: ['Create a snippet, name its file and choose its visibility before saving. Private is access-controlled; anyone with an unlisted link can read it, and public snippets are discoverable.', 'Edit and save another revision. Use the history view to compare revisions. Deleting a secret from the latest text does not remove it from earlier Git history.', 'Download ZIP for the selected revision’s files. For reachable files and revision history, use the native HTTPS Git clone URL. Private Git operations require a scoped access token from Settings → Access tokens; never publish the token.', 'Open the downloaded files or clone locally. ZIP omits history, comments, likes, permissions and account settings; Git omits application metadata and access rules. Keep your independent copy private.', 'Delete the snippet through its native controls when finished. Revoke unused access tokens separately. Account deletion is under Settings. Recipients and backups can retain earlier copies.'],
        success: 'Fictional private/unlisted/public access, revision ZIP, HTTPS Git clone/edit/push, native deletion and an isolated full-service restore were checked. Public OIDC also passed.', troubleshooting: 'SSH Git is disabled; use HTTPS. Archived snippets are read-only. An archive is not deletion. If Git fails, check token scope and the canonical hostname.', privacy: 'Files and history are plaintext on the server. Private access is not end-to-end encryption. Gravatar is disabled. Operational logs rotate by size; daily same-VM backups have no configured automatic expiry.', next: 'Keep the Git clone when revision history matters; use PrivateBin for a short encrypted, expiring message instead.',
      },
      es: {
        title: 'Guardá fragmentos de código con historial Git', intro: "Guardá un archivo pequeño de código, compará sus versiones y elegí acceso privado, no listado o público.", prerequisites: 'Iniciá sesión con una cuenta de Utilibre aprobada y verificada. Empezá con código ficticio sin contraseñas ni claves.',
        steps: ['Creá un fragmento, nombrá su archivo y elegí la visibilidad antes de guardarlo. Privado restringe el acceso; cualquiera con un enlace no listado puede leerlo, y los fragmentos públicos se pueden descubrir.', 'Editá y guardá otra revisión. Comparalas desde el historial. Quitar una clave del texto actual no la elimina de las revisiones anteriores de Git.', 'Elegí Download ZIP para descargar los archivos de la revisión seleccionada. Para conservar archivos e historial accesible, usá la URL Git HTTPS nativa. Las operaciones privadas requieren un token con el alcance necesario desde Settings → Access tokens; nunca lo publiques.', 'Abrí los archivos o el clon en tu dispositivo. El ZIP omite historial, comentarios, favoritos, permisos y ajustes; Git omite metadatos de la aplicación y reglas de acceso. Guardá la copia independiente en privado.', 'Eliminá el fragmento desde sus controles nativos al terminar. Revocá por separado los tokens que ya no necesitás. La cuenta se elimina desde Settings. Los destinatarios y las copias de seguridad pueden conservar versiones anteriores.'],
        success: 'Se probaron accesos privados, no listados y públicos, ZIP de revisión, clonación/edición/envío Git HTTPS, borrado nativo y restauración aislada del servicio. También pasó el acceso OIDC público.', troubleshooting: 'Git por SSH está desactivado; usá HTTPS. Los fragmentos archivados son de solo lectura: archivar no es borrar. Si Git falla, revisá el alcance del token y el dominio.', privacy: 'Los archivos y el historial se guardan sin cifrado de extremo a extremo en el servidor. Gravatar está desactivado. Los registros rotan por tamaño; las copias diarias en esta VM no tienen borrado automático configurado.', next: 'Conservá un clon Git si necesitás el historial. Para un mensaje breve cifrado y con vencimiento, usá PrivateBin.',
      },
    },
  },
  {
    id: 'linkding', paths: { en: 'guides/bookmarks', es: 'guias/marcadores' },
    tools: [{ id: 'linkding', label: { en: 'Open linkding', es: 'Abrir linkding' } }], samples: [], reviewedOn: '2026-10-09',
    copy: {
      en: {
        title: 'Keep and export your bookmarks', intro: "Save links with notes and tags so you can find them later, then keep a bookmark export of your own.", prerequisites: 'Use an approved, verified Utilibre account. Start with a harmless public URL; do not save secret-bearing links as a test.',
        steps: ['Add a bookmark and review its title, description, notes and tags. Fetching page metadata can contact the destination from the server.', 'Leave sharing disabled for private bookmarks. Enabling a public/shared view changes who can read the selected records.', 'Open Settings → Export to download Netscape bookmark HTML. It includes linkding notes, tags, timestamps and archive/unread/shared markers, but not account settings, API tokens, bundles or cached assets.', 'Use Settings → Import in a compatible linkding installation. Review its sharing option before importing; other browser bookmark importers may omit linkding-specific fields. Check a note and a tag after import.', 'Delete bookmarks through their native menu. Revoke API tokens separately. Request account deletion through the private operator contact; no self-service account-deletion path was verified.'],
        success: 'Fictional bookmark HTML export/import preserved notes, tags and archive/unread state. Native deletion, public OIDC and an isolated full-service restore passed.', troubleshooting: 'Background favicons, snapshots, external archives and asset uploads are disabled here even if a profile toggle appears. This instance saves bookmarks, not a guaranteed copy of each destination page.', privacy: 'URLs, notes and account metadata are server-readable. Default sharing is off. Logs may contain failed-request URLs; size rotation is not a fixed retention period. Daily same-VM backups have no configured automatic expiry.', next: 'Keep the HTML export independently and reopen important destination content before relying on a saved link.',
      },
      es: {
        title: 'Guardá y exportá tus marcadores', intro: "Guardá enlaces con notas y etiquetas para encontrarlos después y conservá tu propia exportación de marcadores.", prerequisites: "Usá una cuenta de Utilibre aprobada y verificada. Empezá con una URL pública inocua; no probés con enlaces que contengan claves.",
        steps: ['Agregá un marcador y revisá título, descripción, notas y etiquetas. Obtener metadatos puede contactar el destino desde el servidor.', 'Dejá desactivado el uso compartido para conservar marcadores privados. Activar una vista pública o compartida cambia quién puede leer los registros seleccionados.', 'Abrí Settings → Export para descargar HTML de marcadores Netscape. Incluye notas, etiquetas, fechas y marcas de archivado, lectura y uso compartido de linkding; no incluye ajustes, tokens, agrupaciones personalizadas ni recursos en caché.', 'Usá Settings → Import en una instalación compatible de linkding. Revisá la opción de compartir antes de importar; otros importadores del navegador pueden omitir campos propios de linkding. Comprobá una nota y una etiqueta.', 'Eliminá marcadores desde su menú nativo. Revocá los tokens por separado. Solicitá el borrado de la cuenta mediante el contacto privado del operador; no se verificó un recorrido de autoservicio para eso.'],
        success: 'La exportación e importación HTML ficticia conservó notas, etiquetas y estados de archivo y lectura. Pasaron el borrado nativo, OIDC público y una restauración aislada del servicio.', troubleshooting: 'Los iconos de sitios, las capturas, los archivos externos y las cargas de recursos están desactivados aunque aparezca algún selector del perfil. Se guardan marcadores, no una copia garantizada de cada página.', privacy: 'El servidor puede leer URLs, notas y metadatos de la cuenta. Compartir está desactivado por defecto. Los registros pueden incluir URLs de solicitudes fallidas; rotar por tamaño no fija un plazo. Las copias diarias en esta VM no tienen borrado automático configurado.', next: 'Conservá el HTML por separado y comprobá el contenido importante antes de depender de un enlace guardado.',
      },
    },
  },
  {
    id: 'vikunja', paths: { en: 'guides/tasks-export', es: 'guias/exportar-tareas' },
    tools: [{ id: 'vikunja', label: { en: 'Open Vikunja', es: 'Abrir Vikunja' } }], samples: [], reviewedOn: '2026-10-09',
    copy: {
      en: {
        title: 'Manage tasks and keep an independent export', intro: "Create a small project, check off a task and save a ZIP you can import into a compatible Vikunja installation.", prerequisites: 'Use an approved, verified Utilibre account and a fictional project. Attach only a disposable test file.',
        steps: ['Create a project, add a task and edit its title or completion state. Check project and link-sharing permissions before inviting anyone.', 'Open Settings → Export your data and request the export. Return to that page to download the ZIP when ready; this installation does not send the email mentioned by upstream UI.', 'The ZIP includes projects/tasks, attachments, saved filters and project backgrounds. It is not a complete migration of identity, teams, permissions, sessions or account settings.', 'Import through Settings → Import your data → Vikunja in a compatible installation. Import creates copies. Check a completed task and reopen its attachment before removing the original.', 'Delete tasks or projects through their menus and revoke shared links separately. Account deletion currently needs operator assistance because native email confirmation cannot be delivered here. Discuss shared ownership before deleting an account.'],
        success: 'Fictional task editing/completion and ZIP export/import preserved attachment bytes. A native dump restored both copies and their files in a network-isolated service. Public OIDC passed.', troubleshooting: 'Attachments are limited to 10 MB; imports to 20 MB, 1,000 files and 100 MB imported storage. Email reminders, external avatars, Unsplash and external import integrations are unavailable.', privacy: 'Tasks and files are server-readable. No Sentry or visitor analytics is enabled. Generated export files expire after seven days; ordinary task data does not have a configured expiry. Daily same-VM backups have no configured automatic deletion.', next: 'Protect downloaded ZIPs and keep regular independent copies; synchronization is not a replacement for your own backup.',
      },
      es: {
        title: 'Organizá tareas y conservá una exportación propia', intro: "Creá un proyecto pequeño, marcá una tarea terminada y guardá un ZIP que podás importar en una instalación compatible de Vikunja.", prerequisites: 'Usá una cuenta de Utilibre aprobada y verificada y un proyecto ficticio. Adjuntá solo un archivo descartable.',
        steps: ['Creá un proyecto, agregá una tarea y cambiá su título o estado. Revisá los permisos del proyecto y de los enlaces antes de invitar a alguien.', 'Abrí Settings → Export your data y pedí la exportación. Volvé a esa página para descargar el ZIP cuando esté listo; esta instalación no envía el correo mencionado en la interfaz original.', 'El ZIP incluye proyectos, tareas, adjuntos, filtros guardados y fondos de proyectos. No migra por completo identidad, equipos, permisos, sesiones ni ajustes de la cuenta.', 'Importá desde Settings → Import your data → Vikunja en una instalación compatible. Se crean copias. Comprobá una tarea completada y abrí su adjunto antes de quitar el original.', 'Eliminá tareas o proyectos desde sus menús y revocá enlaces compartidos por separado. Para borrar la cuenta necesitás asistencia del operador porque aquí no se puede entregar la confirmación por correo. Revisá la propiedad compartida antes de borrar una cuenta.'],
        success: 'Las tareas ficticias y su ZIP conservaron el contenido exacto del adjunto. Una restauración nativa recuperó ambas copias y sus archivos sin acceso a la red. Pasó el acceso OIDC público.', troubleshooting: 'Los adjuntos tienen un límite de 10 MB; las importaciones, 20 MB, 1000 archivos y 100 MB de almacenamiento importado. No hay recordatorios por correo, avatares externos, Unsplash ni integraciones de importación externa.', privacy: 'El servidor puede leer tareas y archivos. Sentry y las estadísticas de visitantes están desactivados. Las exportaciones generadas vencen a los siete días; las tareas no tienen vencimiento configurado. Las copias diarias de esta VM no tienen borrado automático configurado.', next: 'Protegé los ZIP descargados y guardá copias independientes con regularidad; sincronizar no reemplaza tu propio respaldo.',
      },
    },
  },
  {
    id: 'bytestash', paths: { en: 'guides/snippet-library', es: 'guias/biblioteca-codigo' },
    tools: [{ id: 'bytestash', label: { en: 'Open ByteStash', es: 'Abrir ByteStash' } }], samples: [], reviewedOn: '2026-10-09',
    copy: {
      en: {
        title: 'Build and export a snippet library', intro: "Keep related code snippets together, add categories and download a JSON copy.", prerequisites: 'Sign in with an approved, verified Utilibre account. Use fictional code and remove credentials before saving or sharing.',
        steps: ['Choose New snippet, enter a title and add named code fragments. Leave Make snippet public off for private records.', 'Share only when needed. An unlisted share grants access to anyone with its link; Require authentication admits any valid local account with the link, not selected recipients. Set an expiry and revoke the link when finished.', 'Open Settings → Export Snippets (JSON). It includes active snippets and code, descriptions, categories and metadata. It omits account settings, API keys and sharing credentials; recycled entries are not included.', 'Use Import Snippets to select that JSON in a compatible ByteStash installation. New copies are created; compare a filename and its code. Markdown export is a readable copy, not an account backup.', 'Move unwanted snippets to Recycle Bin, restore them there or delete permanently. Recycled records expire after 30 days. Revoke API keys and shares separately. Ask the private operator contact for account deletion.'],
        success: 'Native JSON download/import preserved exact fictional code. Private access, share protection/revocation, recycle/restore, public OIDC and an isolated full-service restore passed.', troubleshooting: 'External URL imports and remote Markdown images are blocked; import local files instead. Native editor assets and release notes are served locally. The application does not provide Git history.', privacy: 'Code and metadata are plaintext server-side. Native login/preferences persist in browser storage. No visitor tracking was added. Daily same-VM backups have no configured automatic expiry; deleting live data does not delete downloaded copies.', next: 'Keep your JSON independently; use Opengist when Git revisions and HTTPS clone/push are needed.',
      },
      es: {
        title: 'Armá y exportá una biblioteca de código', intro: "Reuní fragmentos de código relacionados, agregá categorías y descargá una copia JSON.", prerequisites: 'Iniciá sesión con una cuenta de Utilibre aprobada y verificada. Usá código ficticio y quitá credenciales antes de guardar o compartir.',
        steps: ['Elegí New snippet, escribí un título y agregá fragmentos con nombre. Dejá Make snippet public desactivado para registros privados.', 'Compartí solo lo necesario. Un enlace no listado permite el acceso a quien lo tenga; Require authentication admite cualquier cuenta local válida con el enlace, no destinatarios elegidos. Configurá un vencimiento y revocá el enlace al terminar.', 'Abrí Settings → Export Snippets (JSON). Incluye fragmentos activos, código, descripciones, categorías y metadatos. Omite ajustes, claves API y credenciales de uso compartido; tampoco incluye elementos de la papelera.', 'Elegí Import Snippets para seleccionar ese JSON en una instalación compatible. Se crean copias nuevas; compará un nombre de archivo y su código. Exportar Markdown produce una copia legible, no un respaldo de la cuenta.', 'Mové los fragmentos que no necesitás a Recycle Bin; desde ahí podés restaurarlos o borrarlos definitivamente. Vencen a los 30 días en la papelera. Revocá claves API y enlaces por separado. Pedí el borrado de la cuenta al contacto privado del operador.'],
        success: 'La descarga e importación JSON conservó el código ficticio exacto. Pasaron el acceso privado, la protección y revocación de enlaces, la papelera, OIDC público y una restauración aislada del servicio.', troubleshooting: 'Se bloquean las importaciones de URLs externas y las imágenes remotas de Markdown; importá archivos locales. El editor y las notas de versión se sirven localmente. La aplicación no ofrece historial Git.', privacy: 'El servidor guarda código y metadatos sin cifrado de extremo a extremo. El acceso y las preferencias persisten en el navegador. No se agregó rastreo de visitantes. Las copias diarias de esta VM no tienen borrado automático configurado; borrar datos activos no borra descargas.', next: 'Guardá tu JSON por separado; usá Opengist si necesitás revisiones Git y clonar o enviar cambios por HTTPS.',
      },
    },
  },
  {
    id: 'openresume', paths: { en: 'guides/local-resume', es: 'guias/curriculum-local' },
    tools: [{ id: 'openresume', path: '/resume-builder', label: { en: 'Build a local resume', es: 'Crear un currículum local' } }, { id: 'openresume', path: '/resume-parser', label: { en: 'Inspect a resume PDF', es: 'Examinar un PDF de currículum' } }], samples: [], reviewedOn: '2026-10-09',
    copy: {
      en: {
        title: 'Create and inspect a resume locally', intro: "Write a résumé in your browser, download its PDF and check the text the parser reads. No account is needed.", prerequisites: 'Use a current browser and fictional details for your first test. The native interface is English.',
        steps: ['Open Builder and fill the profile and relevant sections. Review the preview and remove example details before using a real resume.', 'Choose Download Resume and reopen the PDF. Check names, accents, line breaks and links. The PDF is not encrypted automatically.', 'Open Parser and select your saved PDF to inspect the extracted text. PDF import reconstructs fields heuristically; it does not guarantee the original formatting or every field.', 'Reloading or closing the tab can preserve editable work in browser storage. Keep your independent PDF; this is not a lossless editable-project export.', 'On a shared device, clear this tool’s site data when finished. Delete downloaded PDFs separately when no longer needed. There is no server document account to delete.'],
        success: 'A fictional resume was generated as PDF, retained across reload and read by the native parser over real public HTTPS. No file uploads or external HTTP hosts appeared.', troubleshooting: 'Complex layouts and scanned PDFs may not parse correctly. Review imported fields manually. This local builder does not provide cloud sharing or account synchronization.', privacy: 'Resume processing is local. Browser data can remain after the tab closes, and downloaded files remain until deleted. Analytics and the remote count iframe were removed; fonts/assets are local. Page requests still produce infrastructure connection metadata.', next: 'Keep the final PDF safely and send it only to intended recipients. Use Reactive Resume separately if you need its account-based workflow.',
      },
      es: {
        title: 'Creá y revisá un currículum localmente', intro: "Escribí un currículum en tu navegador, descargá su PDF y revisá el texto que lee el analizador. No necesitás cuenta.", prerequisites: 'Usá un navegador actualizado y datos ficticios en la primera prueba. La interfaz nativa está en inglés.',
        steps: ['Abrí Builder y completá el perfil y las secciones necesarias. Revisá la vista previa y quitá los ejemplos antes de usar un currículum real.', 'Elegí Download Resume y volvé a abrir el PDF. Revisá nombres, acentos, saltos de línea y enlaces. El PDF no se cifra automáticamente.', 'Abrí Parser y seleccioná tu PDF para revisar el texto extraído. La importación reconstruye campos mediante aproximaciones; no garantiza el formato original ni todos los campos.', 'Recargar o cerrar la pestaña puede conservar el trabajo editable en el navegador. Guardá una copia PDF propia; no es una exportación completa y sin pérdidas del proyecto editable.', "En un dispositivo compartido, borrá los datos de este sitio al terminar. Eliminá las descargas por separado cuando ya no las necesités. No hay una cuenta de documentos en el servidor para borrar."],
        success: 'Se generó un PDF ficticio, se comprobó la persistencia al recargar y se leyó con el analizador nativo por HTTPS público. No hubo cargas de archivos ni solicitudes HTTP a otros dominios.', troubleshooting: 'Los diseños complejos y PDF escaneados pueden analizarse mal. Revisá los campos importados. Este editor local no ofrece sincronización de cuentas ni uso compartido en la nube.', privacy: 'El currículum se procesa localmente. Los datos del navegador pueden quedar al cerrar la pestaña y las descargas permanecen hasta que las borrés. Se quitaron las estadísticas y el contador externo; fuentes y recursos son locales. Las visitas generan metadatos de conexión en la infraestructura.', next: 'Guardá el PDF final en un lugar seguro y envialo solo a sus destinatarios. Usá Reactive Resume por separado si necesitás su recorrido con cuenta.',
      },
    },
  },
];
