import type { PracticalGuide } from './practical-guide-data.ts';

export const addyGuides: PracticalGuide[] = [{
  id: 'addy', paths: { en: 'guides/email-aliases', es: 'guias/alias-de-correo' }, tools: [{ id: 'addy', label: { en: 'Manage email aliases', es: 'Gestionar alias de correo' } }], samples: [], reviewedOn: '2026-10-10',
  copy: {
    en: {
      title: 'Use and manage email aliases',
      intro: 'An alias forwards mail to your existing inbox without giving the sender that inbox address. Utilibre runs addy.io for existing, operator-provisioned accounts. An alias is not a temporary mailbox with automatic deletion.',
      prerequisites: 'You need an existing addy.io account and a verified, active recipient mailbox. Public registration is closed; this application has its own login, separate from Utilibre sign-in. Native controls are in English. Utilibre and the mail providers can process readable messages and attachments.',
      steps: [
        'Open the tool and sign in. In Recipients, check that the destination you intend to use is active and verified. Do not use someone else’s mailbox without permission.',
        'In Aliases, choose Create Alias (or Create Your First Alias for an empty account). Choose the available alias domain and format, select your verified recipient and create the alias. Copy the address the app actually generates; an invented address on the shared domain is not automatically yours.',
        'Give that alias to the intended sender. Look for forwarded messages in your selected inbox. To answer through the alias, use Reply on the forwarded message in that inbox. Delivery depends on the participating mail providers.',
        'To stop forwarding, deactivate the alias in Aliases. That retains its record. The native Delete alias action deactivates it and marks it deleted; this is separate from removing your account or previously delivered mail.',
        'For an independent record, open Settings → Account Data → Export Alias Data. Save the downloaded aliases-YYYY-MM-DD.csv and open it in a spreadsheet or text editor. It contains alias attributes, descriptions, activity counters and timestamps, including retained deleted aliases. It does not include a message archive, recipient-routing relationships, all account settings, credentials or signing keys. Protect the file and save any wanted mail from your destination mailbox separately.',
        'Import Aliases on the same page uses a different CSV template with the exact columns alias,description,recipients. It is only for your custom domains, needs valid recipient records and accepts up to 1,000 rows; existing aliases are skipped. The richer export is not directly that import format, and importing does not restore the full account or shared-domain aliases. Completion sends an email. An import round trip has not been tested here.',
        'Revoke unneeded integrations under Settings → API Keys. To remove your account, open Settings → Delete Account, enter your password and confirm Delete Account. This revokes tokens and removes account data, but inactive shared-domain alias reservations and deleted-username reservations may remain. Update important senders before deletion. Forwarded messages, downloaded exports and older backups are not erased by this action.',
      ],
      success: 'Check that a message sent to your alias arrives in your chosen inbox and that your reply reaches the sender. If you exported alias data, open the CSV and check the alias records.',
      troubleshooting: 'Check the alias and recipient are active and the recipient is verified. Incoming messages are limited to 1 MiB. Each user has 100 MiB monthly bandwidth, 60 forwarded/replied messages per hour and 20 new aliases per hour. Retry or rejection policies at other mail providers also apply. Do not publish passwords, API keys, signed action links or private mail when asking for help.',
      privacy: 'The local Proxmox Mail Gateway, addy.io and the sender/destination mail providers process mail. Recipient fields are encrypted at rest with operator-held keys; ordinary forwarding is not end-to-end encrypted. Hetzner hosts the infrastructure in Germany. Cloudflare supplies DNS for this hostname without its HTTP proxy. Local sender authentication queries domain and signing records through DNS; it does not send message contents to a separate scanning service. Retained Postfix blocklist checks also query Spamhaus through the configured resolver, sharing SMTP client IP and mail-domain metadata, not message bodies. Provider retention for these queries is unverified. The persistent queue has a five-day retry lifetime. Daily native cleanup removes failed-delivery records and optional saved messages after seven days; outbound records use seven days with cleanup every six hours. Alias, recipient and account records have no automatic expiry. Daily same-VM backups have no automatic expiry and are not off-site. Native logs can include addresses and request metadata, with both daily-file and size rotation; edge/provider retention is separately unverified. No visitor analytics is configured.',
      next: 'Export your alias records regularly and keep separate copies of important mail. Deactivate an unwanted alias first if you only want to stop forwarding; account deletion has wider consequences.',
    },
    es: {
      title: 'Usá y gestioná alias de correo',
      intro: 'Un alias reenvía correo a tu buzón existente sin darle al remitente la dirección de ese buzón. Utilibre aloja addy.io para cuentas existentes creadas por el operador. Un alias no es un buzón temporal con borrado automático.',
      prerequisites: 'Necesitás una cuenta existente de addy.io y un buzón destinatario verificado y activo. El registro público está cerrado; esta aplicación tiene su propio acceso, separado del inicio de sesión de Utilibre. Los controles nativos están en inglés. Utilibre y los proveedores de correo pueden procesar mensajes y adjuntos legibles.',
      steps: [
        'Abrí la herramienta e iniciá sesión. En Recipients, comprobá que el destino que querés usar esté activo y verificado. No usés el buzón de otra persona sin su permiso.',
        'En Aliases, elegí Create Alias (o Create Your First Alias si la cuenta está vacía). Elegí el dominio y formato disponibles, seleccioná tu destinatario verificado y creá el alias. Copiá la dirección que genere la aplicación; una dirección inventada en el dominio compartido no te pertenece automáticamente.',
        'Dale ese alias al remitente que elijas. Buscá los mensajes reenviados en el buzón que seleccionaste. Para contestar a través del alias, usá Responder en el mensaje reenviado dentro de ese buzón. La entrega depende de los proveedores de correo participantes.',
        'Para detener el reenvío, desactivá el alias en Aliases. Eso conserva su registro. La acción nativa Delete alias lo desactiva y lo marca como eliminado; es distinto de borrar tu cuenta o el correo ya entregado.',
        'Para conservar un registro independiente, abrí Settings → Account Data → Export Alias Data. Guardá aliases-YYYY-MM-DD.csv y abrilo en una hoja de cálculo o un editor de texto. Contiene atributos, descripciones, contadores de actividad y fechas de los alias, incluidos los eliminados que se conserven. No incluye un archivo de mensajes, las asociaciones de destinatarios, todos los ajustes de cuenta, credenciales ni claves de firma. Protegé el archivo y guardá por separado el correo que quieras conservar desde tu buzón destinatario.',
        'Import Aliases, en la misma página, usa otra plantilla CSV con las columnas exactas alias,description,recipients. Solo sirve para tus dominios personalizados, requiere destinatarios válidos y acepta hasta 1.000 filas; omite los alias que ya existen. La exportación más amplia no tiene directamente ese formato y la importación no restaura toda la cuenta ni los alias del dominio compartido. Al finalizar envía un correo. Acá no se probó una importación de ida y vuelta.',
        'Revocá las integraciones que ya no uses en Settings → API Keys. Para borrar tu cuenta, abrí Settings → Delete Account, ingresá tu contraseña y confirmá Delete Account. Eso revoca tokens y quita datos de la cuenta, pero pueden quedar reservas inactivas de alias del dominio compartido y del nombre de usuario eliminado. Actualizá los remitentes importantes antes de borrar. Esta acción no elimina los mensajes reenviados, las exportaciones descargadas ni los respaldos anteriores.',
      ],
      success: 'Comprobá que un mensaje enviado a tu alias llegue al buzón elegido y que tu respuesta le llegue al remitente. Si exportaste los datos de tus alias, abrí el CSV y revisá sus registros.',
      troubleshooting: 'Comprobá que el alias y el destinatario estén activos y que el destinatario esté verificado. Los mensajes entrantes tienen un máximo de 1 MiB. Cada usuario dispone de 100 MiB mensuales, 60 mensajes reenviados o respondidos por hora y 20 alias nuevos por hora. También se aplican las políticas de reintento o rechazo de otros proveedores de correo. No publiqués contraseñas, claves de API, enlaces de acciones firmados ni correo privado al pedir ayuda.',
      privacy: 'Proxmox Mail Gateway local, addy.io y los proveedores del remitente y destinatario procesan el correo. Los campos de destinatarios se cifran en reposo con claves en poder del operador; el reenvío común no está cifrado de extremo a extremo. Hetzner aloja la infraestructura en Alemania. Cloudflare proporciona DNS para este nombre sin su intermediario HTTP. La autenticación local del remitente consulta registros de dominios y firmas mediante DNS; no envía el contenido del mensaje a otro servicio de análisis. Las comprobaciones de listas de bloqueo que conserva Postfix también consultan Spamhaus mediante el resolvedor configurado: comparten metadatos de IP del cliente SMTP y dominios de correo, no el cuerpo del mensaje. No se verificó la conservación de esas consultas por los proveedores. La cola persistente reintenta durante cinco días. La limpieza nativa diaria quita registros de fallos y mensajes guardados opcionalmente después de siete días; los registros de salida usan siete días con limpieza cada seis horas. Los registros de alias, destinatarios y cuentas no vencen automáticamente. Los respaldos diarios en esta máquina virtual no vencen automáticamente ni se guardan fuera de ella. Los registros nativos pueden incluir direcciones y metadatos de solicitudes, con rotación diaria y por tamaño; la conservación del borde y proveedores sigue sin verificarse por separado. No hay analíticas de visitantes configuradas.',
      next: 'Exportá los registros de tus alias con regularidad y conservá copias separadas del correo importante. Desactivá primero un alias que ya no quieras si solo buscás detener el reenvío; borrar la cuenta tiene consecuencias más amplias.',
    },
  },
}];
