import type { PracticalGuide } from './practical-guide-data.ts';
export const beaverhabitsAdditionGuides: PracticalGuide[] = [{
  id: 'personal-habit-records', paths: { en: 'guides/personal-habit-records', es: 'guias/registro-personal-habitos' },
  tools: [{ id: 'beaverhabits', label: { en: 'Open Beaver Habit Tracker', es: 'Abrir Beaver Habit Tracker' } }], samples: [], reviewedOn: '2026-10-09',
  copy: {
    en: {
      title: 'Keep a habit record you can take with you',
      intro: 'Start with one routine you want to remember, such as reading a page. Beaver records your own entries; it does not infer what you do. Accounts need separate operator provisioning.',
      prerequisites: 'Use your provisioned native email/password account. Public registration and Utilibre SSO are not available here. Keep the password safely: email recovery is disabled. The interface uses English labels, and your records are readable on the server rather than end-to-end encrypted.',
      steps: [
        'Sign in with Email and Password, then Continue. Open Add, type the habit name in New item and press Enter. Record a completion for a day and add a short note if useful.',
        'Open the menu and choose Export, then Export JSON. The downloaded JSON includes your email, export time, active habits and their saved records and notes. It omits archived/soft-deleted habits, account settings, credentials and separately stored note-image files. Save needed images separately and protect the export as personal data.',
        'To reopen the copy, use a compatible Beaver installation and choose Import. Select the JSON file, press the cloud-upload button and confirm Yes. New habits gain an (imported) suffix; matching identifiers can merge records. Try an empty account first rather than assuming an import replaces everything. A fictional export was imported into a second account and retained its completion record.',
        'For integrations, API Token at /gui/tokens offers Generate API Token, Reset Token and Delete. A token does not expire automatically; keep it private and delete it when an integration no longer needs access. The native GET /api/v1/habits/export returns the raw habit-list JSON, including archived entries; it is not a complete account or image backup. Do not paste tokens into public support tickets.',
        'The habit trash control first archives an active habit. Using it again on an archived habit marks it as soft-deleted; this does not erase its stored record. To delete the account, first revoke API tokens and save what you need. Open Export → Delete and confirm Yes. The native flow downloads its active-habit JSON before deleting the account, but that download has the same omissions as Export JSON.',
      ],
      success: 'Your downloaded JSON opens as text, and a compatible Beaver import recreates the selected habits and records. Check a completion and note in the imported copy before relying on it.',
      troubleshooting: 'The interface export excludes archived habits. Unarchive needed habits first or use the native raw-list API if you are comfortable protecting an API token. JSON import can merge matching IDs; it is not a full account restore. Telegram backup, email recovery and Google sign-in are unavailable. Uploads are limited to 2 MiB per request at the gateway.',
      privacy: 'Account details, habits, completion notes and note images are stored in SQLite; session state is also stored on the server. A browser session cookie can survive closing a tab. Native account deletion removes its habit list, settings and note images. Session files, operational logs and retained backups are separate, and copied exports remain wherever you saved them. Daily private backups stay on this VM with no automatic pruning; they are not off-host disaster recovery. No visitor analytics, advertising, external error-reporting provider or cross-service profiling is enabled.',
      next: 'Two native accounts, isolated habit records, JSON export/import, API-token revocation and native account deletion passed with fictional data. A restored application without network access opened the saved habit and completion. Account settings and note-image migration were not tested or promised by the JSON guide.',
    },
    es: {
      title: 'Llevá un registro de hábitos que podás conservar',
      intro: 'Empezá con una rutina que querás recordar, como leer una página. Beaver registra lo que vos anotás; no deduce lo que hacés. Las cuentas requieren habilitación separada por parte del operador.',
      prerequisites: 'Usá tu cuenta nativa habilitada con correo y contraseña. Aquí no hay registro público ni acceso con SSO de Utilibre. Conservá bien la contraseña: la recuperación por correo está desactivada. La interfaz usa etiquetas en inglés y el servidor puede leer tus registros; no hay cifrado de extremo a extremo.',
      steps: [
        'Ingresá Email y Password y elegí Continue. Abrí Add, escribí el nombre del hábito en New item y presioná Enter. Registrá una finalización para un día y añadí una nota breve si te sirve.',
        'Abrí el menú y elegí Export, luego Export JSON. El JSON descargado incluye tu correo, la fecha de exportación, los hábitos activos y sus registros y notas guardados. Omite hábitos archivados o marcados como borrados, ajustes de cuenta, credenciales y archivos de imágenes de notas guardados por separado. Guardá aparte las imágenes que necesités y protegé la exportación como datos personales.',
        'Para reabrir la copia, usá una instalación compatible de Beaver y elegí Import. Seleccioná el JSON, presioná el botón de nube con flecha de subida y confirmá Yes. Los hábitos nuevos reciben el sufijo (imported); los identificadores coincidentes pueden combinar registros. Probá primero con una cuenta vacía, sin asumir que la importación reemplaza todo. Se importó una exportación ficticia en una segunda cuenta y conservó su registro de finalización.',
        'Para integraciones, API Token en /gui/tokens ofrece Generate API Token, Reset Token y Delete. Un token no caduca automáticamente; mantenelo privado y borralo cuando una integración ya no necesite acceso. El GET nativo /api/v1/habits/export devuelve el JSON completo de la lista de hábitos, incluidas las entradas archivadas; no es un respaldo completo de la cuenta ni de las imágenes. No pegués tokens en consultas públicas de soporte.',
        'El control de papelera primero archiva un hábito activo. Usarlo de nuevo sobre un hábito archivado lo marca como borrado; no elimina su registro guardado. Para borrar la cuenta, revocá primero los tokens de API y guardá lo que necesités. Abrí Export → Delete y confirmá Yes. El flujo nativo descarga su JSON de hábitos activos antes de borrar la cuenta, pero esa descarga tiene las mismas omisiones que Export JSON.',
      ],
      success: 'Tu JSON descargado se abre como texto y una importación compatible en Beaver recrea los hábitos y registros elegidos. Revisá una finalización y una nota en la copia importada antes de depender de ella.',
      troubleshooting: 'La exportación de la interfaz excluye hábitos archivados. Reactivá primero los que necesités o usá la API nativa de la lista completa si sabés proteger un token. La importación JSON puede combinar identificadores coincidentes; no restaura una cuenta completa. No hay respaldo en Telegram, recuperación por correo ni acceso con Google. El intermediario limita las subidas a 2 MiB por solicitud.',
      privacy: 'Los datos de cuenta, hábitos, notas e imágenes se guardan en SQLite; también se conserva estado de sesión en el servidor. Una cookie de sesión del navegador puede sobrevivir al cierre de una pestaña. El borrado nativo de la cuenta elimina su lista de hábitos, ajustes e imágenes de notas. Los archivos de sesión, registros operativos y respaldos conservados son aparte, y tus exportaciones permanecen donde las guardaste. Los respaldos privados diarios se quedan en esta VM sin purga automática; no permiten recuperarse de la pérdida de la VM por sí solos. No se habilitan estadísticas de visitantes, anuncios, proveedores externos de informes de errores ni perfiles entre servicios.',
      next: 'Se verificaron dos cuentas nativas, registros separados, exportación/importación JSON, revocación de tokens y borrado nativo con datos ficticios. Una aplicación restaurada sin acceso a la red abrió el hábito y su finalización guardados. La guía JSON no promete ni presenta como probada la migración de ajustes de cuenta o imágenes de notas.',
    },
  },
}];
