import type { PracticalGuide } from './practical-guide-data.ts';
export const chhotoGuides: PracticalGuide[] = [{
  id: 'chhoto', paths: { en: 'guides/shorten-link', es: 'guias/acortar-enlace' }, tools: [{id:'chhoto',label:{en:'Shorten a link',es:'Acortar un enlace'}}],samples:[],reviewedOn:'2026-10-09',
  copy: {
    en: {
      title:'Create a short link with an expiry',
      intro:'Chhoto URL creates a temporary redirect. Keep the original URL so you can share it again after the short link expires.',
      prerequisites:'Use a public, non-sensitive destination and a browser with JavaScript. The native controls are in English. A short link reveals its destination to anyone holding it; this is not a way to hide a password or decryption key.',
      steps:['Open Chhoto URL and paste the destination into Long URL. For practice, use https://utilibre.org/en/. The server stores the full URL, including any query string or fragment.', 'Leave Short URL empty for a generated name, or enter an available name using the indicated characters. A recognizable name is easier to guess.', 'Open More options and choose Expiry. Anonymous links cannot last longer than 30 days, even if a longer choice is displayed. Optional Notes are stored on the server too.', 'Choose Shorten! The native button copies the resulting URL to your clipboard. Paste it into a private note beside the original and verify its destination before sharing.', 'To keep an independent copy, save those two URLs yourself. Anonymous visitors have no account export, saved link library or native deletion token. A copied link does not migrate the redirect to another server.', 'For removal before expiry, use Utilibre’s private contact route and identify the short URL. Do not send passwords or decryption keys. Expiry and native administrative deletion do not recall other people’s copies or earlier backups.'],
      success:"The native button and clipboard were tested with fictional data. The redirect matched its destination, the 30-day ceiling applied, unauthorized listing/deletion was refused, and a backup reopened in an isolated application. Both test links were deleted and returned 404.",
      troubleshooting:'If a name is taken, choose another or leave it empty. Creation is limited to two requests per minute with a burst of four per source IP; shared networks share that ceiling. The ordinary browser flow works; Cloudflare can reject non-browser API requests. Expired links stop resolving.',
      privacy:'Full URLs and notes are readable on the server. The app does not fetch destinations or collect click statistics. Following a link contacts its destination from your browser. Native sessionStorage retains configuration/login UI state. Daily same-VM backups have no automatic expiry, and edge/provider retention is independently unverified.',
      next:'Use the link cleaner first if you want to remove known tracking parameters; review the result before shortening it.',
    },
    es: {
      title:'Creá un enlace corto con vencimiento',
      intro:'Chhoto URL crea una redirección temporal. Guardá la URL original para volver a compartirla cuando venza el enlace corto.',
      prerequisites:'Usá un destino público sin datos sensibles y un navegador con JavaScript. Los controles nativos están en inglés. Cualquiera con el enlace corto puede conocer su destino; no lo usés para ocultar contraseñas ni claves de descifrado.',
      steps:['Abrí Chhoto URL y pegá el destino en Long URL. Para practicar, usá https://utilibre.org/es/. El servidor guarda la URL completa, incluidos parámetros y fragmentos.', 'Dejá Short URL vacío para generar un nombre o ingresá uno disponible con los caracteres indicados. Un nombre reconocible es más fácil de adivinar.', 'Abrí More options y elegí Expiry. Los enlaces anónimos no pueden durar más de 30 días, aunque aparezca una opción mayor. Las Notes opcionales también se guardan en el servidor.', 'Pulsá Shorten! El botón copia el enlace al portapapeles. Pegalo en una nota privada junto al original y verificá el destino antes de compartirlo.', 'Para conservar una copia independiente, guardá ambas URL. Los visitantes anónimos no tienen exportación de cuenta, biblioteca de enlaces ni token nativo de borrado. Copiar un enlace no migra la redirección a otro servidor.', 'Para borrarlo antes del vencimiento, usá el canal privado de contacto de Utilibre e identificá el enlace corto. No enviés contraseñas ni claves de descifrado. El vencimiento y borrado administrativo no quitan copias ajenas ni respaldos anteriores.'],
      success:"Se probaron el botón y el portapapeles con datos ficticios. La redirección coincidió con el destino, se aplicó el máximo de 30 días, se rechazaron consultas y borrados sin autorización y se abrió un respaldo en una aplicación aislada. Ambos enlaces de prueba se borraron y devolvieron 404.",
      troubleshooting:'Si el nombre está ocupado, elegí otro o dejalo vacío. La creación permite dos solicitudes por minuto con una ráfaga de cuatro por IP; las redes compartidas comparten el límite. El flujo normal del navegador funciona; Cloudflare puede rechazar solicitudes de API de otros clientes. Los enlaces vencidos dejan de redirigir.',
      privacy:'El servidor puede leer las URL completas y notas. La aplicación no visita los destinos ni recopila estadísticas de clics. Seguir un enlace contacta al destino desde tu navegador. sessionStorage conserva configuración y estado de la interfaz de sesión. Los respaldos diarios en esta máquina virtual no vencen automáticamente; la conservación del borde y proveedores no está verificada.',
      next:'Usá primero el limpiador si querés quitar parámetros de rastreo conocidos; revisá el resultado antes de acortarlo.',
    },
  },
}];
