import type { PracticalGuide } from './practical-guide-data.ts';

// Native capabilities of installed applications; no duplicate service or custom converter.
export const everydayGuides: PracticalGuide[] = [
  {
    id: 'passwords', paths: { en: 'guides/passwords-passphrases', es: 'guias/contrasenas-frases' },
    tools: [
      { id: 'ittools', path: '/token-generator', label: { en: 'Generate a password', es: 'Generar una contraseña' } },
      { id: 'ittools', path: '/bip39-generator', label: { en: 'Generate a word phrase', es: 'Generar una frase de palabras' } },
    ], samples: [], reviewedOn: '2026-10-08',
    copy: {
      en: {
        title: 'Create a password or a word phrase',
        intro: 'Use the installed IT Tools generators locally, then save a unique result in your password manager. No account is needed.',
        prerequisites: 'Use an up-to-date browser over HTTPS. Reload any generator page opened before 8 October 2026: the token generator was corrected to use WebCrypto. Practice without replacing a real account password until you have saved the result safely.',
        steps: [
          'Open Generate a password. Choose the allowed uppercase, lowercase, number and symbol categories and set a length your destination accepts. Prefer at least 20 characters when allowed. The default is 64. Refresh generates another result; do not reuse the example text from a guide.',
          'Check the destination’s rules. Category switches select allowed characters; they do not guarantee that every category occurs in each result. Refresh if a required category is missing. Do not shorten a result merely to make it easy to remember.',
          'For a word phrase, open Generate a word phrase. The BIP39 generator creates a 12-word mnemonic from fresh random entropy. Use the circular refresh button next to Entropy (seed) for a new phrase. Language changes the word list, not the interface. Keep all 12 words and their order; leave the generated entropy unchanged.',
          'Copy the chosen password or phrase into a trusted password manager and use it for one account only. Check that the account accepts it before closing the change-password form. Do not paste an existing wallet recovery phrase, password or key into the mnemonic fields to test it.',
          'Clear a shared clipboard when finished and check whether your device synchronizes clipboard history. Use the browser’s site-data controls to remove retained application preferences. Closing the tab does not delete clipboard history or files you saved.',
        ],
        success: 'The corrected token generator and the separate native BIP39 generator were checked for fresh output and actual WebCrypto calls. The phrase had 12 words. Test outputs were discarded; this does not validate every password manager or destination’s rules.',
        troubleshooting: 'If secure random generation is unavailable, use a current browser or your password manager. Do not switch to an insecure HTTP copy. The word generator is an advanced mnemonic tool, not a wallet or a recovery service. For a restrictive destination, use the password generator instead.',
        privacy: 'These generators create results in your browser. The application still has to be downloaded; hosting providers receive connection metadata. Clipboard managers, browser extensions and a compromised device can expose copied secrets. Utilibre does not keep a recovery copy. Never put a password in a share link or public support report.',
        next: 'Use a different password for every account and enable the account’s additional authentication options where available. If you used the older token generator, generate a replacement and change that password at its destination.',
      },
      es: {
        title: 'Creá una contraseña o una frase de palabras',
        intro: 'Usá los generadores de IT Tools en tu dispositivo y guardá un resultado único en tu gestor de contraseñas. No necesitás cuenta.',
        prerequisites: 'Usá un navegador actualizado mediante HTTPS. Recargá cualquier generador abierto antes del 8 de octubre de 2026: corregimos el generador de tokens para usar WebCrypto. Practicá sin reemplazar una contraseña real hasta guardar el resultado de forma segura.',
        steps: [
          'Abrí Generar una contraseña. Elegí las categorías permitidas de mayúsculas, minúsculas, números y símbolos y una longitud aceptada por el destino. Preferí al menos 20 caracteres cuando se admitan. El valor inicial es 64. Refresh genera otro resultado; no reutilicés el texto de ejemplo de una guía.',
          'Revisá las reglas del destino. Los interruptores eligen caracteres permitidos; no garantizan que cada categoría aparezca en cada resultado. Generá otro si falta una categoría obligatoria. No acortés el resultado solo para recordarlo más fácilmente.',
          'Para una frase de palabras, abrí Generar una frase de palabras. El generador BIP39 crea 12 palabras a partir de entropía aleatoria nueva. Usá el botón circular junto a Entropy (seed) para otra frase. Language cambia la lista de palabras, no la interfaz. Conservá las 12 palabras y su orden; no modifiqués la entropía generada.',
          'Copiá la contraseña o frase a un gestor de contraseñas confiable y usala para una sola cuenta. Comprobá que la cuenta la acepte antes de cerrar el formulario de cambio. No pegués una frase de recuperación de una billetera, una contraseña o una clave existente para probarla.',
          'Borrá el portapapeles compartido al terminar y revisá si tu dispositivo sincroniza su historial. Usá los controles de datos del sitio del navegador para eliminar preferencias guardadas. Cerrar la pestaña no borra el historial del portapapeles ni los archivos que guardaste.',
        ],
        success: 'Se verificaron la generación de resultados nuevos y las llamadas reales a WebCrypto del generador de tokens corregido y del generador BIP39 nativo. La frase tenía 12 palabras. Los resultados de prueba se descartaron; esto no valida todos los gestores ni las reglas de cada destino.',
        troubleshooting: 'Si no funciona la generación aleatoria segura, usá un navegador actual o tu gestor de contraseñas. No recurrás a una copia HTTP insegura. El generador de palabras es una herramienta avanzada de mnemónicos, no una billetera ni un servicio de recuperación. Para un destino con restricciones, usá el generador de contraseñas.',
        privacy: 'Estos generadores crean los resultados en tu navegador. La aplicación se descarga y los proveedores de alojamiento reciben metadatos de conexión. Los gestores de portapapeles, las extensiones y un dispositivo comprometido pueden revelar secretos copiados. Utilibre no conserva una copia de recuperación. Nunca pongás una contraseña en un enlace compartido ni en un informe público.',
        next: 'Usá una contraseña distinta por cuenta y activá sus opciones de autenticación adicional cuando estén disponibles. Si usaste el generador de tokens anterior, generá un reemplazo y cambiá esa contraseña en su destino.',
      },
    },
  },
  {
    id: 'markdown-export', paths: { en: 'guides/markdown-html-pdf', es: 'guias/markdown-html-pdf' },
    tools: [
      { id: 'ittools', path: '/markdown-to-html', label: { en: 'Convert Markdown to HTML', es: 'Convertir Markdown a HTML' } },
      { id: 'bentopdf', path: '/markdown-to-pdf.html', label: { en: 'Print Markdown to PDF', es: 'Imprimir Markdown como PDF' } },
    ], samples: [{ file: 'document-{lang}.md', localized: true, label: { en: 'Fictional reading plan (Markdown)', es: 'Plan de lectura ficticio (Markdown)' } }], reviewedOn: '2026-10-08',
    copy: {
      en: {
        title: 'Save Markdown as HTML or PDF', intro: "Turn a short Markdown document into HTML or PDF, check the result and keep the editable original.",
        prerequisites: 'Start with the fictional Markdown file. For PDF, use a browser and operating system with a Save as PDF print destination. These are simple-document workflows; complex layouts may differ.',
        steps: [
          'Download the fictional .md file and keep it as the editable original. Read it in a text editor: # starts a heading, and blank lines separate paragraphs. Remove remote image references if you do not want the renderer or a recipient to request those images.',
          'For HTML, open Convert Markdown to HTML and paste the Markdown into Your Markdown to convert. Inspect Output HTML. Copy that output into a local text editor, save it with an .html extension using UTF-8, and reopen it in your browser. Keep the .md file for later editing.',
          'For PDF, open Print Markdown to PDF. Choose Upload and select the .md file, or paste into the Markdown pane. Check the Preview, including names, accents and lists. Changing the preview does not change your original .md file.',
          'Choose Export PDF. This opens the browser’s print workflow; choose Save as PDF, review page size, margins and page breaks, then save. It does not automatically download a server-generated PDF. Reopen the PDF and search for a sentence from the original.',
          'Compare the saved copy against the original before sharing it. Keep personal content out of filenames and remove unnecessary browser print headers or footers. Delete unwanted downloads yourself; closing the application does not remove them.',
        ],
        success: 'Reopen the saved HTML or PDF. It should contain the heading, paragraphs and fictional coordinator from the original, without editor controls. Confirm the page count before sharing.',
        troubleshooting: 'Export PDF opens a print dialog, not an immediate download. If nothing appears, check for a print window behind the browser, allow the page to finish loading and try once more. If no PDF destination is available, use another browser or your operating system’s print-to-file feature. Keep the Markdown original until the PDF is saved. Check the print preview for extra blank pages and exclude them with the page-range control when needed. Long code blocks, tables, links and fonts can change pagination. An HTML fragment is not a complete website or an encrypted document.',
        privacy: 'The tested text conversion and printing run in your browser. Linked remote images can cause network requests; the text-only sample contains none. App delivery still creates connection metadata. HTML and PDF copies are ordinary unencrypted files and remain on your device until you delete them.',
        next: 'Share a checked file with PairDrop or share only a small text/code extract through PrivateBin. Keep the editable Markdown independently.',
      },
      es: {
        title: 'Guardá Markdown como HTML o PDF', intro: "Convertí un documento Markdown breve en HTML o PDF, revisá el resultado y conservá el original editable.",
        prerequisites: 'Empezá con el archivo Markdown ficticio. Para PDF, necesitás un navegador y un sistema con la opción Guardar como PDF al imprimir. Este recorrido cubre documentos sencillos; los diseños complejos pueden variar.',
        steps: [
          'Descargá el archivo .md ficticio y conservalo como original editable. Leelo en un editor de texto: # inicia un título y las líneas vacías separan párrafos. Quitá referencias a imágenes remotas si no querés que el programa o un destinatario las solicite.',
          'Para HTML, abrí Convertir Markdown a HTML y pegá el Markdown en Your Markdown to convert. Revisá Output HTML. Copiá ese resultado a un editor de texto local, guardalo con extensión .html y codificación UTF-8 y abrilo en tu navegador. Conservá el .md para editar después.',
          'Para PDF, abrí Imprimir Markdown como PDF. Elegí Upload y seleccioná el .md, o pegalo en el panel Markdown. Revisá la vista previa, incluidos nombres, acentos y listas. Cambiar la vista previa no modifica el .md original.',
          'Elegí Exportar PDF (Export PDF si la interfaz está en inglés). Se abre el recorrido de impresión del navegador: elegí Guardar como PDF, revisá el tamaño, los márgenes y los saltos de página y guardá. No descarga automáticamente un PDF generado en el servidor. Volvé a abrir el PDF y buscá una frase del original.',
          'Compará la copia guardada con el original antes de compartirla. Evitá datos personales en los nombres de archivo y quitá encabezados o pies de impresión innecesarios. Eliminá vos las descargas que no necesitás; cerrar la aplicación no las borra.',
        ],
        success: 'Volvé a abrir el HTML o PDF guardado. Debe contener el título, los párrafos y la coordinadora ficticia del original, sin controles del editor. Revisá la cantidad de páginas antes de compartir.',
        troubleshooting: 'Exportar PDF abre un diálogo de impresión, no una descarga inmediata. Si no aparece nada, buscá una ventana de impresión detrás del navegador, esperá que termine de cargar la página y probá una vez más. Si no hay un destino PDF, probá otro navegador o la impresión a archivo de tu sistema. Conservá el Markdown original hasta guardar el PDF. Revisá si la vista de impresión agrega páginas en blanco y excluilas con el selector de páginas cuando sea necesario. El código largo, las tablas, los enlaces y las fuentes pueden alterar la paginación. Un fragmento HTML no es un sitio completo ni un documento cifrado.',
        privacy: 'La conversión de texto y la impresión probadas ocurren en tu navegador. Las imágenes remotas enlazadas pueden provocar solicitudes de red; el ejemplo de texto no contiene ninguna. Descargar la aplicación genera metadatos de conexión. Las copias HTML y PDF no están cifradas y quedan en tu dispositivo hasta que las eliminés.',
        next: 'Compartí un archivo revisado con PairDrop o un fragmento breve de texto o código con PrivateBin. Conservá el Markdown editable por separado.',
      },
    },
  },
  {
    id: 'share-code', paths: { en: 'guides/share-code', es: 'guias/compartir-codigo' },
    tools: [{ id: 'privatebin', label: { en: 'Share code with PrivateBin', es: 'Compartir código con PrivateBin' } }], samples: [], reviewedOn: '2026-10-08',
    copy: {
      en: {
        title: 'Share a small code snippet', intro: "Share readable code in PrivateBin’s Source Code format, with browser encryption and an expiry you choose.",
        prerequisites: 'Prepare a small fictional example such as const answer = 42;. Remove passwords, API keys, tokens, private paths and personal data before sharing. This is a text paste; file uploads and discussion are disabled.',
        steps: [
          'Open PrivateBin and choose Source Code in the format selector. Paste only the snippet the recipient needs. Check that copying it preserves indentation and characters.',
          'Choose an expiry: this instance offers 5 minutes, 10 minutes, 1 hour, 1 day or 1 week. Add a password if needed and send that password through a separate channel. Leave burn-after-reading off if you want to check the shared link yourself without consuming it.',
          'Choose Create. Copy the complete sharing link, including the part after #, for the intended recipient. Keep the deletion link separate and private. A complete sharing link can grant access to the snippet.',
          'Open the sharing link in another browser context for a fictional test. Confirm the code renders and copies correctly. For a burn-after-reading paste, opening it yourself can consume its single read; do not use that mode for a repeated preview.',
          'Use the deletion link to remove the paste when it is no longer needed, or let its chosen expiry apply. Deletion does not recall copies a recipient saved or rewrite existing server backups.',
        ],
        success: 'A fictional source-code paste was created, decrypted in a separate browser and deleted through its native deletion mechanism. Its expiry was five minutes. The test did not contain credentials or real code from a visitor.',
        troubleshooting: 'A link missing its # fragment lacks the normal decryption key. A password-protected paste also needs that password. Syntax highlighting is presentation, not code validation; do not run unfamiliar code simply because it displays cleanly.',
        privacy: 'PrivateBin encrypts the content in the browser and stores ciphertext on Utilibre. Normal decryption needs the link key and any password you set. Connection metadata and the encrypted record are distinct; see the tool’s data notes. You still trust the delivered application code and the recipient. For an abuse report, send an identifier or link without its decryption fragment where possible.',
        next: 'Keep your source in your own project or backup. A temporary paste is a sharing copy, not version control or a permanent archive.',
      },
      es: {
        title: 'Compartí un fragmento breve de código', intro: "Compartí código legible con el formato Código fuente de PrivateBin, cifrado en el navegador y el vencimiento que elijás.",
        prerequisites: 'Prepará un ejemplo ficticio breve, como const answer = 42;. Quitá contraseñas, claves de API, tokens, rutas privadas y datos personales antes de compartir. Es un texto: los adjuntos y los comentarios están desactivados.',
        steps: [
          'Abrí PrivateBin y elegí Código fuente en el selector de formato. Pegá solo el fragmento que necesita el destinatario. Revisá que al copiarlo se conserven la sangría y los caracteres.',
          'Elegí un vencimiento: esta instancia ofrece 5 minutos, 10 minutos, 1 hora, 1 día o 1 semana. Agregá una contraseña si hace falta y enviala por otro canal. Dejá desactivada la eliminación tras leer si querés revisar el enlace sin consumirlo.',
          'Elegí Crear. Copiá el enlace completo, incluida la parte después de #, para el destinatario. Guardá el enlace de eliminación por separado y en privado. El enlace completo puede dar acceso al fragmento.',
          'Para una prueba ficticia, abrí el enlace en otro contexto del navegador. Comprobá que el código se vea y se copie correctamente. Si activaste la eliminación tras leer, abrirlo vos puede consumir su única lectura; no usés ese modo para previsualizaciones repetidas.',
          'Usá el enlace de eliminación cuando ya no necesités el texto o dejá que venza. Eliminarlo no retira las copias guardadas por un destinatario ni modifica las copias de seguridad existentes del servidor.',
        ],
        success: 'Se creó un texto ficticio en formato de código, se descifró en otro navegador y se eliminó mediante su mecanismo nativo. Tenía un vencimiento de cinco minutos. La prueba no contenía credenciales ni código real de visitantes.',
        troubleshooting: 'Un enlace sin su fragmento # no incluye la clave normal de descifrado. Si protegiste el texto con contraseña, también se necesita esa contraseña. Resaltar la sintaxis solo cambia la presentación: no valida el código. No ejecutés código desconocido porque se vea ordenado.',
        privacy: 'PrivateBin cifra el contenido en tu navegador y guarda texto cifrado en Utilibre. Para descifrarlo normalmente se necesitan la clave del enlace y la contraseña que hayas elegido. Los metadatos de conexión y el registro cifrado son distintos: consultá las notas de la herramienta. Seguís confiando en el código recibido y en el destinatario. Para reportar abuso, enviá un identificador o un enlace sin su fragmento de descifrado cuando sea posible.',
        next: 'Conservá el código en tu proyecto o respaldo. Un texto temporal sirve para compartir, no como control de versiones ni archivo permanente.',
      },
    },
  },
  {
    id: 'inspect-photo', paths: { en: 'guides/inspect-photo-metadata', es: 'guias/inspeccionar-metadatos-foto' },
    tools: [{ id: 'image-scrubber', label: { en: 'Inspect a photo with Image Scrubber', es: 'Inspeccionar una foto con Image Scrubber' } }],
    samples: [{ file: 'fictional-image.jpg', label: { en: 'Fictional JPEG with an EXIF tag', es: 'JPEG ficticio con una etiqueta EXIF' } }], reviewedOn: '2026-10-08',
    copy: {
      en: {
        title: 'Inspect a photo’s EXIF metadata', intro: "See what a photo’s embedded EXIF fields say before sharing it. Image Scrubber shows them before editing, without uploading the image.",
        prerequisites: 'Keep the original and start with the fictional JPEG below. This is an EXIF viewer for supported images, not a complete forensic report for every metadata format.',
        steps: [
          'Open Image Scrubber and choose Open Image. Select the fictional JPEG. The first screen displays EXIF information before you continue to the editor.',
          'Find the Artist field containing UTILIBRE FICTIONAL EXAMPLE. On your own photo, check for fields such as camera details, capture times or coordinates if present. This test file does not represent a real person or location.',
          'If inspection is all you need, stop here and close the tool. It has not rewritten the original file. Do not send a screenshot of private metadata to a public support channel.',
          'If you want a shareable copy, continue to the editor and follow the existing Cover private information in a photo guide. Save a new PNG and inspect that downloaded file separately. Removing EXIF does not cover a face, address or other visible detail.',
        ],
        success: 'The installed viewer displayed the known fictional Artist tag before editing. No original file was changed. The separate photo-preparation guide checks the flattened PNG export.',
        troubleshooting: 'No EXIF found does not mean a file contains no metadata or private information. Unsupported formats, other metadata systems and visible content need separate review. CyberChef’s current Extract EXIF parser is blocked by this instance’s strict browser security policy; use this verified viewer instead.',
        privacy: 'The selected image is read in your browser by this build. App delivery still involves connection metadata. Do not mistake clearing a preview for deleting the original or a downloaded copy; those files remain on your device.',
        next: 'Use the file-type and hash guide to compare exact files, or prepare a separate sanitized copy before sharing.',
      },
      es: {
        title: 'Inspeccioná los metadatos EXIF de una foto', intro: "Revisá qué dicen los campos EXIF de una foto antes de compartirla. Image Scrubber los muestra antes de editar, sin subir la imagen.",
        prerequisites: 'Conservá el original y empezá con el JPEG ficticio. Es un visor EXIF para imágenes compatibles, no un informe forense completo de todos los formatos de metadatos.',
        steps: [
          'Abrí Image Scrubber y elegí Open Image (Abrir imagen). Seleccioná el JPEG ficticio. La primera pantalla muestra la información EXIF antes de continuar al editor.',
          'Buscá el campo Artist que contiene UTILIBRE FICTIONAL EXAMPLE. En una foto propia, revisá campos como cámara, fecha de captura o coordenadas, si aparecen. El archivo de prueba no representa a una persona ni ubicación real.',
          'Si solo necesitás inspeccionar, detenete acá y cerrá la herramienta. No reescribió el archivo original. No enviés capturas de metadatos privados a un canal público de ayuda.',
          'Si necesitás una copia para compartir, continuá al editor y seguí la guía existente para tapar información privada en una foto. Guardá un PNG nuevo e inspeccioná esa descarga por separado. Quitar EXIF no tapa una cara, dirección ni otro detalle visible.',
        ],
        success: 'El visor instalado mostró la etiqueta Artist ficticia antes de editar. No se modificó el archivo original. La guía de preparación de fotos verifica la exportación como PNG aplanado.',
        troubleshooting: 'Que no aparezca EXIF no significa que el archivo carezca de metadatos o información privada. Los formatos no admitidos, otros sistemas de metadatos y el contenido visible requieren revisión aparte. La política de seguridad estricta de esta instancia bloquea el analizador Extract EXIF de CyberChef; usá este visor verificado.',
        privacy: 'Esta versión lee la imagen seleccionada en tu navegador. Descargar la aplicación genera metadatos de conexión. Borrar una vista previa no elimina el original ni una copia descargada: esos archivos permanecen en tu dispositivo.',
        next: 'Usá la guía de tipo de archivo y hash para comparar archivos exactos o prepará una copia saneada por separado antes de compartir.',
      },
    },
  },
  {
    id: 'file-verify', paths: { en: 'guides/file-type-sha256', es: 'guias/tipo-archivo-sha256' },
    tools: [
      { id: 'cyberchef', path: '/#recipe=Detect_File_Type(true,true,true,true,true,true,true)', label: { en: 'Identify a file type', es: 'Identificar el tipo de archivo' } },
      { id: 'cyberchef', path: "/#recipe=SHA2('256',64,160)", label: { en: 'Calculate file SHA-256', es: 'Calcular el SHA-256 de un archivo' } },
    ], samples: [{ file: 'fictional-image.jpg', label: { en: 'Fictional JPEG for both checks', es: 'JPEG ficticio para ambas comprobaciones' } }], reviewedOn: '2026-10-08',
    copy: {
      en: {
        title: 'Identify a file and compare its SHA-256', intro: "Identify a file’s likely format and compare its SHA-256 with CyberChef. The ready-made recipe links contain only operation settings, never your file or its name.",
        prerequisites: 'Start with the fictional JPEG. For a real download, obtain the expected SHA-256 from a trusted publisher through an independent authenticated source. A hash supplied beside an untrusted file is not proof of authenticity.',
        steps: [
          'Open Identify a file type. The Detect File Type recipe is already selected. Use the folder icon in the Input panel to choose the file itself. Do not paste only its filename or path. If needed, click BAKE!.',
          'Read the Output. The fictional sample is identified as JPEG with MIME type image/jpeg. A signature is a clue about format; it does not prove the whole file is valid, harmless or what its extension claims.',
          'Open Calculate file SHA-256 and choose the same original file in Input. Keep SHA2 set to 256 and the standard 64 rounds. Click BAKE! if Auto Bake is off. The result is a 64-character hexadecimal digest of the file’s exact bytes.',
          'Compare every character with the publisher’s expected SHA-256. For practice, calculate the sample again and confirm the results match. Re-saving, resizing, changing metadata or even changing text line endings produces different bytes and a different digest.',
          'If the result differs, stop using that download and check its source and version. Do not change the expected hash to make the check pass. Clear Input and Output after use, and avoid saving a share URL that includes input data.',
        ],
        success: 'The native signature recipe identified the fictional JPEG. CyberChef’s file SHA-256 matched an independent Node SHA-256 calculation over the exact same bytes. No malware detection or publisher-signature verification is claimed.',
        troubleshooting: 'An unknown signature can be an unsupported format; it does not automatically mean encryption or corruption. Large files may need substantial browser memory. Hashing pasted text, base64 or a path hashes that text rather than the original file bytes. Use the file picker.',
        privacy: 'The recipes run in your browser, and network-request operations are disabled in this CyberChef build. Application delivery still generates connection metadata. Recipe URLs can optionally include input, so do not use that option for confidential data. A hash is not encryption and may identify a known public file.',
        next: 'Inspect a photo’s metadata separately before sharing. Keep important originals and the trusted publisher’s digest independently.',
      },
      es: {
        title: 'Identificá un archivo y compará su SHA-256', intro: "Identificá el formato probable de un archivo y compará su SHA-256 con CyberChef. Los enlaces de las recetas preparadas contienen solo ajustes de operaciones, nunca tu archivo ni su nombre.",
        prerequisites: 'Empezá con el JPEG ficticio. Para una descarga real, obtené el SHA-256 esperado de una fuente auténtica e independiente del publicador. Un hash junto a un archivo no confiable no prueba su autenticidad.',
        steps: [
          'Abrí Identificar el tipo de archivo. La receta Detect File Type ya está seleccionada. Usá el icono de carpeta del panel Input para elegir el archivo. No pegués solo su nombre o ruta. Si hace falta, pulsá BAKE!.',
          'Leé Output. El ejemplo se identifica como JPEG con tipo MIME image/jpeg. La firma da una pista del formato; no prueba que todo el archivo sea válido, inofensivo ni lo que indica su extensión.',
          'Abrí Calcular el SHA-256 de un archivo y elegí el mismo original en Input. Conservá SHA2 en 256 y las 64 rondas estándar. Pulsá BAKE! si Auto Bake está desactivado. El resultado tiene 64 caracteres hexadecimales y corresponde a los bytes exactos del archivo.',
          'Compará cada carácter con el SHA-256 publicado. Para practicar, calculá otra vez el hash del ejemplo y comprobá que coincidan. Volver a guardar, redimensionar, cambiar metadatos o incluso los saltos de línea de un texto produce otros bytes y otro hash.',
          'Si no coincide, dejá de usar esa descarga y revisá su origen y versión. No modifiqués el hash esperado para que coincida. Borrá Input y Output al terminar y evitá guardar un enlace compartido que incluya los datos de entrada.',
        ],
        success: 'La receta nativa de firmas identificó el JPEG ficticio. El SHA-256 de CyberChef coincidió con un cálculo independiente de Node sobre los mismos bytes. No se afirma detección de malware ni verificación de firmas del publicador.',
        troubleshooting: 'Una firma desconocida puede indicar un formato no admitido; no implica necesariamente cifrado ni corrupción. Los archivos grandes pueden consumir bastante memoria del navegador. Calcular el hash de texto pegado, base64 o una ruta procesa ese texto, no los bytes del archivo original. Usá el selector de archivos.',
        privacy: 'Las recetas funcionan en tu navegador y esta versión de CyberChef tiene desactivadas las operaciones de solicitudes de red. Descargar la aplicación genera metadatos de conexión. Sus enlaces pueden incluir opcionalmente datos de entrada: no activés esa opción con información confidencial. Un hash no es cifrado y puede identificar un archivo público conocido.',
        next: 'Inspeccioná por separado los metadatos de una foto antes de compartirla. Conservá los originales importantes y el hash de la fuente confiable por separado.',
      },
    },
  },
  {
    id: 'outlook-link', paths: { en: 'guides/outlook-link-destination', es: 'guias/destino-enlace-outlook' },
    tools: [{ id: 'ittools', path: '/safelink-decoder', label: { en: 'Decode an Outlook wrapper', es: 'Decodificar un enlace de Outlook' } }],
    samples: [], reviewedOn: '2026-10-08',
    copy: {
      en: {
        title: 'Inspect the destination inside an Outlook link',
        intro: "See the destination hidden inside an Outlook Safe Links wrapper before deciding what to do with it. IT Tools decodes the text locally; no account is needed.",
        prerequisites: 'Copy a complete Outlook Safe Links wrapper as text, without opening it. Use fictional data for practice. Decoding reveals text; it does not establish that a link, sender or destination is trustworthy.',
        steps: [
          'Open Decode an Outlook wrapper. The native tool is called Outlook Safelink decoder. Paste the wrapper into Your input Outlook SafeLink Url, not the browser address bar.',
          'Read Output decoded URL. Check the scheme, full hostname, path, query and the part after # before copying. The decoder keeps the embedded destination’s query and fragment; they may contain tracking fields, identifiers or access keys.',
          'For the fictional check, the embedded destination was https://example.invalid/?item=42#part. The output retained both item=42 and #part. The .invalid address is only an example; do not open it or replace it with a real private link for a public support report.',
          'Use the copy control only when you intend to retain or share that destination. Decoding does not open it. Opening the copied destination later sends a separate request to that site and bypasses the original wrapper.',
          'Clear the input when finished and remove any unwanted clipboard copies. Closing the tab does not clear clipboard history or files you saved.',
        ],
        success: 'A fictional wrapper using a .invalid hostname produced the exact embedded .invalid destination, including query and fragment. The browser check observed no request to the wrapper or destination and no pasted input in the application URL. The permissive wrapper-name check is not proof of a genuine Microsoft URL.',
        troubleshooting: 'An ordinary shortened URL may show Invalid SafeLinks URL provided or no destination. This is not a universal unshortener: it does not follow HTTP redirects, create short links, remove tracking parameters or check destination safety. Do not remove unfamiliar parameters to force a link to work.',
        privacy: 'This decoder processes the pasted text in browser memory and does not upload it or save it to browser storage. Downloading the application still generates connection metadata on Utilibre’s normal hosting path. Copying the output can expose it to clipboard history or synchronization. Keep links containing access keys out of public reports.',
        next: 'Share a destination only if you intend to grant any access carried by its query or fragment. Keep the original separately if you need it; this tool does not modify or revoke either link.',
      },
      es: {
        title: 'Revisá el destino incluido en un enlace de Outlook',
        intro: "Revisá el destino incluido en un enlace de Outlook Safe Links antes de decidir qué hacer con él. IT Tools decodifica el texto en tu dispositivo; no necesitás cuenta.",
        prerequisites: 'Copiá como texto un enlace completo de Outlook Safe Links, sin abrirlo. Practicá con datos ficticios. Decodificar muestra texto; no demuestra que el enlace, el remitente o el destino sean confiables.',
        steps: [
          'Abrí Decodificar un enlace de Outlook. La herramienta nativa se llama Outlook Safelink decoder. Pegá el enlace en Your input Outlook SafeLink Url, no en la barra de direcciones del navegador.',
          'Leé Output decoded URL. Revisá el protocolo, el nombre completo del servidor, la ruta, los parámetros y la parte después de # antes de copiar. La herramienta conserva los parámetros y el fragmento del destino; pueden contener rastreo, identificadores o claves de acceso.',
          'En la prueba ficticia, el destino incluido era https://example.invalid/?item=42#part. El resultado conservó tanto item=42 como #part. La dirección .invalid es solo un ejemplo: no la abrás ni la reemplacés por un enlace privado real para un informe público.',
          'Usá el control de copiar solo si querés conservar o compartir ese destino. Decodificar no lo abre. Si después abrís el destino copiado, enviás una solicitud aparte a ese sitio y evitás el enlace envolvente original.',
          'Borrá la entrada al terminar y eliminá las copias del portapapeles que no necesitás. Cerrar la pestaña no borra el historial del portapapeles ni los archivos que guardaste.',
        ],
        success: 'Un enlace envolvente ficticio con un servidor .invalid produjo el destino .invalid exacto, incluidos sus parámetros y fragmento. La prueba del navegador no observó solicitudes al enlace envolvente ni al destino, ni la entrada pegada en la URL de la aplicación. La comprobación permisiva del nombre no prueba que la URL sea de Microsoft.',
        troubleshooting: 'Un enlace corto común puede mostrar Invalid SafeLinks URL provided o ningún destino. No es un expansor universal: no sigue redirecciones HTTP, no crea enlaces cortos, no elimina parámetros de rastreo ni comprueba la seguridad del destino. No borrés parámetros desconocidos para intentar que funcione.',
        privacy: 'Este decodificador procesa el texto pegado en la memoria del navegador; no lo sube ni lo guarda en el almacenamiento del navegador. Descargar la aplicación genera metadatos de conexión en la infraestructura habitual de Utilibre. Copiar el resultado puede exponerlo al historial o la sincronización del portapapeles. No incluyás enlaces con claves de acceso en informes públicos.',
        next: 'Compartí un destino solo si querés conceder el acceso que puedan dar sus parámetros o fragmento. Conservá el original por separado si lo necesitás: esta herramienta no modifica ni revoca ninguno de los enlaces.',
      },
    },
  },
  {
    id: 'booklet', paths: { en: 'guides/pdf-booklet', es: 'guias/folleto-pdf' },
    tools: [{ id: 'bentopdf', path: '/pdf-booklet.html', label: { en: 'Make a basic PDF booklet', es: 'Crear un folleto PDF sencillo' } }],
    samples: [{ file: 'booklet-eight-pages.pdf', label: { en: 'Eight fictional numbered pages (PDF)', es: 'Ocho páginas ficticias numeradas (PDF)' } }], reviewedOn: '2026-10-08',
    copy: {
      en: {
        title: 'Arrange a PDF as a basic folded booklet',
        intro: "Arrange PDF pages for one folded booklet with BentoPDF. Check the downloaded PDF first: this guide verifies digital order, not a physical printer or folded result.",
        prerequisites: 'Download the fictional eight-page sample and keep your original separately. Use a current browser and enough device memory. This basic workflow uses No rotation and the 1×2 (Booklet) layout.',
        steps: [
          'Open Make a basic PDF booklet and select the fictional PDF in the file picker. Confirm that the summary shows 8 pages. Selecting it loads the file into the browser; this workflow does not upload its contents.',
          'Leave Source Rotation at No rotation. Choose Paper Size, such as Letter or A4. Keep Grid Mode at 1×2 (Booklet) and Orientation at Auto (best for layout). Auto produces landscape output here. The other grids place pages sequentially; they do not use this folded-booklet order.',
          'Select Generate Preview. The eight-page sample shows four output sides. The application calls them output sheets, but these are four PDF pages: front and back for two physical sheets if printed duplex.',
          'Select Create Booklet, or Crear Folleto on the Spanish page, and save under a new name. The download proposes the input filename; avoid overwriting your original. Reopen the downloaded PDF.',
          'Check left to right: side 1 has pages 8 and 1; side 2 has 2 and 7; side 3 has 6 and 3; side 4 has 4 and 5. Confirm four landscape PDF pages and legible content. This order was verified on Letter and A4.',
          'Before printing a long document, make a small physical test. Duplex flip, scale, margins, feed direction and stacking depend on the printer. Follow its instructions and check both sides before folding. No universal printer setting or physical folding result was tested here.',
        ],
        success: 'The eight-page sample downloaded as four correctly ordered sides from the deployed English and Spanish pages. The original remained unchanged. Network capture observed only application downloads from the PDF service, with no file upload or outside request during these tests.',
        troubleshooting: 'Keep No rotation: the clockwise option has separate preview logic but was not applied to the downloaded PDF in the test. Some Spanish controls remain in English. Multi-signature binding, sewing marks, custom binding margins and specialized zine layouts are not part of this tool. Large PDFs may need substantial device memory.',
        privacy: 'This booklet workflow processes the PDF in your browser. App delivery still creates connection metadata on Utilibre’s hosting path. Original and downloaded PDFs remain on your device until you delete them; closing the tab deletes neither. The output is an ordinary PDF, not an encrypted backup.',
        next: 'Keep the original and a checked booklet copy separately. Use the existing PDF tools for other edits; a dedicated bookbinding application is useful when you need advanced signatures or binding marks.',
      },
      es: {
        title: 'Ordená un PDF como folleto plegado sencillo',
        intro: "Ordená las páginas de un PDF para un folleto plegado con BentoPDF. Revisá primero el PDF descargado: esta guía verifica el orden digital, no una impresora ni el resultado físico del plegado.",
        prerequisites: 'Descargá el ejemplo ficticio de ocho páginas y conservá el original por separado. Usá un navegador actual y suficiente memoria en tu dispositivo. Este recorrido usa No rotation y el diseño 1×2 (Booklet).',
        steps: [
          'Abrí Crear un folleto PDF sencillo y elegí el PDF ficticio en el selector de archivos. Comprobá que el resumen indique 8 pages. Elegirlo lo carga en el navegador; este recorrido no sube su contenido.',
          'Dejá Source Rotation en No rotation. Elegí el Tamaño de Papel, por ejemplo Letter o A4. Mantené Grid Mode en 1×2 (Booklet) y Orientation en Auto (best for layout). Auto produce páginas horizontales acá. Las otras cuadrículas colocan páginas consecutivas, sin este orden para plegar el folleto.',
          'Pulsá Generate Preview. El ejemplo de ocho páginas muestra cuatro caras. La aplicación las llama output sheets, pero son cuatro páginas PDF: anverso y reverso de dos hojas físicas si imprimís a doble cara.',
          'Pulsá Crear Folleto, o Create Booklet en la página inglesa, y guardá la descarga con otro nombre. La descarga propone el nombre del archivo de entrada; evitá reemplazar el original. Volvé a abrir el PDF descargado.',
          'Revisá de izquierda a derecha: la cara 1 tiene las páginas 8 y 1; la cara 2, 2 y 7; la cara 3, 6 y 3; la cara 4, 4 y 5. Confirmá cuatro páginas PDF horizontales y contenido legible. Este orden se verificó con papel Letter y A4.',
          'Antes de imprimir un documento largo, hacé una prueba física pequeña. El volteo a doble cara, la escala, los márgenes, la alimentación y el apilado dependen de la impresora. Seguí sus instrucciones y revisá ambas caras antes de plegar. Acá no se probó un ajuste universal de impresión ni un resultado físico de plegado.',
        ],
        success: 'El ejemplo de ocho páginas se descargó como cuatro caras en el orden correcto desde las páginas inglesa y española instaladas. El original no cambió. La captura de red solo observó descargas de la aplicación desde el servicio PDF, sin subir el archivo ni contactar servicios externos durante estas pruebas.',
        troubleshooting: 'Conservá No rotation: la opción de rotación horaria tiene una lógica aparte para la vista previa, pero no se aplicó al PDF descargado en la prueba. Algunos controles siguen en inglés. Esta herramienta no incluye encuadernación en varios cuadernillos, marcas de costura, márgenes de encuadernación personalizados ni diseños especializados de fanzines. Los PDF grandes pueden necesitar bastante memoria.',
        privacy: 'Este recorrido procesa el PDF en tu navegador. Descargar la aplicación genera metadatos de conexión en la infraestructura de Utilibre. El original y las descargas quedan en tu dispositivo hasta que los eliminés; cerrar la pestaña no los borra. El resultado es un PDF común, no un respaldo cifrado.',
        next: 'Conservá por separado el original y una copia del folleto revisada. Usá las herramientas PDF existentes para otras ediciones; una aplicación de encuadernación sirve cuando necesitás cuadernillos avanzados o marcas de encuadernación.',
      },
    },
  },
];
