import type { PracticalGuide } from './practical-guide-data.ts';

// Native flows checked against the deployed releases on 2026-10-09.
export const householdAdditionGuides: PracticalGuide[] = [
  {
    id: 'shared-expenses', paths: { en: 'guides/shared-expenses', es: 'guias/gastos-compartidos' },
    tools: [{ id: 'spliit', label: { en: 'Open shared expenses', es: 'Abrir gastos compartidos' } }],
    samples: [], reviewedOn: '2026-10-09',
    copy: {
      en: {
        title: 'Split a shared expense and save a copy',
        intro: 'Create a Spliit group without an account, add participants and record who paid. The group link grants access to everyone who receives it.',
        prerequisites: 'Use fictional names and a small practice expense first. Agree who should have the group link: anyone holding it can read and change the group. Keep an independent copy of important records.',
        steps: [
          'Create a group and name its participants. For practice, use a fictional outing and three fictional people. Save the group link privately; the recent-groups list in your browser is not an independent backup.',
          'Add an expense with its title, amount, payer and participants. Check each share before saving. Receipt uploads and automatic exchange-rate requests are disabled; enter a custom exchange rate manually when needed.',
          'Share the group link only with the intended participants. A second browser can open the same group without signing in. There are no separate read-only and editing permissions on that link.',
          'Open Export and choose Export to JSON or Export to CSV. JSON preserves group/participant information, expense details and activity records. CSV is a tabular expense export. Browser recent-group lists and preferences are omitted; attachments are disabled.',
          'Open the downloaded CSV in a spreadsheet or the JSON in a suitable text viewer and check your expense. This release has no native CSV/JSON import: these are readable independent records, not a tested in-app migration file.',
          'To remove an expense, open it, choose edit, then Delete and Yes. Related names or titles may remain in activity history. Removing a group from your browser only removes that local shortcut. For whole-group server deletion, contact the operator privately with the group identifier; do not post its access link publicly.',
        ],
        success: 'A fictional three-person group and expense were created, opened in a separate browser context, exported as JSON/CSV and checked. An isolated database restore recovered that group and expense. Native expense deletion passed; the exact test group was then removed through guarded operator database administration.',
        troubleshooting: 'If totals differ, check the currency, payer and shares. Automatic currency rates and receipt AI are unavailable. An export does not become encrypted merely because the website uses HTTPS. Keep the group link and downloaded files out of public support requests.',
        privacy: 'Spliit stores group, participant, expense and activity data on the server. Anyone with the link can read and edit it and retain an export. Browser shortcuts persist until removed. Local operational backups have no automatic expiry and stay on this VM until operator removal; live deletion does not remove old backups. These backups are not off-site.',
        next: 'Export after important changes and compare the final balances together before settling outside the application.',
      },
      es: {
        title: 'Repartí un gasto compartido y guardá una copia',
        intro: 'Creá un grupo de Spliit sin cuenta, agregá participantes y registrá quién pagó. El enlace del grupo da acceso a toda persona que lo reciba.',
        prerequisites: 'Probá primero con nombres ficticios y un gasto pequeño. Acordá quién debe recibir el enlace: cualquiera que lo tenga puede leer y modificar el grupo. Conservá una copia independiente de los registros importantes.',
        steps: [
          'Creá un grupo y nombrá a sus participantes. Para practicar, usá una salida y tres personas ficticias. Guardá el enlace en privado; la lista de grupos recientes del navegador no es una copia independiente.',
          'Agregá un gasto con título, importe, persona que pagó y participantes. Revisá cada parte antes de guardar. La carga de recibos y las consultas automáticas de cambio están desactivadas; ingresá una tasa personalizada cuando la necesités.',
          'Compartí el enlace solo con las personas previstas. Otro navegador puede abrir el mismo grupo sin iniciar sesión. Ese enlace no separa los permisos de lectura y edición.',
          'Abrí Export y elegí Export to JSON o Export to CSV. JSON conserva datos del grupo y sus participantes, detalles de gastos y actividad. CSV es una tabla de gastos. Se omiten los grupos recientes y las preferencias del navegador; los adjuntos están desactivados.',
          'Abrí el CSV descargado en una hoja de cálculo o el JSON en un visor de texto y comprobá el gasto. Esta versión no importa CSV/JSON de forma nativa: son registros independientes legibles, no un archivo de migración probado dentro de la aplicación.',
          "Para borrar un gasto, abrilo, elegí editar, luego Delete y Yes. Los nombres o títulos relacionados pueden seguir en el historial. Quitar un grupo del navegador solo elimina el acceso directo local. Para borrar todo el grupo del servidor, contactá en privado a la persona operadora con su identificador; no publiqués el enlace de acceso.",
        ],
        success: 'Se creó un grupo ficticio de tres personas con un gasto, se abrió desde otro navegador y se comprobaron sus exportaciones JSON/CSV. Una restauración aislada recuperó el grupo y el gasto. Se probó el borrado nativo del gasto; después se eliminó el grupo exacto de prueba mediante administración de base de datos con controles de identificación.',
        troubleshooting: 'Si los totales no coinciden, revisá la moneda, quién pagó y las partes. Las tasas automáticas y la IA para recibos no están disponibles. HTTPS no cifra automáticamente tus exportaciones. No incluyás enlaces del grupo ni archivos descargados en consultas públicas.',
        privacy: 'Spliit guarda grupos, participantes, gastos y actividad en el servidor. Cualquiera con el enlace puede leerlos, editarlos y conservar una exportación. Los accesos del navegador persisten hasta que los borrés. Las copias operativas locales no tienen caducidad automática y permanecen en esta VM hasta que la persona operadora las elimine; borrar datos activos no borra las copias antiguas. No son copias externas.',
        next: 'Exportá después de cambios importantes y compará los saldos finales con el grupo antes de saldar cuentas fuera de la aplicación.',
      },
    },
  },
  {
    id: 'gift-wishlist', paths: { en: 'guides/gift-wishlist', es: 'guias/lista-regalos' },
    tools: [{ id: 'wishlist', label: { en: 'Open Wishlist', es: 'Abrir Wishlist' } }],
    samples: [], reviewedOn: '2026-10-09',
    copy: {
      en: {
        title: 'Organize a shared gift wishlist',
        intro: "Keep gift ideas together in groups and lists with your Utilibre account. Enter product details yourself and check who can see each list before sharing.",
        prerequisites: 'You need an approved Utilibre account. Start with fictional wishes. Uploaded image URLs do not require sign-in even when the list does; avoid confidential images.',
        steps: [
          'Sign in with Utilibre. If you have no group yet, open the user/group menu and create a group, or join a manager’s invitation. A new account is not automatically placed in a shared group.',
          'Choose Create List, enter its name and choose Create. Then choose Create item and enter the title and optional price or URL. Automatic product-page extraction is unavailable; enter the details yourself.',
          'Review the group members and the list’s visibility before sharing. Public registry sharing is a separate native option; an ordinary list starts nonpublic. Anyone receiving an unsigned uploaded-image URL can retrieve that image.',
          'Keep important wish details in your own file. This release has no native bulk account/JSON/CSV export. The item Import option accepts a product/share URL; it is not an import of an independent database backup.',
          'Use the native list/item controls to remove wishes. A group manager can delete the group. An item linked to more than one list may remain through its other links.',
          'For account deletion, ask the operator privately to use Admin → Users. This does not delete your Utilibre identity account. Uploaded files can remain after their list/account records are deleted; request removal of a specific image privately. Do not send passwords or session tokens.',
        ],
        success: 'Public HTTPS sign-in, ordinary-user group/list/item creation, anonymous denial of the private list, isolated SQLite restore, native group deletion and operator deletion of the disposable app account passed. A separate isolated check passed image upload and a second member’s reserve, mark-purchased and unclaim actions. Direct item deletion removed its image; deleting the group removed its item records but left the image accessible. Image/database snapshot consistency was not tested.',
        troubleshooting: 'A new account without a group may first show the no-group page; use the user/group menu. Enter products manually when automatic lookup is unavailable. Invitation/reset links use native manager/operator controls; this instance does not send notification email.',
        privacy: 'Profiles, lists, wishes, prices, notes, links, claims, memberships and sessions are stored on the server. Uploaded images are not access-protected by the containing list. The tested browser used only Wishlist and Utilibre identity hosts. Local backups include database, uploads and private configuration; they have no automatic expiry, stay on this VM and are not off-site. Deletion does not alter old backups or other people’s copies.',
        next: 'Review membership and visibility whenever a group changes. Keep an independent written copy of wishes you need to preserve.',
      },
      es: {
        title: 'Organizá una lista compartida de regalos',
        intro: "Reuní ideas para regalos en grupos y listas con tu cuenta de Utilibre. Ingresá los detalles de cada producto y revisá quién puede ver cada lista antes de compartirla.",
        prerequisites: 'Necesitás una cuenta de Utilibre aprobada. Empezá con deseos ficticios. Las URL de imágenes cargadas no exigen iniciar sesión aunque la lista sí lo haga; evitá imágenes confidenciales.',
        steps: [
          'Iniciá sesión con Utilibre. Si todavía no tenés grupo, abrí el menú de usuario/grupo y creá uno o sumate con una invitación de quien lo administra. Una cuenta nueva no entra automáticamente en un grupo compartido.',
          'Elegí Create List, ingresá un nombre y elegí Create. Después elegí Create item e ingresá el título y, si querés, precio o enlace. La extracción automática de páginas de productos no está disponible; completá los datos manualmente.',
          'Revisá los miembros del grupo y la visibilidad de la lista antes de compartir. Publicar una lista de regalos es una opción nativa separada; una lista común comienza sin ser pública. Cualquiera que reciba la URL sin firma de una imagen cargada puede verla.',
          'Conservá los detalles importantes en un archivo propio. Esta versión no exporta cuentas completas ni JSON/CSV de forma nativa. La opción Import del artículo acepta un enlace de producto o compartido; no importa una copia independiente de la base de datos.',
          'Usá los controles nativos de listas y artículos para quitar deseos. Quien administra el grupo puede eliminarlo. Un artículo vinculado a varias listas puede permanecer mediante sus otros vínculos.',
          "Para borrar la cuenta, pedí en privado que la persona operadora use Admin → Users. Esto no elimina tu cuenta de identidad de Utilibre. Los archivos cargados pueden permanecer después de borrar sus registros de lista o cuenta; pedí en privado el borrado de una imagen concreta. No enviés contraseñas ni tokens de sesión.",
        ],
        success: 'Se probaron el ingreso HTTPS, la creación de grupo/lista/artículo con un usuario común, la denegación anónima de la lista privada, una restauración SQLite aislada, el borrado nativo del grupo y el borrado de la cuenta desechable por la persona operadora. Otra prueba aislada pasó la carga de imágenes y las acciones de reservar, marcar como comprado y quitar la reserva con otro miembro. Borrar un artículo directamente eliminó su imagen; borrar el grupo quitó sus registros de artículos pero dejó la imagen accesible. No se probó la consistencia de una instantánea conjunta de imágenes y base de datos.',
        troubleshooting: 'Una cuenta sin grupo puede mostrar primero la página correspondiente; usá el menú de usuario/grupo. Ingresá los productos manualmente cuando no haya búsqueda automática. Las invitaciones y los enlaces de recuperación usan los controles nativos de administración; esta instancia no envía correos de notificación.',
        privacy: 'Los perfiles, listas, deseos, precios, notas, enlaces, reservas, membresías y sesiones se guardan en el servidor. La lista no protege el acceso a las imágenes cargadas. El navegador probado solo contactó Wishlist y la identidad de Utilibre. Las copias locales incluyen base de datos, cargas y configuración privada; no caducan automáticamente, permanecen en esta VM y no son externas. El borrado no modifica copias antiguas ni copias de otras personas.',
        next: 'Revisá los miembros y la visibilidad cada vez que cambie un grupo. Conservá una copia escrita independiente de los deseos que necesités guardar.',
      },
    },
  },
  {
    id: 'household-recipes', paths: { en: 'guides/household-recipes', es: 'guias/recetas-hogar' },
    tools: [{ id: 'kitchenowl', label: { en: 'Open KitchenOwl', es: 'Abrir KitchenOwl' } }],
    samples: [], reviewedOn: '2026-10-09',
    copy: {
      en: {
        title: 'Keep household recipes and export a copy',
        intro: "Organize recipes, shopping and meal plans with your Utilibre account. Save supported content as JSON for a compatible KitchenOwl installation.",
        prerequisites: 'You need an approved Utilibre account and permission to manage the relevant household. Practice in a disposable household before importing into shared data. Recipe URL scraping and AI are disabled.',
        steps: [
          'Sign in with Utilibre and create or join the intended household. Enter recipes and ingredients manually. Review household members before adding personal information; some household profile fields can also be retrieved by other authenticated users who know its identifier.',
          'Open Settings, then the household’s settings and Danger zone → Export. Save the downloaded household_export.json file somewhere private.',
          'The JSON includes household metadata, member usernames, shopping-list names, recipes/ingredients/tags/times, items/categories and expenses. It does not provide account credentials, identity links, sessions, permissions, full planner history, shopping-list item/check states or embedded image files. Photo references still depend on the original files.',
          'In a suitable target household on a compatible KitchenOwl installation, choose Import, select the JSON and review the supported content to import. Import handles items, recipes, expenses and shopping-list names; it does not recreate every exported setting or membership.',
          'Check a recipe and its ingredients after importing. The verified round trip used one fictional item/category and recipe/ingredients; image and expense migration were not tested. Keep separate copies of important image files.',
          'For household deletion, use its Danger zone → Delete household; this affects all members. Account deletion is a separate native profile action and does not revoke your Utilibre identity or erase other members’ retained copies. Uploaded-file cleanup and older backups are separate from deletion of live records.',
        ],
        success: 'Real HTTPS sign-in and a fictional native JSON item/recipe export → import into a second household passed. Anonymous export was denied. An isolated database/files restore passed; both fictional households and the disposable app account were deleted through native endpoints, and its token was rejected afterwards.',
        troubleshooting: 'Choose the correct target household before importing and check the supported selection. An exported photo filename is not an image backup. Automatic recipe fetching and AI are unavailable; use manual entry. Import is not a complete account or permission migration.',
        privacy: 'Accounts, memberships, lists, recipes, plans, expenses and tokens are stored on the server, with uploaded images in local files. Household members share content; some household profile metadata is visible to other authenticated users by identifier. There is no end-to-end-encryption claim. Local backups have no automatic expiry, remain on this VM and are not off-site. Live deletion leaves old backups unchanged.',
        next: 'Export regularly and check your independent copies. Protect JSON and image downloads, which remain on your device until you delete them.',
      },
      es: {
        title: 'Guardá recetas del hogar y exportá una copia',
        intro: "Organizá recetas, compras y comidas con tu cuenta de Utilibre. Guardá el contenido admitido como JSON para una instalación compatible de KitchenOwl.",
        prerequisites: 'Necesitás una cuenta de Utilibre aprobada y permiso para gestionar el hogar correspondiente. Practicá en un hogar desechable antes de importar sobre datos compartidos. La extracción de recetas por URL y la IA están desactivadas.',
        steps: [
          'Iniciá sesión con Utilibre y creá o elegí el hogar previsto. Ingresá recetas e ingredientes manualmente. Revisá sus miembros antes de agregar información personal; otros usuarios autenticados que conozcan su identificador también pueden consultar algunos datos del perfil del hogar.',
          'Abrí Settings, luego los ajustes del hogar y Danger zone → Export. Guardá el archivo household_export.json descargado en un lugar privado.',
          'El JSON incluye metadatos del hogar, nombres de usuarios miembros, nombres de listas, recetas/ingredientes/etiquetas/tiempos, artículos/categorías y gastos. No incluye credenciales, vínculos de identidad, sesiones, permisos, historial completo del planificador, artículos o marcas de las listas de compras ni archivos de imagen incorporados. Las referencias de fotos siguen dependiendo de los originales.',
          'En un hogar de destino adecuado de una instalación compatible de KitchenOwl, elegí Import, seleccioná el JSON y revisá el contenido compatible que vas a importar. Se importan artículos, recetas, gastos y nombres de listas; no se recrean todos los ajustes o membresías exportados.',
          'Comprobá una receta y sus ingredientes después de importar. La prueba usó un artículo/categoría y una receta/ingredientes ficticios; no se probaron migraciones de imágenes o gastos. Conservá copias separadas de las imágenes importantes.',
          'Para borrar un hogar, usá Danger zone → Delete household; afecta a todos sus miembros. El borrado de cuenta es una acción nativa separada del perfil y no revoca tu identidad de Utilibre ni elimina las copias conservadas por otras personas. La limpieza de archivos cargados y las copias antiguas son distintas del borrado de registros activos.',
        ],
        success: 'Se probaron el ingreso HTTPS y la exportación JSON nativa de un artículo y una receta ficticios, seguida de su importación en otro hogar. Se denegó la exportación anónima. Se comprobó una restauración aislada de base de datos y archivos; se borraron ambos hogares y la cuenta desechable por funciones nativas, y su token dejó de ser aceptado.',
        troubleshooting: 'Elegí el hogar correcto antes de importar y revisá la selección compatible. El nombre exportado de una foto no es una copia de esa imagen. La extracción automática de recetas y la IA no están disponibles; usá el ingreso manual. Importar no migra toda la cuenta ni sus permisos.',
        privacy: 'Las cuentas, membresías, listas, recetas, planes, gastos y tokens se guardan en el servidor; las imágenes cargadas se guardan en archivos locales. Los miembros comparten contenido; otros usuarios autenticados pueden ver ciertos metadatos del perfil mediante su identificador. No se promete cifrado de extremo a extremo. Las copias locales no caducan automáticamente, permanecen en esta VM y no son externas. El borrado activo no modifica copias antiguas.',
        next: 'Exportá con frecuencia y comprobá tus copias independientes. Protegé los JSON y las imágenes descargados: permanecen en tu dispositivo hasta que los eliminés.',
      },
    },
  },
];
