import type { PracticalGuide } from './practical-guide-data.ts';
export const knitNewtonGuides: PracticalGuide[] = [
  {
    id: 'knit', paths: { en: 'guides/knitting-pattern', es: 'guias/patron-de-tejido' }, tools: [{ id: 'knit', label: { en: 'Open Knit', es: 'Abrir Knit' } }], samples: [], reviewedOn: '2026-10-09',
    copy: {
      en: {
        title: 'Keep your place in a knitting pattern', intro: 'Knit generates its included patterns in your browser and keeps the selected row in the page URL. Save that complete URL when you stop.',
        prerequisites: 'Use a current browser with JavaScript. Native controls and stitch abbreviations are in English. Start with a small fictional pattern and check the stitch instructions before using your yarn.',
        steps: ['Choose Pattern and adjust the displayed measurements. Cables, Capelet, Triangles and Sophie Scarf are the included pattern families; this is not an importer for arbitrary knitting charts.', 'Choose the rocket button, Start knitting. Use the left and right arrows to follow the rows. The highlighted row is your current place.', 'Bookmark or copy the complete URL, including everything after #, after making progress. It contains the non-default pattern inputs and row number; it does not contain every row-visit time or elapsed-time history.', 'Open that saved URL in another tab or browser and compare the pattern settings and highlighted row. A saved older URL restores its older row, not later progress in another tab.', 'To start again, open the base Knit URL without its fragment. Remove old bookmarks, copied links and browser history separately if you no longer need them.'],
        success: 'A cable pattern with six cables and two row advances was restored from its full URL in a fresh browser context. Desktop and 390-pixel workflows passed without external requests or browser errors.',
        troubleshooting: 'If a value is invalid, correct the field before starting. Native controls do not provide a document/PDF export or account backup. Browser history can change; keep an independent note of your settings and row for important work.',
        privacy: 'Pattern calculations stay in the browser. URL fragments are not sent in HTTP requests, but bookmarks, browser history and copied links can retain them after tab closure. Sharing a full URL shares the settings and row. The tested build stores no pattern in localStorage or IndexedDB. Loading its assets creates ordinary connection metadata; opening an external help link is a separate request.',
        next: 'Check the restored row before continuing. Utilibre cannot recover a lost pattern URL or erase copies kept in another browser.',
      },
      es: {
        title: 'Conservá tu posición en un patrón de tejido', intro: 'Knit genera los patrones incluidos en tu navegador y conserva la fila seleccionada en la URL. Guardá esa URL completa cuando parés.',
        prerequisites: 'Usá un navegador actual con JavaScript. Los controles y abreviaturas de puntos están en inglés. Empezá con un patrón ficticio pequeño y revisá las instrucciones antes de usar tu lana.',
        steps: ['Elegí Pattern y ajustá las medidas que aparecen. Las familias incluidas son Cables, Capelet, Triangles y Sophie Scarf; no es un importador de cualquier gráfico de tejido.', 'Elegí el botón del cohete, Start knitting. Usá las flechas izquierda y derecha para seguir las filas. La fila resaltada indica tu posición.', 'Guardá en favoritos o copiá la URL completa, incluido todo lo que sigue a #, después de avanzar. Contiene los ajustes que difieren de los iniciales y el número de fila; no contiene cada tiempo de visita ni todo el historial de duración.', 'Abrí esa URL guardada en otra pestaña o navegador y compará los ajustes y la fila resaltada. Una URL anterior restaura su fila anterior, no lo que avanzaste después en otra pestaña.', 'Para empezar de nuevo, abrí la URL base de Knit sin el fragmento. Borrá por separado favoritos, enlaces copiados e historial del navegador si ya no los necesitás.'],
        success: 'Se restauró un patrón de seis cables con dos avances de fila desde su URL completa en un navegador nuevo. Los recorridos de escritorio y 390 píxeles pasaron sin solicitudes externas ni errores del navegador.',
        troubleshooting: 'Si un valor no es válido, corregí el campo antes de empezar. Los controles nativos no ofrecen exportación de documentos o PDF ni respaldo de cuenta. El historial puede cambiar; conservá una nota independiente de ajustes y fila para el trabajo importante.',
        privacy: 'Los cálculos quedan en el navegador. Los fragmentos de URL no se envían en las solicitudes HTTP, pero favoritos, historial y enlaces copiados pueden conservarlos después de cerrar. Compartir la URL completa comparte ajustes y fila. La compilación probada no guarda patrones en localStorage ni IndexedDB. Cargar recursos genera metadatos de conexión; abrir ayuda externa es una solicitud separada.',
        next: 'Revisá la fila restaurada antes de seguir. Utilibre no puede recuperar una URL perdida ni borrar copias conservadas en otro navegador.',
      },
    },
  },
  {
    id: 'newton', paths: { en: 'guides/darts-tournament', es: 'guias/torneo-de-dardos' }, tools: [{ id: 'newton', label: { en: 'Open NewTon', es: 'Abrir NewTon' } }], samples: [], reviewedOn: '2026-10-09',
    copy: {
      en: {
        title: 'Create and keep a darts tournament', intro: 'NewTon’s browser edition stores tournaments on your device. Create a fictional four-player event, export it, then check the JSON in a separate browser before relying on that backup.',
        prerequisites: 'Use a current browser with JavaScript, localStorage, IndexedDB and downloads. Controls are in English. Import only trusted JSON; a desktop screen remains more comfortable for a large bracket. No server account is required.',
        steps: ['In Tournament Setup, enter a fictional name and date and choose Create tournament. Open Player Registration and use + New player to create four distinct short names.', 'Open Tournament Bracket. Mark the participating players as paid by clicking their names, even for a free practice event: this is the native eligibility control. Dismiss the help panel if it opens. Choose Single Elimination Cup and confirm Generate.', 'Return through Setup in the bracket header and choose Export tournament. Keep the JSON download. It includes this tournament’s players, bracket, matches, included transaction history, configuration snapshot and player database. Completed-event history can be pruned by the native exporter; it is not every tournament, every preference or the separate Analytics database. Server credentials are omitted.', 'In a separate browser profile, open NewTon and choose import a tournament file, select the JSON and confirm Import Tournament. Compare players and bracket. The installed version preserved the tested four-player event, while import deliberately kept that browser’s Global Settings. Inspect settings separately; use a compatible NewTon version.', 'For deletion, first create or load a different tournament, then use the original tournament’s Delete control in Setup and confirm. This removes that working tournament and its transaction history. Analytics records and the player database have separate controls; deleting one tournament does not erase those copies. Delete downloaded JSON and independent backups separately.'],
        success: 'Native creation, paid-player selection, a four-player single-elimination bracket, JSON export/import in a fresh context, browser reload and working-tournament deletion passed at desktop and 390-pixel width. No external, PHP/API, proprietary-client or font requests occurred.',
        troubleshooting: 'Server backup, network handover and Chalker are unavailable in this edition. Analytics is the native local darts-results registry. Its separate database export/import was reviewed in source but was not the round trip tested here. Deleting its tournament records is separate from Setup; player records already used in statistics may need archiving instead of deletion.',
        privacy: 'LocalStorage and IndexedDB can retain tournaments, player details, settings and match statistics after tab closure. This app does not encrypt them or downloaded JSON. The local Analytics feature is user-requested game data, not visitor tracking. No tournament backend or operator data backup exists here. Clearing all tools.utilibre.org site data can also erase work in other tools, so prefer native controls and export first.',
        next: 'Keep dated JSON copies and verify the imported event and settings. Loading the application creates connection metadata through the delivery providers; user-opened external links are separate requests.',
      },
      es: {
        title: 'Creá y conservá un torneo de dardos', intro: 'La edición de navegador de NewTon guarda torneos en tu dispositivo. Creá un evento ficticio de cuatro jugadores, exportalo y revisá el JSON en otro navegador antes de confiar en ese respaldo.',
        prerequisites: 'Usá un navegador actual con JavaScript, localStorage, IndexedDB y descargas. Los controles están en inglés. Importá solo JSON de confianza; una pantalla de escritorio sigue siendo más cómoda para un cuadro grande. No necesitás cuenta en el servidor.',
        steps: ['En Tournament Setup, ingresá un nombre y fecha ficticios y elegí Create tournament. Abrí Player Registration y usá + New player para crear cuatro nombres cortos distintos.', 'Abrí Tournament Bracket. Marcá como pagados a quienes participan pulsando sus nombres, incluso para una práctica gratuita: es el control nativo de participación. Cerrá la ayuda si aparece. Elegí Single Elimination Cup y confirmá Generate.', 'Volvé mediante Setup en la cabecera del cuadro y elegí Export tournament. Conservá el JSON descargado. Incluye jugadores, cuadro, partidas, historial de operaciones incluido, una instantánea de configuración y la base de jugadores. El exportador puede recortar el historial de eventos terminados; no contiene todos los torneos, preferencias ni la base separada de Analytics. Omite credenciales del servidor.', 'En otro perfil del navegador, abrí NewTon y elegí import a tournament file, seleccioná el JSON y confirmá Import Tournament. Compará jugadores y cuadro. La versión instalada conservó el evento probado de cuatro jugadores; la importación mantuvo deliberadamente los Global Settings de ese navegador. Revisá los ajustes por separado y usá una versión compatible de NewTon.', 'Para borrar, primero creá o cargá otro torneo; después usá Delete en el torneo original de Setup y confirmá. Esto elimina ese torneo de trabajo y su historial de operaciones. Los registros de Analytics y la base de jugadores tienen controles separados; borrar un torneo no elimina esas copias. Borrá por separado JSON descargados y respaldos independientes.'],
        success: 'Pasaron la creación nativa, selección de jugadores pagados, cuadro de eliminación simple de cuatro jugadores, exportación e importación JSON en un contexto nuevo, recarga y borrado del torneo de trabajo, en escritorio y a 390 píxeles. No hubo solicitudes externas, a PHP/API, al cliente propietario ni a fuentes.',
        troubleshooting: 'Esta edición no ofrece respaldo en servidor, transferencia por red ni Chalker. Analytics es el registro local nativo de resultados de dardos. Su exportación e importación separada se revisó en el código, pero no fue el recorrido probado acá. Borrar sus torneos es independiente de Setup; los jugadores usados en estadísticas pueden requerir archivado en lugar de borrado.',
        privacy: 'LocalStorage e IndexedDB pueden conservar torneos, datos de jugadores, ajustes y estadísticas después de cerrar la pestaña. La aplicación no cifra esos datos ni el JSON descargado. Analytics contiene datos de juego solicitados por vos, no rastreo de visitantes. Acá no hay servidor de torneos ni respaldo de esos datos a cargo del operador. Borrar todos los datos de tools.utilibre.org también puede borrar trabajo de otras herramientas: preferí los controles nativos y exportá primero.',
        next: 'Conservá JSON con fecha y verificá el evento importado y sus ajustes. Cargar la aplicación genera metadatos de conexión en los proveedores de entrega; los enlaces externos que abrís son solicitudes separadas.',
      },
    },
  },
];
