import type { PracticalGuide } from './practical-guide-data.ts';

export const nextFeatureGuides: PracticalGuide[] = [
  {
    id: 'shared-board', paths: { en: 'guides/shared-whiteboard', es: 'guias/pizarra-compartida' },
    tools: [{ id: 'wbo', label: { en: 'Open the temporary shared whiteboard', es: 'Abrir la pizarra compartida temporal' } }], samples: [],
    copy: {
      en: {
        title: 'Draw together on a temporary whiteboard', intro: 'Make a small fictional workshop sketch with another person, then save an SVG picture. No account is needed; this pilot is not private document storage.',
        prerequisites: 'Two current browsers with JavaScript, a network connection and downloads enabled. A mouse and larger screen help. Do not use confidential information: anyone with the room address can participate and the server can read drawings. The editor follows your browser language where supported.',
        steps: ['Open the temporary whiteboard and read its limitations. Choose Create an unlisted board. Read the notice again if shown, then choose Continue with non-sensitive content.', 'Copy the complete board address to your participant. They open the same address in their browser and acknowledge the notice. Do not publish that link if you do not want other people joining; an unlisted link is not an authenticated private room.', 'For a fictional workshop, choose the rectangle tool and draw a box. Ask the other person to draw a second box next to it. Confirm that both people see both shapes. Add an arrow or a short non-sensitive label if useful.', 'If one participant disconnects, reopen the same address after connectivity returns. The saved scene can reappear while the service has stayed running. If the server restarted, previous drawings are not recoverable here.', 'Choose Download (the download-arrow tool) to save SVG. Open that file in a browser and check both boxes are visible. Give the downloaded file a useful name. SVG is an exported picture; editable re-import is not promised.', 'Export before leaving and during longer sessions. Closing all tabs does not erase a board or revoke a shared link. Oldest objects are discarded above 256 objects. Do not depend on the room as a backup.'],
        success: 'Both independent browsers see both participants’ shapes, and the downloaded SVG opens with the expected drawing. A screenshot or one working browser alone does not establish collaboration.',
        troubleshooting: 'Wait for the connection before drawing. If edits do not reach the other participant, check that both opened the identical room address and reconnect. A busy pilot may reject new connections; wait before retrying. If the service restarted, use your exported SVG as a reference, not an automatic scene restore. No image-upload feature is provided in this build.',
        privacy: 'Drawing data travels through Cloudflare to Utilibre and room participants. It is not end-to-end encrypted. Scenes use temporary server storage and disappear when the service stops or restarts; there is no fixed expiry or recovery promise. Browser history, recent room names and other people’s copies can remain. Clearing your browser data does not delete the server scene.',
        next: 'For private local sketching, use Excalidraw instead. Save its native file if you need an editable project. Share the exported WBO picture only after checking it contains nothing sensitive.',
      },
      es: {
        title: 'Dibujá en grupo en una pizarra temporal', intro: 'Hacé un boceto ficticio de un taller con otra persona y guardá una imagen SVG. No necesitás cuenta; este piloto no es almacenamiento privado.',
        prerequisites: 'Dos navegadores actuales con JavaScript, conexión y descargas habilitadas. Convienen un mouse y una pantalla grande. No usés información confidencial: cualquiera con la dirección puede participar y el servidor puede leer el dibujo. El editor sigue el idioma del navegador cuando está disponible.',
        steps: ['Abrí la pizarra temporal y leé sus límites. Elegí Crear una pizarra sin listar. Si aparece el aviso, leelo y elegí Continuar con datos no sensibles.', 'Copiá la dirección completa para la otra persona. Debe abrirla en su navegador y aceptar el aviso. No publiqués el enlace si no querés que otras personas entren; no es una sala privada protegida por cuenta.', 'Para un taller ficticio, elegí la herramienta de rectángulo y dibujá un cuadro. Pedile a la otra persona que dibuje otro al lado. Comprobá que ambas ven los dos cuadros. Agregá una flecha o un rótulo breve sin datos sensibles si sirve.', 'Si alguien pierde conexión, reabrí la misma dirección cuando vuelva. El dibujo puede reaparecer si el servicio siguió funcionando. Si el servidor se reinició, aquí no se puede recuperar lo anterior.', 'Elegí Descargar (la herramienta con flecha de descarga) para guardar SVG. Abrilo en el navegador y comprobá los dos cuadros. Dale un nombre útil. SVG es una imagen exportada; no se promete volver a importarla como proyecto editable.', 'Exportá antes de salir y durante sesiones largas. Cerrar todas las pestañas no borra la pizarra ni revoca el enlace. Al superar 256 objetos se descartan los más antiguos. No usés la sala como respaldo.'],
        success: 'Los dos navegadores independientes muestran los trazos de ambas personas y el SVG descargado se abre con el dibujo esperado. Una captura o una sola sesión no demuestra colaboración.',
        troubleshooting: 'Esperá a que se conecte antes de dibujar. Si los cambios no llegan, comprobá que ambas personas abrieron exactamente la misma dirección y reconectá. Si el piloto está ocupado puede rechazar conexiones; esperá antes de reintentar. Si se reinició, usá el SVG como referencia, no como restauración automática. Esta versión no permite subir imágenes.',
        privacy: 'El dibujo pasa por Cloudflare hacia Utilibre y los participantes. No tiene cifrado de extremo a extremo. Las pizarras usan almacenamiento temporal y desaparecen al detener o reiniciar el servicio; no hay vencimiento fijo ni promesa de recuperación. El historial, los nombres recientes y las copias de otras personas pueden permanecer. Borrar los datos del navegador no borra el dibujo del servidor.',
        next: 'Para bocetar de forma local, usá Excalidraw. Guardá su archivo nativo si necesitás un proyecto editable. Antes de compartir el SVG de WBO, comprobá que no tenga información sensible.',
      },
    },
  },
  {
    id: 'my-utilibre', paths: { en: 'guides/my-utilibre', es: 'guias/mi-utilibre' }, tools: [], samples: [],
    portalLinks: [{ en: '/en/my-utilibre', es: '/es/mi-utilibre', label: { en: 'Manage My Utilibre', es: 'Gestionar Mi Utilibre' } }],
    copy: {
      en: {
        title: 'Save and share your tool collection', intro: 'Keep the tools you need together without creating an account. Move the selection to another browser with an export or a shared link.',
        prerequisites: 'JavaScript and optional browser storage. This saves only collection names, tool IDs, order and language—not application documents, sign-ins or private links. Use harmless collection names.',
        steps: ['Open My Utilibre. Under Choose a tool to pin, select a tool and choose Pin tool. For example, pin draw.io, RAWGraphs and PairDrop for a fictional workshop.', 'Use Move up and Move down beside each tool to order it. These are keyboard buttons: Tab to the button, then press Enter or Space. Unpin removes only the shortcut.', 'Open Manage collections. Rename the collection “Workshop practice”, or create another collection. Choose Use as starting collection for the selection that should open when you return to My Utilibre; this does not change your browser homepage.', 'Choose Export all collections and keep the JSON file. On another device, open My Utilibre, select that file and choose Import and replace collections. Review the confirmation: importing replaces the toolkit selections, not application documents.', 'Copy the collection link. A recipient opens a preview without changing their own collections, then chooses Save a copy to my collections if wanted. Everyone with the link can read its name and tool IDs. To make a QR, copy the link and paste it into QR Tools; this is a manual handoff.', 'To remove this preference data, export first if needed and choose Reset only toolkit preferences. It does not reset other applications or the portal theme. Deleting a collection does not revoke copies or links you already shared.'],
        success: 'Reload My Utilibre and check the starting collection and order. Open the shared link in a separate browser profile: it should show a preview, not replace existing selections. Open a tool and check its current access label.',
        troubleshooting: 'If storage is unavailable, changes may last only in the open page; export before leaving. Invalid or oversized imports are rejected. Limits are 12 collections, 64 tools per collection and 256 pins total; imports are at most 32 KB. Unknown or retired tool IDs are shown without invented destinations. Remove them when no longer useful. Large collections can make QR codes dense; send the link instead.',
        privacy: 'Preferences stay in this browser. A shared fragment is not sent in the ordinary HTTP page request, but is readable by recipients, browser history and software with access to the link; it is not encrypted. Never put private information in the label. Tool sign-in and availability rules do not change.',
        next: 'Try the native starting projects guide. Each guide offers a shared selection of its tools; save that selection explicitly if useful.',
      },
      es: {
        title: 'Guardá y compartí tu colección de herramientas', intro: 'Reuní las herramientas que necesitás sin crear una cuenta. Pasá la selección a otro navegador con una exportación o un enlace compartido.',
        prerequisites: 'JavaScript y almacenamiento opcional del navegador. Solo se guardan nombres de colecciones, ID de herramientas, orden e idioma; no documentos, sesiones ni enlaces privados. Usá nombres sin datos sensibles.',
        steps: ['Abrí Mi Utilibre. En Elegí una herramienta para fijar, seleccioná una y elegí Fijar herramienta. Por ejemplo, fijá draw.io, RAWGraphs y PairDrop para un taller ficticio.', 'Usá Subir y Bajar junto a cada herramienta. Funcionan con teclado: llegá con Tab y presioná Enter o Espacio. Quitar elimina solo el acceso directo.', 'Abrí Gestionar colecciones. Cambiá el nombre a “Práctica de taller” o creá otra colección. Usá Usar como colección inicial para elegir cuál aparece al volver a Mi Utilibre; no cambia la página de inicio del navegador.', 'Elegí Exportar todas las colecciones y conservá el JSON. En otro dispositivo, abrí Mi Utilibre, seleccioná ese archivo y elegí Importar y reemplazar colecciones. Leé la confirmación: reemplaza selecciones, no documentos de las aplicaciones.', 'Copiá el enlace de la colección. El destinatario ve una vista previa sin cambiar sus colecciones y decide si elige Guardar una copia en mis colecciones. Cualquiera con el enlace puede leer el nombre y los ID. Para crear un QR, copiá el enlace y pegalo en QR Tools; es un paso manual.', 'Para borrar estas preferencias, exportá primero si necesitás una copia y elegí Restablecer solo las colecciones. No borra otras aplicaciones ni el tema del portal. Eliminar una colección no revoca copias ni enlaces compartidos.'],
        success: 'Recargá Mi Utilibre y revisá la colección inicial y el orden. Abrí el enlace compartido en otro perfil del navegador: debe mostrar una vista previa sin reemplazar tus selecciones. Abrí una herramienta y revisá sus requisitos actuales.',
        troubleshooting: 'Si el almacenamiento no está disponible, los cambios pueden durar solo mientras la página siga abierta; exportá antes de salir. Se rechazan importaciones inválidas o demasiado grandes. Los límites son 12 colecciones, 64 herramientas por colección, 256 elementos en total y archivos de hasta 32 KB. Los ID desconocidos o retirados se muestran sin inventar destinos. Los QR de colecciones largas pueden ser densos; enviá el enlace.',
        privacy: 'Las preferencias quedan en este navegador. El fragmento compartido no se envía en la solicitud HTTP normal de la página, pero lo pueden leer destinatarios, historial y software con acceso al enlace; no está cifrado. No pongás información privada en el nombre. Los requisitos de acceso y disponibilidad no cambian.',
        next: 'Probá la guía de proyectos de práctica. Cada guía ofrece una selección compartida de sus herramientas; guardala explícitamente si te sirve.',
      },
    },
  },
  {
    id: 'open-with', paths: { en: 'guides/open-with-utilibre', es: 'guias/abrir-con-utilibre' }, tools: [{ id: 'private-router', label: { en: 'Check a Reddit link', es: 'Revisar un enlace de Reddit' } }], samples: [],
    copy: {
      en: {
        title: 'Open supported links with Utilibre', intro: 'Check a public Reddit link locally, then choose Redlib or the original site. Optional browser settings can make repeat visits easier.',
        prerequisites: 'Use a public Reddit community, profile, search or post link. Redlib is a reading frontend, not Reddit login. Remote media, login, settings and /s/ share-token links are unsupported. A supported community ?sort= value is also translated into Redlib’s sort path; the original parameter remains. Conflicting or unsupported community sorts are rejected.',
        steps: ['Open Check a Reddit link and paste https://www.reddit.com/r/Guatemala/?sort=new as a public example. Choose Check URL. Nothing is fetched merely by converting the link.', 'Read the displayed Redlib destination. Meaningful parameters, repeated values and fragments are preserved; only utm_source, utm_medium, utm_campaign, utm_term, utm_content, utm_id, share_id and rdt tracking fields are stripped. A redd.it post ID becomes /comments/ID without resolving it remotely.', 'Choose Continue to Redlib, Copy Utilibre link, or Open original on Reddit. Opening the original contacts Reddit directly. A converted URL is not a guarantee that Reddit will supply that page to the instance.', 'For optional extension use, obtain LibRedirect from its official website, open its settings, select Reddit and the Redlib frontend, and add the exact Utilibre Redlib origin shown by the opener as a custom instance. Select it and remove other selected instances only if you want Utilibre exclusively. Test one public post and use the extension’s original-site or disable control to return.', 'Consult LibRedirect’s browser-specific installation instructions. Firefox and Chromium packaging differ, and mobile browser support is not universal. Utilibre does not install the extension or change browser settings. Review its permissions and keep it updated.', 'In SearXNG, Preferences → General offers the optional Hostnames plugin when enabled by the operator. It changes configured hostnames, not result rankings; it cannot validate individual Reddit paths. Leave it off for original links, or turn it off and rerun the same search when a rewritten result fails. The portal opener is stricter about supported paths.'],
        success: 'The destination stays on the configured Redlib instance, the original action keeps the Reddit URL, and editing the input removes stale output. No destination opens until you choose it.',
        troubleshooting: 'For unsupported links, copy the full public post permalink. Do not paste account credentials or private messages. A challenge, missing post or upstream refusal is separate from URL conversion; do not repeatedly retry a blocked service. If copying is blocked, copy the selected output field manually.',
        privacy: 'Conversion runs in the browser with no URL lookup. Following Redlib sends a request to Utilibre, which accesses Reddit. Following the original goes directly to Reddit. Installing an extension gives that extension its requested browser permissions; it is a separate trust decision.',
        next: 'For LibRedirect 3.4.0, use a currently supported Firefox build: Reddit → Redlib → Add your favorite instances; enter the exact origin in Add instance input and press Add the instance. No Utilibre import file is required. The popup provides Redirect to Original. Its Manifest V2 build is not supported by current Google Chrome; do not downgrade a browser or alter security policy to force it. Other Chromium variants need their own current support check. These extension steps were source-reviewed, not tested in a user’s installed extension. From Redlib, its instance information page provides a native Back to Utilibre link; SearXNG already has a native Utilibre navigation link.',
      },
      es: {
        title: 'Abrí enlaces compatibles con Utilibre', intro: 'Revisá localmente un enlace público de Reddit y elegí Redlib o el sitio original. Las opciones del navegador pueden facilitar visitas futuras.',
        prerequisites: 'Usá un enlace público de comunidad, perfil, búsqueda o publicación. Redlib sirve para leer, no para iniciar sesión en Reddit. No se admiten medios externos, acceso, ajustes ni enlaces /s/ con token. Un ?sort= compatible de comunidad se traduce también a la ruta de orden de Redlib y conserva el parámetro original. Se rechazan órdenes contradictorios o incompatibles.',
        steps: ['Abrí Revisar un enlace de Reddit y pegá https://www.reddit.com/r/Guatemala/?sort=new como ejemplo público. Elegí Revisar URL. Convertir el enlace no descarga su contenido.', 'Revisá el destino de Redlib. Se conservan parámetros útiles, valores repetidos y fragmentos; solo se eliminan utm_source, utm_medium, utm_campaign, utm_term, utm_content, utm_id, share_id y rdt. Un ID de redd.it se convierte en /comments/ID sin consultar un servicio remoto.', 'Elegí Continuar a Redlib, Copiar enlace de Utilibre o Abrir original en Reddit. Abrir el original contacta directamente a Reddit. Convertir una URL no garantiza que Reddit entregue esa página a la instancia.', 'Si querés una extensión, obtené LibRedirect desde su web oficial. Abrí sus ajustes, elegí Reddit y la interfaz Redlib, y agregá como instancia personalizada el origen exacto de Utilibre mostrado por el adaptador. Seleccionalo y quitá otras instancias seleccionadas solo si querés usar exclusivamente Utilibre. Probá una publicación pública y usá el control para volver al original o desactivar la extensión.', 'Consultá las instrucciones de instalación de LibRedirect para tu navegador. Firefox y Chromium usan distribución distinta; no todos los navegadores móviles son compatibles. Utilibre no instala la extensión ni cambia tus ajustes. Revisá sus permisos y mantenela actualizada.', 'En SearXNG, Preferencias → General ofrece la extensión Hostnames cuando el operador la habilita. Cambia dominios configurados, no el orden de resultados; no valida cada ruta de Reddit. Dejala desactivada para conservar enlaces originales, o desactivala y repetí la búsqueda si falla un resultado convertido. El adaptador del portal es más estricto con las rutas.'],
        success: 'El destino queda en la instancia configurada de Redlib y la acción original conserva la URL de Reddit. Al editar el campo, desaparece el resultado anterior. Nada se abre hasta que lo elijás.',
        troubleshooting: 'Si el enlace no es compatible, copiá el enlace completo de la publicación pública. No pegues credenciales ni mensajes privados. Un desafío, una publicación ausente o un bloqueo del origen son distintos de la conversión; evitá reintentos repetidos. Si falla Copiar, copiá el campo seleccionado manualmente.',
        privacy: 'La conversión ocurre en el navegador sin consultar la URL. Abrir Redlib envía una solicitud a Utilibre, que consulta Reddit. Abrir el original contacta directamente a Reddit. Una extensión recibe los permisos que le otorgués; es una decisión de confianza aparte.',
        next: 'Para LibRedirect 3.4.0, usá una versión vigente compatible de Firefox: Reddit → Redlib → Add your favorite instances. Ingresá el origen exacto en Add instance input y elegí Add the instance. No necesitás un archivo de importación de Utilibre. El menú ofrece Redirect to Original. Esta versión usa Manifest V2, incompatible con Google Chrome actual; no desactualicés el navegador ni cambiés políticas de seguridad para forzarla. Otras variantes de Chromium requieren verificar su soporte vigente. Estos pasos se revisaron en el código, no en la extensión instalada de un usuario. La página de información de Redlib ofrece Volver a Utilibre; SearXNG ya tiene su enlace nativo de regreso.',
      },
    },
  },
  {
    id: 'starting-projects', paths: { en: 'guides/starting-projects', es: 'guias/proyectos-de-practica' },
    tools: [{ id: 'drawio', label: { en: 'Edit a process diagram', es: 'Editar un diagrama de proceso' } }, { id: 'excalidraw', label: { en: 'Plan a workshop board', es: 'Planificar un taller en una pizarra' } }, { id: 'rawgraphs', label: { en: 'Chart the survey', es: 'Graficar la encuesta' } }, { id: 'minipaint', label: { en: 'Prepare an image', es: 'Preparar una imagen' } }, { id: 'bentopdf', path: 'rotate-pdf.html', label: { en: 'Rotate a practice PDF', es: 'Rotar un PDF de práctica' } }],
    samples: [
      { file: 'process-{lang}.drawio', label: { en: 'Editable process diagram (.drawio)', es: 'Diagrama de proceso editable (.drawio)' } },
      { file: 'workshop-{lang}.excalidraw', label: { en: 'Editable workshop board (.excalidraw)', es: 'Pizarra de taller editable (.excalidraw)' } },
      { file: 'survey-{lang}.csv', label: { en: 'Fictional survey (UTF-8 CSV)', es: 'Encuesta ficticia (CSV UTF-8)' } },
      { file: 'fictional-image.jpg', label: { en: 'Fictional image (JPEG)', es: 'Imagen ficticia (JPEG)' } },
      { file: 'scan-{lang}.pdf', label: { en: 'Fictional notice (PDF)', es: 'Aviso ficticio (PDF)' } },
    ],
    copy: {
      en: {
        title: 'Start with an editable example', intro: 'Five small exercises using native formats and fictional data. Download a sample, open the named tool and save your own result.',
        prerequisites: 'Download existing work before opening an example. Use local file import, not an online URL importer. The new diagrams, workshop boards and survey CSVs are original CC0 examples; see their bundled LICENSE.txt. All sample data is fictional, not visitor records or official forms. In draw.io, Save as → Where: Download changes the confirmation button to OK. Excalidraw also supports Ctrl+O to open and Ctrl+Shift+S to save a native file.',
        steps: ['Process diagram: download the .drawio file. In draw.io choose Device, then Open Existing Diagram, or File → Open From → Device. Double-click “Prepare materials” and add a short fictional task. Use File → Save as to save a .drawio copy. Reopen that copy and confirm three steps and two arrows remain editable.', 'Workshop board: download the .excalidraw file. In Excalidraw’s main menu choose Open, then select it. The existing scene may be replaced: save it first. Edit the Before/During/After text for a fictional workshop. Use Save to in the menu for the editable file, then reopen it. This is the local whiteboard, not a shared room.', 'Survey chart: open RAWGraphs and paste the downloaded CSV text into Load your data. It records 26 fictional responses: Reading 12, Practice 8, Discussion 6. Select Bar chart, map Activity to Bars and Responses to Size. Responses are counts, not percentages. Export SVG with Download and reopen it. Reading should be the longest bar, with all labels readable.', 'Image preparation: download the JPEG, open it in miniPaint with File → Open → Open File …, and follow the image-preparation guide. As a hypothetical requirement, resize to 600 pixels wide with the ratio preserved, export PNG, and reopen it. The example becomes 600 × 400 pixels; this is not an identity-photo specification.', 'PDF practice: download the fictional notice. Open Rotate a practice PDF, select the PDF, rotate the page with the shown controls and save the result. Reopen it to check the orientation. Keep the original; the scanned-documents guide uses it to practice OCR.', 'Save all editable results before closing the browser. Use the guide’s tool collection link to preview these tools together, then explicitly save it in My Utilibre if useful. Files are not embedded in that collection link.'],
        success: 'You have an editable three-step diagram, an editable workshop board, a labeled chart with values 12/8/6, a reopened 600 × 400 image and a PDF with the intended orientation.',
        troubleshooting: 'Choose the correct native extension; renaming a PNG to .drawio does not make it editable. In RAWGraphs use UTF-8, commas, one header row and whole numeric values. On a small screen, use a larger view for field mapping rather than forcing tiny drag targets. A downloaded image or SVG is not always an editable project.',
        privacy: 'These exercises use local files in browser tools. Applications may retain working scenes or settings in browser storage. Clearing site data can erase that work. Downloading the app is a network request; importing these samples is not an upload in the tested paths. Do not enter real personal information just to practice.',
        next: 'Continue with the detailed image, CSV chart, scanned-document or file-transfer guide below.',
      },
      es: {
        title: 'Empezá con un ejemplo editable', intro: 'Cinco ejercicios pequeños con formatos nativos y datos ficticios. Descargá un ejemplo, abrí la herramienta indicada y guardá tu resultado.',
        prerequisites: 'Descargá tu trabajo antes de abrir un ejemplo. Usá importación local, no una URL. Los nuevos diagramas, pizarras y CSV son ejemplos originales bajo CC0; su LICENSE.txt lo explica. Los datos son ficticios, no registros de visitantes ni formularios oficiales. En draw.io, Guardar como → Dónde: Descargar cambia la confirmación a Aceptar (Save as → Where: Download → OK en inglés). Excalidraw también permite Ctrl+O para abrir y Ctrl+Shift+S para guardar el archivo nativo.',
        steps: ['Diagrama de proceso: descargá el .drawio. En draw.io elegí Dispositivo y Abrir diagrama existente, o Archivo → Abrir desde → Dispositivo. Hacé doble clic en “Preparar materiales” y agregá una tarea ficticia breve. Usá Archivo → Guardar como para conservar un .drawio. Reabrilo y comprobá que los tres pasos y las dos flechas sean editables.', 'Pizarra de taller: descargá el .excalidraw. En el menú principal de Excalidraw elegí Abrir y seleccioná el archivo. Puede reemplazar la escena actual: guardala primero. Editá los textos Antes/Durante/Después. Usá Guardar en para descargar la copia editable y reabrila. Esta es la pizarra local, no una sala compartida.', 'Gráfica de encuesta: abrí RAWGraphs y pegá el CSV descargado en Load your data. Representa 26 respuestas ficticias: Lectura 12, Práctica 8, Debate 6. Elegí Bar chart, asigná Actividad a Bars y Respuestas a Size. Son cantidades, no porcentajes. Exportá SVG con Download y reabrilo. Lectura debe tener la barra más larga y todos los rótulos deben leerse.', 'Preparación de imagen: descargá el JPEG y abrilo en miniPaint con File → Open → Open File …; seguí la guía de imágenes. Como requisito hipotético, reducí el ancho a 600 píxeles manteniendo la proporción, exportá PNG y reabrilo. El ejemplo queda en 600 × 400 píxeles; no son requisitos de una foto de identidad.', 'Práctica de PDF: descargá el aviso ficticio. Abrí Rotar un PDF de práctica, seleccioná el archivo, girá la página con los controles visibles y guardá el resultado. Reabrilo y comprobá la orientación. Conservá el original: también sirve para practicar OCR en la guía de documentos escaneados.', 'Guardá todos los resultados editables antes de cerrar el navegador. El enlace de colección de esta guía te deja ver estas herramientas juntas; guardalo explícitamente en Mi Utilibre si te sirve. Los archivos no se incluyen en ese enlace.'],
        success: 'Tenés un diagrama editable de tres pasos, una pizarra editable, una gráfica rotulada con valores 12/8/6, una imagen reabierta de 600 × 400 y un PDF con la orientación elegida.',
        troubleshooting: 'Elegí la extensión nativa correcta: renombrar un PNG como .drawio no lo vuelve editable. En RAWGraphs usá UTF-8, comas, una fila de encabezados y números enteros. Para asignar campos, una pantalla grande ayuda más que arrastrar controles diminutos. Una imagen o SVG no siempre es un proyecto editable.',
        privacy: 'Estos ejercicios usan archivos locales en herramientas del navegador. Las aplicaciones pueden conservar escenas y ajustes en sus propios datos locales; borrarlos puede perder el trabajo. Descargar una aplicación genera solicitudes de red; importar estos ejemplos no los sube en los recorridos probados. No ingresés datos personales reales para practicar.',
        next: 'Continuá con las guías detalladas de imágenes, gráficas CSV, documentos escaneados o transferencia de archivos.',
      },
    },
  },
];
