import type { PracticalGuide } from './practical-guide-data.ts';
export const projectsGuides: PracticalGuide[] = [{
  id: 'projects', paths: { en: 'guides/projects-board', es: 'guias/tablero-projects' }, tools: [{ id: 'projects', label: { en: 'Open Projects', es: 'Abrir Projects' } }], samples: [], reviewedOn: '2026-10-09',
  copy: {
    en: {
      title: 'Keep a copy of a Projects board',
      intro: 'Projects uses your approved Utilibre account for shared boards. Its native CSV is a useful card list, not a complete board backup. Public HTTPS sign-in, member access and CSV downloads were checked with fictional data.',
      prerequisites: 'Use a current browser and your approved Utilibre account with its configured sign-in checks. Try a fictional project first. Some interface strings and CSV headings remain in English, including Export as CSV.',
      steps: ['Choose Continue with Utilibre, then create a project and board. Add lists and cards. Grant board access only to the intended members; a different signed-in account does not automatically gain access.', 'Open the board’s three-dot menu near its sharing controls and choose Export as CSV. On a narrow screen, scroll the board controls into view. Save the download outside the browser. It includes list and card names, descriptions, assignee and label names, due dates, completion state and completed/total task counts.', 'Open the CSV in a text editor or spreadsheet. Import untrusted cells as text: the native exporter quotes CSV fields but does not neutralize spreadsheet formulas. The download omits task text, comments/history, attachment files, permissions and account settings. Download needed attachments separately.', 'There is no native CSV-to-board import in this release. A CSV cannot recreate the full project in another installation. Operator database/file recovery was tested separately with fictional data; that backup is not a self-service user export.', 'To remove an attachment, use its own Delete control before deleting its card or project if you need the active file removed. Project deletion makes the project unavailable but archives records and can leave uploaded files. Request account removal privately: the native administrator action soft-deletes the account, removes identity links and memberships, and retains identity fields. Deleting the Projects account is separate from your Utilibre identity.', 'Log out when finished. Shared members may have independent copies; earlier operator backups can also retain deleted records. Remove downloaded CSV and attachments separately when you no longer need them.'],
      success: 'Two approved accounts passed native MFA/OIDC sign-in as non-admin users; an unapproved account was rejected. Private project, card and attachment boundaries, card movement, CSV download at desktop and 390-pixel width, attachment deletion and logout revocation passed. A PostgreSQL/file backup restored fictional cards and attachment bytes into separate disposable state.',
      troubleshooting: 'The gateway limits upload requests to 10 MiB, including multipart overhead. External Markdown images are blocked, and mail, webhooks and external widgets are not enabled. A local CSV copy is not automatically encrypted. Some upstream controls use English or their original Spanish translation.',
      privacy: 'Utilibre stores readable accounts, boards, cards, tasks, comments, activity, notification state and uploaded files. Sessions include IP and user-agent metadata. Browser login state and preferences can persist after the tab closes. There is no configured automatic content/archive expiry. Daily backups stay on the same VM with no automatic expiry; a physical-host failure can affect the application and those backups together. Edge/provider log retention is separate and unverified.',
      next: 'Keep independent CSV and attachment copies, understand their omissions, and review membership before sharing. Support contains More tools / Más herramientas, which returns to the Utilibre portal.',
    },
    es: {
      title: 'Conservá una copia de un tablero de Projects',
      intro: 'Projects usa tu cuenta aprobada de Utilibre para compartir tableros. Su CSV nativo sirve como lista de tarjetas, no como respaldo completo. El acceso público por HTTPS, los permisos de integrantes y las descargas CSV se verificaron con datos ficticios.',
      prerequisites: 'Usá un navegador actual y tu cuenta aprobada de Utilibre con sus controles de acceso configurados. Probá primero con un proyecto ficticio. Algunos textos y encabezados CSV siguen en inglés, incluido Export as CSV.',
      steps: ['Elegí Continuá con Utilibre y creá un proyecto y un tablero. Agregá listas y tarjetas. Dales acceso solo a quienes corresponda; otra cuenta con sesión no obtiene acceso automáticamente.', 'Abrí el menú de tres puntos del tablero, junto a los controles para compartir, y elegí Export as CSV. En una pantalla angosta, desplazá los controles del tablero hasta verlos. Guardá la descarga fuera del navegador. Incluye nombres de listas y tarjetas, descripciones, nombres de responsables y etiquetas, fechas límite, estado de finalización y cantidades de tareas completadas y totales.', 'Abrí el CSV en un editor de texto o una hoja de cálculo. Importá como texto las celdas que no sean de confianza: el exportador entrecomilla campos CSV, pero no neutraliza fórmulas de hojas de cálculo. La descarga omite el texto de tareas, comentarios e historial, archivos adjuntos, permisos y ajustes de cuenta. Descargá por separado los adjuntos que necesités.', 'Esta versión no ofrece importación nativa de CSV a tablero. El CSV no recrea el proyecto completo en otra instalación. La recuperación de base y archivos del operador se probó por separado con datos ficticios; ese respaldo no es una exportación de autoservicio.', 'Para quitar un adjunto, usá su propio control Delete antes de borrar su tarjeta o proyecto si necesitás eliminar el archivo activo. Borrar el proyecto lo vuelve inaccesible, pero archiva registros y puede dejar archivos cargados. Pedí en privado la eliminación de cuenta: la acción nativa de administración marca la cuenta como borrada, quita vínculos de identidad y membresías, y conserva datos de identidad. Borrar la cuenta de Projects es distinto de borrar tu identidad de Utilibre.', 'Cerrá sesión al terminar. Los integrantes pueden conservar copias independientes; los respaldos anteriores del operador también pueden retener registros borrados. Borrá por separado CSV y adjuntos descargados cuando ya no los necesités.'],
      success: 'Dos cuentas aprobadas pasaron el acceso nativo MFA/OIDC sin ser administradoras; una cuenta no aprobada fue rechazada. Pasaron los límites de acceso a proyectos, tarjetas y adjuntos privados, el movimiento de tarjetas, la descarga CSV en escritorio y a 390 píxeles, el borrado de adjuntos y la revocación al cerrar sesión. Un respaldo PostgreSQL y de archivos restauró tarjetas y adjuntos ficticios en un estado temporal separado.',
      troubleshooting: 'El intermediario limita las solicitudes de carga a 10 MiB, incluido el contenido adicional de formularios. Las imágenes externas en Markdown están bloqueadas; correo, webhooks y widgets externos no están habilitados. Una copia CSV local no queda cifrada automáticamente. Algunos controles originales usan inglés o su traducción española original.',
      privacy: 'Utilibre guarda datos legibles de cuentas, tableros, tarjetas, tareas, comentarios, actividad, notificaciones y archivos. Las sesiones incluyen metadatos de IP y agente del navegador. La sesión y preferencias del navegador pueden persistir al cerrar la pestaña. No hay vencimiento automático configurado de contenido ni registros archivados. Los respaldos diarios quedan en la misma VM sin vencimiento automático; una falla del servidor físico puede afectar juntos a la aplicación y esos respaldos. La conservación de registros del borde y proveedores es independiente y no está verificada.',
      next: 'Guardá copias independientes de CSV y adjuntos, tené presentes sus omisiones y revisá integrantes antes de compartir. Support contiene More tools / Más herramientas para volver al portal de Utilibre.',
    },
  },
}];
