import type { PracticalGuide } from './practical-guide-data.ts';

export const razziaGuides: PracticalGuide[] = [{
  id: 'razzia', paths: { en: 'guides/live-quiz', es: 'guias/cuestionario-en-vivo' },
  tools: [{ id: 'razzia', label: { en: 'Join a quiz', es: 'Unirte a un cuestionario' } }, { id: 'razzia', path: '/manager', label: { en: 'Manager access', es: 'Acceso de gestión' } }], samples: [], reviewedOn: '2026-10-09',
  copy: {
    en: {
      title: 'Run a live quiz and keep its questions',
      intro: 'Participants join Razzia with a room PIN and nickname. Hosting uses a shared manager credential controlled by the operator.',
      prerequisites: 'Arrange manager access privately with the operator. Managers share the same quiz and results library; this is not a separate account for each organizer. The native UI does not include Spanish.',
      steps: ['In Manager, open Quizz and create a definition or import quiz JSON. Review each question, answer, correct solution and time limit. Use fictional names for a trial.', 'Under Play, select the quiz and choose Start game to create a room. Give participants its PIN; they open the ordinary quiz homepage and choose a nickname.', 'Check the participant list, then start the game. Use the native controls to show answers and finish the leaderboard. Completed results are saved on the server.', 'Under Quizz, choose Export quizz as JSON beside the definition. It includes questions, solutions, timing/scoring and media URLs, but not player results, credentials, active rooms or the media files themselves.', 'Use Import quizz from JSON in a compatible Razzia installation to create a new copy. Check the questions. Results can be viewed and deleted in the Results tab; this version has no results export/import button.', 'Delete unwanted definitions and finished results separately using their trash controls. Log out when finished; clear this tool’s site data on a shared device. Downloaded files and existing backups remain separate.'],
      success: 'Two simultaneous public rooms kept their players and correct/incorrect scores separate. Auth rejection, cross-manager room-control rejection, native JSON export/import, results view/deletion and an isolated restore of definitions/results passed.',
      troubleshooting: 'A restart loses active games. Shared managers can access the common stored library. External media is blocked. The gateway allows 40 WebSocket connections per source IP, so a shared network can reach that ceiling; heavy-event capacity was not measured.',
      privacy: 'Quiz definitions, nicknames, answers and completed scores are server-readable. Completed records have no automatic expiry. Browser identifiers support reconnection, without visitor analytics. Daily same-VM backups have no configured automatic deletion; they do not preserve running games.',
      next: 'Keep the quiz JSON independently and use non-sensitive nicknames. Ask the operator privately about an authorized results copy or participant-data deletion.',
    },
    es: {
      title: 'Organizá un cuestionario en vivo y conservá sus preguntas',
      intro: 'Los participantes entran a Razzia con un PIN y un apodo. Para organizar se usa una credencial de gestión compartida, controlada por el operador.',
      prerequisites: 'Coordiná el acceso de gestión en privado con el operador. Quienes administran comparten la biblioteca de cuestionarios y resultados: no hay una cuenta separada por organizador. La interfaz nativa no incluye español.',
      steps: ['En Manager, abrí Quizz y creá una definición o importá un JSON. Revisá preguntas, opciones, respuestas correctas y tiempos. Usá nombres ficticios para probar.', 'En Play, elegí el cuestionario y Start game para crear una sala. Entregá su PIN: los participantes abren la página principal y eligen un apodo.', 'Revisá la lista de participantes y comenzá la partida. Usá los controles nativos para mostrar respuestas y terminar la clasificación. Los resultados finales se guardan en el servidor.', 'En Quizz, elegí Export quizz as JSON junto a la definición. Incluye preguntas, soluciones, tiempos, puntuación y URLs de medios; omite resultados de jugadores, credenciales, salas activas y los archivos multimedia.', 'Usá Import quizz from JSON en una instalación compatible para crear una copia y revisá las preguntas. En Results podés ver y borrar resultados; esta versión no ofrece un botón para exportarlos o importarlos.', 'Borrá por separado las definiciones y los resultados con sus controles de papelera. Cerrá sesión al terminar y borrá los datos de este sitio si el dispositivo es compartido. Las descargas y los respaldos existentes son copias separadas.'],
      success: 'Dos salas públicas simultáneas mantuvieron separados participantes y puntuaciones correctas e incorrectas. Pasaron los rechazos de acceso y control de otra sala, JSON nativo, vista y borrado de resultados y una restauración aislada de definiciones y resultados.',
      troubleshooting: 'Reiniciar el servicio pierde las partidas activas. Quienes administran pueden acceder a la biblioteca común. Los medios externos están bloqueados. Se permiten 40 conexiones WebSocket por IP: una red compartida puede llegar al límite. No se midió la capacidad de eventos grandes.',
      privacy: 'El servidor puede leer cuestionarios, apodos, respuestas y puntuaciones finales. Los registros terminados no vencen automáticamente. Los identificadores del navegador permiten reconectarte, sin estadísticas de visitantes. Las copias diarias de esta VM no tienen borrado automático configurado y no conservan partidas activas.',
      next: 'Guardá el JSON por separado y elegí apodos sin datos sensibles. Consultá en privado al operador sobre una copia autorizada de resultados o el borrado de datos de participantes.',
    },
  },
}];
