import type { PracticalGuide } from './practical-guide-data.ts';
export const standaloneGuides: PracticalGuide[] = [
  {
    id: 'one-file-core', paths: { en: 'guides/standalone-diagram', es: 'guias/diagrama-en-un-archivo' }, tools: [{ id: 'one-file-core', label: { en: 'Download The One File Core', es: 'Descargar The One File Core' } }], samples: [], reviewedOn: '2026-10-09',
    copy: {
      en: {
        title: 'Save a diagram together with its editor',
        intro: 'Download The One File Core and open it locally. Its HTML save contains the diagram and editor, so you can reopen the copy without a hosted account.',
        prerequisites: 'Use a current browser that can open and download local HTML. Application controls are in English. Start with fictional information; only import documents you trust. Mobile browsers may hand HTML files to another viewer instead of opening an editable page.',
        steps: ['Choose Download Core on the Utilibre download page. Open the downloaded HTML in your browser and choose Skip or select a mapping mode.', 'Choose + Node, enter a fictional name and choose Add Node. On a narrow screen, open the ☰ menu to find + Node. If the diagram is too small, open Map and use Fit to view.', 'Choose Save HTML. Save the new download under a clear filename. This creates another file; it does not overwrite the website or an earlier download.', 'Open the new HTML in a fresh browser tab and check the nodes and connections before discarding an old copy. Keep an independent backup. JSON, CSV and image exports have different scopes; they are not the HTML round trip checked here.', 'To clear this working diagram, use Settings → Clear All and confirm. Save another copy if you want an empty document. Delete old downloads and independent backups separately.'],
        success: 'Fictional node edits survived an HTML save and independent reopen at desktop and 390-pixel width. Literal </script> text round-tripped after the small serialization correction. Native browser autosave and Clear All were also checked.',
        troubleshooting: 'Creating encrypted HTML is disabled in this build: upstream encrypted saves can leave readable node details in the page. To protect a finished download, encrypt that whole file separately with hat.sh and retain the password. That does not erase browser drafts or old plaintext copies. Existing files may contain a different application version.',
        privacy: 'The editor runs in the downloaded file. IndexedDB autosaves, recovery snapshots and local edit records can remain after closing the tab; file-storage behavior varies by browser. Downloads remain until deleted. Utilibre stores no diagram in this workflow, so it has no diagram to recover or delete. Application downloads create connection metadata; the packaged file blocks external resources and connections.',
        next: 'Keep the tested HTML copy and any encrypted backup separately. Use the portal’s shared whiteboards when you need collaboration; this Core edition has no collaboration server or live network monitoring.',
      },
      es: {
        title: 'Guardá un diagrama junto con su editor',
        intro: 'Descargá The One File Core y abrilo localmente. Su HTML guardado contiene el diagrama y el editor para que podás volver a abrirlo sin una cuenta alojada.',
        prerequisites: 'Usá un navegador actual que pueda abrir y descargar HTML locales. Los controles están en inglés. Empezá con información ficticia e importá solo documentos de confianza. Algunos navegadores móviles entregan el HTML a otro visor en lugar de abrir una página editable.',
        steps: ['Elegí Descargar Core en la página de descarga de Utilibre. Abrí el HTML descargado en tu navegador y elegí Skip o un modo de diagramación.', 'Elegí + Node, ingresá un nombre ficticio y pulsá Add Node. En una pantalla estrecha, abrí el menú ☰ para encontrar + Node. Si el diagrama se ve muy pequeño, abrí Map y usá Fit to view.', 'Elegí Save HTML. Guardá la descarga nueva con un nombre claro. Se crea otro archivo; no se sobrescriben el sitio ni una descarga anterior.', 'Abrí el HTML nuevo en otra pestaña y revisá nodos y conexiones antes de descartar una copia anterior. Conservá un respaldo independiente. Las exportaciones JSON, CSV e imagen tienen otro alcance; no son el recorrido HTML probado acá.', 'Para vaciar este diagrama de trabajo, usá Settings → Clear All y confirmá. Guardá otra copia si querés un documento vacío. Borrá por separado las descargas anteriores y los respaldos independientes.'],
        success: 'Las ediciones de nodos ficticios sobrevivieron al guardado HTML y a una apertura independiente en escritorio y a 390 píxeles. El texto literal </script> se conservó después de la pequeña corrección de serialización. También se comprobaron el autoguardado del navegador y Clear All.',
        troubleshooting: 'Crear HTML cifrado está desactivado en esta compilación: el guardado cifrado original puede dejar detalles legibles de nodos en la página. Para proteger una descarga terminada, cifrá ese archivo completo por separado con hat.sh y conservá la contraseña. Eso no borra borradores del navegador ni copias legibles anteriores. Los archivos existentes pueden contener otra versión de la aplicación.',
        privacy: 'El editor funciona en el archivo descargado. Los borradores IndexedDB, las instantáneas de recuperación y los registros locales de edición pueden quedar al cerrar la pestaña; el almacenamiento de archivos varía según el navegador. Las descargas permanecen hasta que las borrés. Utilibre no guarda diagramas en este recorrido y no tiene uno que recuperar o borrar. Descargar la aplicación genera metadatos de conexión; el archivo distribuido bloquea recursos y conexiones externas.',
        next: 'Conservá por separado el HTML verificado y cualquier respaldo cifrado. Usá las pizarras compartidas del portal si necesitás colaboración; esta edición Core no tiene servidor colaborativo ni monitoreo de redes en vivo.',
      },
    },
  },
  {
    id: 'tiddlywiki', paths: { en: 'guides/single-file-notebook', es: 'guias/cuaderno-en-un-archivo' }, tools: [{ id: 'tiddlywiki', label: { en: 'Download a TiddlyWiki notebook', es: 'Descargar un cuaderno TiddlyWiki' } }], samples: [], reviewedOn: '2026-10-09',
    copy: {
      en: {
        title: 'Keep notes in a single HTML notebook',
        intro: 'Download an English or Spanish TiddlyWiki file, edit it in your browser and save the whole notebook as another HTML file.',
        prerequisites: 'Use a browser with local HTML editing and downloads. Keep a backup before importing notes or plugins, and import only sources you trust: a wiki can contain executable code. This edition has no server account or automatic document-storage service.',
        steps: ['Download the English or Spanish notebook and open that file locally. The Utilibre note explains this edition’s save and network limits.', 'Choose + (new tiddler), give the note a fictional title and type its text. Confirm with the check mark. This updates the open notebook; it has not yet saved a file.', 'Choose Save changes (the cloud/download button). Keep the downloaded HTML. It includes your notes, the bundled editor, language/theme and included notebook configuration; external files referenced only by URL are not made independent copies.', 'Close that tab and open the new HTML. Find your note in the sidebar search if it is not already open. Check important notes and embedded attachments individually before replacing an earlier copy. A full HTML copy opens directly; you do not need a server import.', 'To remove a note, open its edit control and choose Delete this tiddler, then confirm. Save changes again and reopen that new download to check deletion. Delete older HTML files and backups separately if you no longer need their contents.'],
        success: 'Native note creation, HTML download and independent reopen passed in English and Spanish, including the 390-pixel layout. A fictional note was deleted with the native controls, saved and confirmed absent after another independent reopen. No external HTTP requests occurred in the tested local workflows.',
        troubleshooting: 'Closing a tab without downloading can lose edits. This edition has no browser-storage autosave plugin or remote synchronization. External images, services and plugin-library requests are blocked; embedded local images and notes are the supported starting point. Browser mobile file handling varies; a desktop browser is the tested recovery option.',
        privacy: 'Notes stay in the locally opened notebook and its downloaded copies in this workflow. Downloads are not encrypted by default. Native optional password settings can use browser storage; closing the tab does not guarantee all preferences are erased. Deleting one note does not change earlier files or other people’s copies. Utilibre cannot retrieve or delete local notebooks. App delivery creates ordinary connection metadata.',
        next: 'Keep dated independent copies and verify the latest one before deleting an older notebook. Use a compatible TiddlyWiki release and test your plugins separately when upgrading.',
      },
      es: {
        title: 'Conservá notas en un cuaderno HTML',
        intro: 'Descargá un archivo TiddlyWiki en inglés o español, editalo en tu navegador y guardá todo el cuaderno como otro HTML.',
        prerequisites: 'Usá un navegador que permita editar HTML locales y descargarlos. Conservá un respaldo antes de importar notas o complementos e importá solo fuentes de confianza: una wiki puede contener código ejecutable. Esta edición no tiene cuenta en el servidor ni un servicio automático para guardar documentos.',
        steps: ['Descargá el cuaderno en inglés o español y abrí ese archivo localmente. La nota Utilibre explica los límites de guardado y conexiones de esta edición.', 'Elegí + (nuevo tiddler), poné un título ficticio a la nota y escribí su texto. Confirmá con la marca de verificación. Eso actualiza el cuaderno abierto; todavía no guardaste un archivo.', 'Elegí Guardar cambios (el botón de nube y descarga). Conservá el HTML descargado. Incluye tus notas, el editor empaquetado, el idioma, el tema y los ajustes incluidos; no crea copias independientes de archivos externos referenciados solo por URL.', 'Cerrá esa pestaña y abrí el HTML nuevo. Buscá tu nota en el buscador lateral si no está abierta. Revisá por separado las notas y los adjuntos importantes antes de reemplazar una copia anterior. El HTML completo se abre directamente; no necesitás importarlo en un servidor.', 'Para quitar una nota, abrí su control de edición y elegí Eliminar este tiddler; confirmá. Volvé a guardar los cambios y abrí esa descarga nueva para comprobar el borrado. Borrá por separado HTML anteriores y respaldos si ya no necesitás su contenido.'],
        success: 'La creación nativa de notas, la descarga HTML y la apertura independiente pasaron en inglés y español, incluido el diseño a 390 píxeles. Se borró una nota ficticia con los controles nativos, se guardó y se confirmó su ausencia al abrir otra vez el archivo. No hubo solicitudes HTTP externas en los recorridos locales probados.',
        troubleshooting: 'Cerrar una pestaña sin descargar puede perder las ediciones. Esta edición no tiene complemento de autoguardado en almacenamiento del navegador ni sincronización remota. Se bloquean imágenes, servicios y solicitudes a bibliotecas de complementos externos; empezá con notas e imágenes locales incrustadas. El manejo móvil de archivos varía; el navegador de escritorio es la opción de recuperación probada.',
        privacy: 'En este recorrido, las notas quedan en el cuaderno abierto localmente y en sus copias descargadas. Las descargas no están cifradas de forma predeterminada. Los ajustes nativos opcionales de contraseñas pueden usar almacenamiento del navegador; cerrar la pestaña no garantiza que se borren todas las preferencias. Borrar una nota no modifica archivos anteriores ni copias de otras personas. Utilibre no puede recuperar ni borrar cuadernos locales. Descargar la aplicación genera los metadatos habituales de conexión.',
        next: 'Conservá copias independientes con fecha y verificá la más reciente antes de borrar una anterior. Usá una versión compatible de TiddlyWiki y probá tus complementos por separado al actualizar.',
      },
    },
  },
];
