import type { PracticalGuide } from './practical-guide-data.ts';
export const tripGuides: PracticalGuide[] = [{
  id: 'trip', paths: { en: 'guides/trip-backup', es: 'guias/respaldar-viajes-trip' }, tools: [{ id: 'trip', label: { en: 'Open TRIP', es: 'Abrir TRIP' } }], samples: [], reviewedOn: '2026-10-09',
  copy: {
    en: {
      title: 'Keep an independent copy of a TRIP travel plan',
      intro: 'TRIP stores travel plans on the server and can create a native ZIP backup. Public HTTPS sign-in, trip creation and maps were checked with fictional data. These instructions describe the installed release; account access is operator-provisioned.',
      prerequisites: 'Use an approved Utilibre account with permission for TRIP. Try a fictional trip first. Native controls are in English and several other upstream languages, but this release has no Spanish interface. Search and routing use external providers. OpenStreetMap’s service terms set a minimum age of 13.',
      steps: [
        'Sign in through Utilibre. Create a trip, add a place and upload a small fictional PDF. A different signed-in account cannot read your private trip or its PDFs. To collaborate, invite the intended username; that person accepts the invitation. Review members and any separate public sharing settings.',
        'Open Settings with the gear control, choose Data, and find Backups. Use the plus button to create a backup. Wait for Completed, refreshing the list with its circular-arrow button if necessary. Use the download-arrow button on that backup to save its ZIP outside the browser.',
        'The ZIP contains data.json, your categories and places, content of trips you own, and your uploaded images and PDFs. Trips owned by someone else are omitted even if you are a member. Files uploaded by another collaborator are not covered by the own-upload rule. Do not assume membership, sharing permissions, every setting, account credentials or a complete edit history will migrate. Save needed shared files separately with permission.',
        'To restore into a compatible TRIP installation, open Settings → Data → Backups, use the upload-arrow button and select the ZIP. Import creates new trip and place identifiers and can merge categories with matching names. Test it in an empty account first. The fictional check restored the trip, place, image and byte-identical PDF to the receiving account; the original account did not gain access to that imported copy.',
        'Use an item’s native Delete control to remove it. Remove a generated backup separately with its trash button. For a whole account, contact Utilibre privately: a native administrator deletes the TRIP account and removes its service-access grant. The tested account deletion removed its active trip, place, image and PDF files. Deleting this app account is separate from deleting your Utilibre identity.',
        'Keep downloads protected. Deleting active content does not erase earlier operator backups, other people’s downloaded copies or copies you deliberately imported elsewhere. Sign out of both TRIP and Utilibre on a shared device; closing a tab does not clear saved login state.',
      ],
      success: 'Two fictional accounts passed native MFA/OIDC sign-in, private account separation, collaboration, PDF access restrictions, ZIP export/import and deletion. A native administrator backup restored the database, image and exact PDF in a disconnected disposable installation. These tests used fictional content, not real travel records.',
      troubleshooting: 'Each PDF is limited to 2 MiB. Upload requests are limited to 10 MiB; backup imports allow 8 MiB per uncompressed entry and 32 MiB in total. Storage is bounded across the installation, not a promised per-account quota. Search and routing share 30 requests/minute across users. Wait after a rate-limit response. Photon does not support this app’s nearby search. Remote image downloads, link previews, Google API integration and external notifications are disabled.',
      privacy: 'Trip data is readable to the operator. Uploaded image URLs work without login for anyone holding the link; they are not authenticated PDF attachments. OpenStreetMap and its Fastly CDN receive your browser’s tile requests and connection metadata; the provider uses logs and aggregate statistics. Photon receives search text through the server; FOSSGIS receives route coordinates and states that it logs requests. Exact deletion periods for OSMF tile logs, Photon queries and FOSSGIS route logs remain unverified. The public hostname uses Cloudflare as an HTTPS proxy; it can process ordinary HTTP content and connection metadata. Its applicable retention has not been verified. The outbound proxy resolves provider hostnames through Cloudflare and Quad9 DNS. Navigation deliberately opens Google Maps with the selected coordinates. Login tokens, preferences and app caches can survive tab closure. Daily on-host backups have no automatic pruning and share the application’s physical-host failure risk.',
      next: 'Use the native ZIP for content you own, keep separate copies of needed shared files and review restored contents before relying on them. Do not put confidential information into external map searches.',
    },
    es: {
      title: 'Conservá una copia independiente de un viaje en TRIP',
      intro: 'TRIP guarda los planes de viaje en el servidor y puede crear un respaldo ZIP nativo. El acceso público por HTTPS, la creación de viajes y los mapas se verificaron con datos ficticios. Estas instrucciones describen la versión instalada; el operador habilita el acceso a las cuentas.',
      prerequisites: 'Usá una cuenta aprobada de Utilibre con permiso para TRIP. Probá primero con un viaje ficticio. Los controles nativos están en inglés y otros idiomas originales, pero esta versión no tiene interfaz en español. Las búsquedas y rutas usan proveedores externos. Las condiciones de servicio de OpenStreetMap establecen una edad mínima de 13 años.',
      steps: [
        'Iniciá sesión mediante Utilibre. Creá un viaje, agregá un lugar y subí un PDF ficticio pequeño. Otra cuenta con sesión no puede leer tu viaje privado ni sus PDF. Para colaborar, invitá el nombre de usuario correcto; esa persona acepta la invitación. Revisá quiénes participan y los ajustes separados para compartir públicamente.',
        'Abrí Settings con el engranaje, elegí Data y buscá Backups. Usá el botón de suma para crear un respaldo. Esperá a Completed y, si hace falta, actualizá la lista con el botón de flecha circular. Usá la flecha de descarga de ese respaldo para guardar el ZIP fuera del navegador.',
        'El ZIP contiene data.json, tus categorías y lugares, el contenido de los viajes que te pertenecen y las imágenes y PDF que subiste. Omite los viajes de otra persona aunque participés en ellos. La regla de archivos propios no cubre las cargas de otra persona colaboradora. No supongás que migran las membresías, permisos para compartir, todos los ajustes, credenciales o un historial completo de cambios. Guardá aparte los archivos compartidos que necesités y para los que tengás permiso.',
        'Para restaurar en una instalación compatible de TRIP, abrí Settings → Data → Backups, usá la flecha de carga y seleccioná el ZIP. La importación crea identificadores nuevos para viajes y lugares, y puede combinar categorías con el mismo nombre. Probala primero en una cuenta vacía. La prueba ficticia restauró el viaje, lugar, imagen y PDF idéntico en la cuenta receptora; la cuenta original no obtuvo acceso a esa copia importada.',
        'Usá Delete en un elemento para borrarlo. Borrá aparte un respaldo generado con su papelera. Para eliminar toda la cuenta, contactá a Utilibre en privado: la administración elimina la cuenta nativa de TRIP y le quita el permiso de acceso al servicio. La prueba de borrado eliminó sus viajes, lugares, imágenes y PDF activos. Borrar la cuenta de esta aplicación es distinto de borrar tu identidad de Utilibre.',
        'Protegé las descargas. Borrar contenido activo no elimina respaldos anteriores del operador, copias descargadas por otras personas ni copias que importaste deliberadamente en otro lugar. Cerrá sesión tanto en TRIP como en Utilibre si compartís el dispositivo; cerrar la pestaña no borra el acceso guardado.',
      ],
      success: 'Dos cuentas ficticias completaron acceso nativo con MFA/OIDC, separación de cuentas, colaboración, restricciones de PDF, exportación e importación ZIP y borrado. Un respaldo administrativo nativo restauró la base, imagen y PDF idéntico en una instalación desechable sin red. Las pruebas usaron contenido ficticio, no registros de viajes reales.',
      troubleshooting: 'Cada PDF puede pesar hasta 2 MiB. Las solicitudes de carga tienen un límite de 10 MiB; los respaldos importados admiten 8 MiB por entrada sin comprimir y 32 MiB en total. El almacenamiento está limitado para toda la instalación; no es una cuota prometida por cuenta. Las búsquedas y rutas comparten 30 solicitudes por minuto entre usuarios. Esperá si recibís una respuesta de límite. Photon no admite la búsqueda cercana de esta aplicación. Las descargas de imágenes remotas, vistas previas de enlaces, integración de la API de Google y notificaciones externas están desactivadas.',
      privacy: 'El operador puede leer los datos del viaje. Cualquiera que tenga la URL de una imagen subida puede abrirla sin sesión; no es un adjunto PDF autenticado. OpenStreetMap y su CDN Fastly reciben las solicitudes de mapas y los metadatos de conexión de tu navegador; el proveedor usa registros y estadísticas agregadas. Photon recibe el texto de búsqueda desde el servidor; FOSSGIS recibe las coordenadas de ruta y declara que registra las solicitudes. Siguen sin verificarse los plazos exactos de borrado de registros de mapas OSMF, consultas Photon y rutas FOSSGIS. El dominio público usa Cloudflare como intermediario HTTPS; puede procesar contenido HTTP común y metadatos de conexión. No se verificó su conservación aplicable. El intermediario de salida resuelve los dominios de los proveedores con los DNS de Cloudflare y Quad9. La navegación abre Google Maps deliberadamente con las coordenadas seleccionadas. Los tokens, preferencias y cachés pueden persistir al cerrar la pestaña. Los respaldos diarios en esta VM no tienen purga automática y comparten el riesgo de falla del servidor físico.',
      next: 'Usá el ZIP nativo para tu contenido, guardá por separado los archivos compartidos necesarios y revisá lo restaurado antes de depender de ello. No incluyás información confidencial en búsquedas de mapas externas.',
    },
  },
}];
