import { catalogEntry } from '../catalog/catalog';
import { practicalGuides, practicalGuidePath } from './practical-guide-data';
import type { Language } from '../i18n';
import { routePath } from '../routes';
import { element, type Translate } from '../utilities/dom';

type GuideCopy = { stored: string; steps: string[]; scope: string; reopen: string; deletion: string; checked: string };
type DataGuide = { id: string; name: string; version: string; source: string; copy: Record<Language, GuideCopy> };

// Native application procedures, checked against the installed releases. This is
// presentation data, not an export service or a second application inventory.
const guides: DataGuide[] = [
  { id: 'reactive-resume', name: 'Reactive Resume', version: '6.0.0', source: 'https://github.com/reactive-resume/reactive-resume/blob/bc71f636c02a80ac6d731e17d2ee13501275295c/docs/guides/exporting-your-data.mdx', copy: {
    en: { stored: 'The server stores your account, resumes, cover letters, job-application records and uploaded images. These documents are readable by the service; a private sharing setting is access control, not end-to-end encryption. New view/download analytics were disabled on 8 October 2026. Earlier aggregate counters may remain in live data or backups; this update did not erase them.', steps: ['Select your name at the bottom of the sidebar → Settings → Account → Your data. Beside Export everything, select Export to download the account ZIP.', 'For one resume, open Share & export → Download and choose JSON for an editable backup. Download PDF is a presentation copy; it is not a complete editable backup.'], scope: 'The account ZIP contains account.json, applications.json, and individual resume/letter JSON files, including trashed resumes. It omits passwords, passkeys, verification secrets, API keys and AI-provider keys. Uploaded images are referenced by URL, not included as image files. Individual JSON can contain private notes and hidden entries; do not send that backup to a recruiter as though it were the visible PDF.', reopen: 'Extract the ZIP. On Documents, choose New → Import a resume and select an individual resume or letter JSON. Import creates a new document; the whole ZIP is not a bulk-import file. Account settings, public-sharing settings and application links are not restored by document import. Keep independent image files where needed. Import fidelity for an entire account has not been tested here.', deletion: 'Move a document to Trash from its menu, then use Trash → its menu → Delete now to purge it. For account deletion, use Settings → Account → Your data → Delete account, review what will be removed, type delete and confirm. Revoke any API keys and public links you no longer need. Removing this app account does not itself retire your separate Utilibre identity; recipient downloads and earlier backups remain separate.', checked: 'On 9 October 2026, an isolated copy of the installed image downloaded a native account ZIP with fictional account data and one resume. Importing its extracted resume JSON into a second account preserved content and design, started private, and passed edit/save/reload and access checks. Native account deletion rejected the old sessions. Whole-ZIP import displayed extraction guidance. Letters, nonempty job applications, image files and complete account migration were not tested. Earlier JSON/PDF and Trash/purge checks remain separate.' },
    es: { stored: 'El servidor guarda tu cuenta, currículos, cartas, registros de postulaciones e imágenes subidas. El servicio puede leer esos documentos; compartir en privado es un control de acceso, no cifrado de extremo a extremo. La nueva recopilación de estadísticas de visitas y descargas se desactivó el 8 de octubre de 2026. Pueden quedar contadores agregados anteriores en los datos activos o los respaldos; esta actualización no los borró.', steps: ['Elegí tu nombre al pie de la barra lateral → Settings → Account → Your data. Junto a Export everything, elegí Export para descargar el ZIP de la cuenta.', 'Para un currículo, abrí Share & export → Download y elegí JSON como respaldo editable. Download PDF genera una copia de presentación; no es un respaldo editable completo.'], scope: 'El ZIP contiene account.json, applications.json y archivos JSON individuales de currículos y cartas, incluidos los currículos de la papelera. Omite contraseñas, claves de acceso, secretos de verificación, claves de API y de proveedores de IA. Las imágenes subidas aparecen como direcciones, no como archivos de imagen. Un JSON individual puede incluir notas privadas y entradas ocultas; no mandés ese respaldo a un reclutador como si fuera el PDF visible.', reopen: 'Extraé el ZIP. En Documents, elegí New → Import a resume y seleccioná el JSON individual de un currículo o carta. La importación crea otro documento; el ZIP completo no es un archivo de importación masiva. Importar un documento no restaura ajustes de cuenta, de publicación ni enlaces con postulaciones. Conservá por separado las imágenes que necesités. No se probó acá la fidelidad de una importación de toda la cuenta.', deletion: 'Mové el documento a Trash desde su menú y usá Trash → su menú → Delete now para eliminarlo. Para la cuenta, usá Settings → Account → Your data → Delete account, revisá qué se borrará, escribí delete y confirmá. Revocá las claves de API y enlaces públicos que ya no necesités. Borrar esta cuenta no retira por sí solo tu identidad separada de Utilibre; las descargas de destinatarios y respaldos anteriores son distintos.', checked: 'El 9 de octubre de 2026, una copia aislada de la imagen instalada descargó el ZIP nativo con datos ficticios de cuenta y un currículo. Importar su JSON extraído a otra cuenta conservó el contenido y el diseño, inició el documento como privado y pasó las pruebas de edición, guardado, recarga y acceso. El borrado nativo de cuentas rechazó las sesiones anteriores. Importar el ZIP completo mostró instrucciones para extraerlo. No se probaron cartas, postulaciones con datos, archivos de imagen ni la migración completa de cuenta. Las pruebas anteriores de JSON/PDF y papelera siguen siendo comprobaciones separadas.' },
  } },
  { id: 'penpot', name: 'Penpot', version: '2.18.2', source: 'https://github.com/penpot/penpot/tree/cf46b53bcb61c2a9be8f202bec03647a5470d43d/frontend/src/app/main/ui/exports', copy: {
    en: { stored: 'The server stores design files, assets, teams, permissions and account data. The service can read designs; team membership and sharing links control access.', steps: ['Open the design file’s menu and choose Download Penpot file (.penpot), or select files on the dashboard and use their download menu.', 'If shared libraries are used, choose deliberately between Export shared libraries, Include shared library assets in file libraries, and Treat shared library assets as basic objects. Download the resulting native files. Exporting selected shapes as SVG/PNG/PDF is a separate visual export, not the whole editable design.'], scope: 'The native file export carries editable design data and the assets/libraries selected by its export options. It is not an account/team backup: do not assume membership, permissions, sharing links, comments, version history, integrations or every uploaded font migrate. Keep required licensed font files separately and inspect dependencies.', reopen: 'On a compatible Penpot installation, open the destination project and choose Import Penpot files, then select the .penpot file (the importer also accepts supported legacy ZIP files). Check pages, components, linked libraries, images and fonts. An isolated test on the installed 2.18.2 release exported a fictional design, imported it into a second account and reopened its editable rectangle. Shared-library migration and other dependencies still need your own checks.', deletion: 'Use the file’s menu → Delete for designs you control; inspect the Deleted area and its permanent-deletion controls if you want to remove a recoverable file. Remove public sharing links and team access separately. Account settings → Profile offers Want to remove your account?; review the confirmation and transfer needed team ownership before proceeding. Deleting or leaving a shared team can affect others, and cannot recall their downloads. Revoke personal access tokens/integrations when leaving.', checked: 'On 9 October 2026, an isolated test passed native .penpot export/import, preserved a fictional rectangle’s name, position, dimensions and fill, and saved a browser edit that survived reload. The other account could not access the imported copy. Native API file deletion passed. Download/import labels and account-deletion controls were source-reviewed. Shared libraries, images, fonts, history and team migration were not tested.' },
    es: { stored: 'El servidor guarda diseños, recursos, equipos, permisos y datos de cuenta. El servicio puede leer los diseños; los integrantes del equipo y los enlaces compartidos determinan el acceso.', steps: ['Abrí el menú del archivo y elegí Download Penpot file (.penpot), o seleccioná archivos en el panel y usá su menú de descarga.', 'Si usás bibliotecas compartidas, elegí entre Export shared libraries, Include shared library assets in file libraries y Treat shared library assets as basic objects según lo que necesités conservar. Descargá los archivos nativos. Exportar formas como SVG/PNG/PDF es una exportación visual distinta, no todo el diseño editable.'], scope: 'El archivo nativo incluye el diseño editable y los recursos o bibliotecas seleccionados en la exportación. No es un respaldo de cuenta ni equipo: no supongás que migren integrantes, permisos, enlaces, comentarios, historial, integraciones ni todas las fuentes subidas. Conservá por separado las fuentes necesarias con su licencia y revisá las dependencias.', reopen: 'En una instalación compatible de Penpot, abrí el proyecto de destino y elegí Import Penpot files; seleccioná el archivo .penpot. El importador también acepta formatos ZIP antiguos compatibles. Revisá páginas, componentes, bibliotecas vinculadas, imágenes y fuentes. Una prueba aislada con la versión instalada 2.18.2 exportó un diseño ficticio, lo importó en otra cuenta y volvió a abrir su rectángulo editable. La migración de bibliotecas compartidas y otras dependencias todavía requiere tus propias comprobaciones.', deletion: 'Usá el menú del archivo → Delete para diseños que controlás; revisá Deleted y sus controles de borrado permanente si querés quitar un archivo recuperable. Retirá por separado enlaces públicos y accesos de equipo. En los ajustes de cuenta → Profile aparece Want to remove your account?; revisá la confirmación y transferí primero la propiedad de equipos que deban continuar. Borrar o abandonar un equipo puede afectar a otras personas y no recupera sus descargas. Revocá los tokens personales e integraciones al marcharte.', checked: 'El 9 de octubre de 2026, una prueba aislada pasó la exportación e importación nativas de .penpot: conservó el nombre, la posición, las dimensiones y el color de un rectángulo ficticio, y guardó un cambio desde el navegador que persistió al recargar. La otra cuenta no pudo acceder a la copia importada. Pasó el borrado de archivos por la API nativa. Las etiquetas de descarga e importación y los controles de borrado de cuenta se revisaron en el código. No se probaron bibliotecas compartidas, imágenes, fuentes, historial ni migración de equipos.' },
  } },

  { id: 'freshrss', name: 'FreshRSS', version: '1.29.1', source: 'https://freshrss.github.io/FreshRSS/en/users/04_Subscriptions.html', copy: {
    en: { stored: 'Subscriptions, categories, fetched articles, favourites, labels and reading state are stored on the server.', steps: ['Open Subscription management → Import / export.', 'Under Export, select the OPML feed list. Separately select starred articles, labelled articles and any feeds whose stored articles you want. Choose Export and save the download. The web export includes at most 50 articles per selected feed. Starred and labelled selections are separate; choose them too if needed. Multiple selections can be packaged as a ZIP.'], scope: 'OPML contains subscriptions and their categories, not article archives or read/unread state. Article JSON exports contain the selected stored articles and their available state/labels; they are separate from OPML. These files are not a complete account backup: passwords, API credentials and every preference are not included.', reopen: 'Import OPML into a compatible feed reader. FreshRSS Import / export accepts its supported OPML, article JSON and ZIP formats. Native article JSON and ZIP imports preserved the checked text, read/unread state, favourites and labels in independent fictional accounts. The 50-article web limit can leave ordinary articles out even when the ZIP also contains favourites and labelled articles. For a larger retained archive, contact the operator; the native command-line exporter has a separate per-feed limit and is not a web control.', deletion: 'Remove a subscription through Subscription management. A non-administrator can delete their account under Settings → Profile, using their password and the deletion confirmation. Revoke any API/app password when retiring clients. Deleting an account does not remove articles from their original publishers or copies already exported.', checked: 'OPML export/import passed on 8 October 2026. On 9 October, a 53-article fixture exported 50 through the feed selection, five through favourites/labels, and 52 distinct articles through their combined ZIP. Independent imports preserved the checked content and state; repeat import created no duplicates. The operator-only export with a 100-per-feed limit included all 53 fixture articles. Account preferences and other readers were not tested.' },
    es: { stored: 'El servidor guarda suscripciones, categorías, artículos descargados, favoritos, etiquetas y estado de lectura.', steps: ['Abrí Gestión de suscripciones → Importar / exportar.', 'En Exportar, seleccioná la lista de fuentes OPML. Seleccioná por separado artículos favoritos, artículos etiquetados y las fuentes cuyos artículos guardados querás conservar. Elegí Exportar y guardá la descarga. La exportación web incluye como máximo 50 artículos por fuente seleccionada. Los favoritos y etiquetados se eligen por separado; seleccionalos también si los necesitás. Varias selecciones pueden agruparse en un ZIP.'], scope: 'El OPML contiene suscripciones y categorías; no incluye archivos de artículos ni su estado leído/no leído. Las exportaciones JSON contienen los artículos seleccionados y su estado y etiquetas disponibles, por separado del OPML. No son un respaldo completo de la cuenta: no incluyen contraseñas, credenciales de API ni todas las preferencias.', reopen: 'Importá el OPML en un lector compatible. Importar / exportar de FreshRSS admite sus formatos OPML, JSON de artículos y ZIP. Las importaciones nativas de JSON y ZIP conservaron el texto, el estado leído/no leído, los favoritos y las etiquetas comprobados en cuentas ficticias independientes. El límite web de 50 artículos puede dejar fuera artículos comunes aunque el ZIP también incluya favoritos y etiquetados. Para obtener un archivo más amplio de los artículos retenidos, contactá al operador; la exportación nativa por línea de comandos tiene otro límite por fuente y no es un control web.', deletion: 'Quitá una suscripción desde Gestión de suscripciones. Una cuenta sin privilegios de administración puede borrarse desde Configuración → Perfil, con contraseña y confirmación. Revocá las contraseñas de API o aplicaciones cuando retirés clientes. Borrar la cuenta no elimina artículos de sus sitios originales ni las copias ya exportadas.', checked: 'La exportación e importación OPML pasó el 8 de octubre de 2026. El 9 de octubre, una prueba con 53 artículos exportó 50 desde la selección de fuente, cinco desde favoritos y etiquetas, y 52 artículos distintos en el ZIP combinado. Las importaciones independientes conservaron el contenido y estado comprobados; repetir la importación no creó duplicados. La exportación del operador con un límite de 100 por fuente incluyó los 53 artículos ficticios. No se probaron preferencias de cuenta ni otros lectores.' },
  } },
  { id: 'cryptpad', name: 'CryptPad', version: '2026.9.0', source: 'https://docs.cryptpad.org/en/user_guide/user_account.html', copy: {
    en: { stored: 'The server retains encrypted documents, the encrypted drive and functional account/storage metadata. Your browser and document links hold access keys.', steps: ['To keep an independent copy of your documents, download their contents. A backup containing only document-access keys still depends on the server retaining those documents.', 'Open Settings → CryptDrive. Backup downloads the drive structure and access keys as JSON. Restore imports that key/drive backup; it does not recreate deleted server documents.', 'Choose Download my CryptDrive to download document contents as a ZIP. Keep the tab open, inspect the export errors and check the files. For an individual document, use its File → Export; formats depend on the editor.'], scope: 'The ZIP uses ordinary document formats when supported and CryptPad-specific formats otherwise. An unavailable, invalid or timed-out document can be omitted and reported as an error. The tested personal ZIP did not include the team document. Export team material separately: open Teams, choose the team, then Administration → Download and confirm, where your role permits it. Do not assume these files preserve document history, permissions, account settings or every shared folder.', reopen: 'Open ordinary exported files in compatible local applications, or use the matching CryptPad editor’s Import function for supported formats. Test important files individually. A restored document-key backup is still dependent on the original server and documents; it is not a portable content archive.', deletion: 'Removing a document from your drive is different from destroying an owned document. Use the document’s Access/ownership controls before deletion, and review collaborators and sharing links. Settings → Account → Delete your account removes the account/drive; documents still retained by others can remain. This instance uses 90 days of inactivity before archiving unretained documents and a further 15-day archive window; deletion is not instant erasure of every copy. Inactive-account eviction is configured at 365 days. Recipients can keep exports and keys.', checked: 'On 9 October 2026, an isolated native test exported personal Markdown, Rich Text HTML and a small uploaded text file. The HTML reopened; Markdown imported into a second account and survived reload. The keys JSON contained no document bodies. The personal ZIP omitted the test team’s document; the owner’s separate team ZIP contained it. Native invitation acceptance passed. The 8 October owned-document/account deletion and earlier office/recovery checks remain separate. Full drive/account migration, images, history, permissions and all editor types were not tested.' },
    es: { stored: 'El servidor conserva documentos cifrados, la unidad cifrada y metadatos funcionales de cuenta y almacenamiento. Tu navegador y los enlaces de documentos contienen claves de acceso.', steps: ['Para conservar una copia independiente de tus documentos, descargá su contenido. Una copia que solo contiene las claves de acceso sigue dependiendo de que el servidor conserve esos documentos.', 'Abrí Configuración → CryptDrive. Backup descarga en JSON la estructura de la unidad y las claves de acceso. Restore importa ese respaldo de claves y unidad; no vuelve a crear documentos borrados del servidor.', 'Elegí Download my CryptDrive para descargar el contenido en ZIP. Dejá abierta la pestaña, revisá los errores de exportación y comprobá los archivos. Para un documento individual, usá File → Export; los formatos dependen del editor.'], scope: 'El ZIP usa formatos de documentos comunes cuando están disponibles y formatos propios de CryptPad en los demás casos. Un documento ausente, inválido o que tarde demasiado puede quedar fuera y aparecer como error. El ZIP personal probado no incluyó el documento del equipo. Exportá ese material por separado: abrí Teams, elegí el equipo y usá Administration → Download y su confirmación, cuando tu rol lo permita. No supongás que estos archivos conserven historial, permisos, ajustes de cuenta ni todas las carpetas compartidas.', reopen: 'Abrí los formatos comunes en aplicaciones locales compatibles o usá Import en el editor correspondiente de CryptPad. Probá individualmente los archivos importantes. Restaurar un respaldo de claves sigue dependiendo del servidor y de los documentos originales; no es un archivo portátil de su contenido.', deletion: 'Quitar un documento de tu unidad es distinto de destruir un documento propio. Revisá Access, la propiedad, los colaboradores y los enlaces antes de borrarlo. Configuración → Cuenta → Delete your account elimina la cuenta y la unidad; los documentos conservados por otras personas pueden permanecer. Esta instancia archiva documentos sin retención tras 90 días de inactividad y conserva el archivo durante otros 15 días; borrar no elimina instantáneamente todas las copias. La eliminación de cuentas inactivas está configurada a 365 días. Los destinatarios pueden conservar exportaciones y claves.', checked: 'El 9 de octubre de 2026, una prueba nativa aislada exportó Markdown personal, HTML de texto enriquecido y un archivo de texto pequeño subido. El HTML volvió a abrirse; Markdown se importó en otra cuenta y persistió al recargar. El JSON de claves no contenía los documentos. El ZIP personal omitió el documento del equipo; el ZIP separado de su propietario sí lo incluyó. Pasó la aceptación nativa de la invitación. El borrado de documento y cuenta del 8 de octubre y las pruebas anteriores de oficina y recuperación son comprobaciones separadas. No se probaron migraciones completas de unidad o cuenta, imágenes, historial, permisos ni todos los editores.' },
  } },
  { id: 'actual', name: 'Actual Budget', version: '26.10.0', source: 'https://actualbudget.org/docs/backup-restore/restore/', copy: {
    en: { stored: 'Budget data lives in browser/local storage and, when synchronized, in the server’s budget files. Account and synchronization metadata are separate.', steps: ['Open the budget. Open the budget-name menu → Settings.', 'In Export, choose Export data and save the ZIP. Keep the original export unchanged while testing a copy.'], scope: 'The ZIP is a native budget export containing the budget database and metadata, not a backup of your Utilibre login or every server setting. Treat it as readable sensitive financial data. Remote synchronization encryption does not automatically protect downloaded ZIPs or all local data.', reopen: 'On a compatible Actual installation, close the current budget and choose Import file from the Files screen, choose Actual → Select file and select the ZIP. Check account balances, transactions and categories before relying on it. Compatibility depends on the Actual release and its migrations; do not assume any version can open any export.', deletion: 'From the Files screen, use the budget’s menu and Delete, reading whether the confirmation removes the local copy, the server copy or both. Remove retained browser data and downloaded files separately. Shared users may have their own copies. Contact the operator to retire your invited service account and revoke its sessions; deleting a budget alone does not revoke your Utilibre account.', checked: 'Native ZIP export and import into the installed 26.10.0 release passed on 8 October 2026: the fictional cash account and its 123.45 starting balance survived. This checks one small budget, not every bank integration or historical-version migration.' },
    es: { stored: 'El presupuesto se guarda en el navegador o dispositivo y, al sincronizarse, en archivos del servidor. Los metadatos de cuenta y sincronización son distintos.', steps: ['Abrí el presupuesto y el menú con su nombre → Settings.', 'En Export, elegí Export data y guardá el ZIP. Conservá intacta la exportación original mientras probás una copia.'], scope: 'El ZIP es una exportación nativa del presupuesto, con su base de datos y metadatos; no respalda tu acceso a Utilibre ni todos los ajustes del servidor. Tratá la descarga como información financiera sensible y legible. El cifrado de sincronización remota no protege automáticamente los ZIP descargados ni todos los datos locales.', reopen: 'En una instalación compatible de Actual, cerrá el presupuesto actual y elegí Import file en la pantalla Files, Actual → Select file y seleccioná el ZIP. Revisá saldos, movimientos y categorías antes de depender de esa copia. La compatibilidad depende de la versión de Actual y sus migraciones; no supongás que cualquier versión abre cualquier exportación.', deletion: 'En Files, usá el menú del presupuesto y Delete. Leé si la confirmación elimina la copia local, la del servidor o ambas. Borrá por separado los datos retenidos en el navegador y las descargas. Otros usuarios pueden conservar copias. Contactá al operador para retirar tu cuenta invitada y revocar sesiones; borrar un presupuesto no revoca tu cuenta de Utilibre.', checked: 'La exportación ZIP y su importación en la versión instalada 26.10.0 pasaron el 8 de octubre de 2026: conservaron la cuenta ficticia de efectivo y su saldo inicial de 123.45. La prueba cubre un presupuesto pequeño, no todas las integraciones bancarias ni migraciones de versiones antiguas.' },
  } },
  { id: 'wakapi', name: 'Wakapi', version: '2.18.1', source: 'https://github.com/muety/wakapi/tree/347f1f45ae2863d9499236471317a76630c5308f/scripts', copy: {
    en: { stored: 'The server stores the coding heartbeats you deliberately send, including project/file metadata, and derived activity summaries. Scheduled cleanup is configured to remove heartbeats, durations and summaries older than three months; it is not an instantaneous deletion deadline.', steps: ['Use the upstream download_heartbeats.py script from the installed release; there is no equivalent CSV export button in this web interface.', 'Set its URL to https://wakapi.utilibre.org/api, provide your API key privately, select the from/to dates in YYYY-MM-DD form, and choose an output filename with the script’s --output option. Follow its --help for the exact arguments. Do not post the key in a support issue or retain it in shared terminal history.'], scope: 'The CSV contains available raw heartbeat rows: time, project, file/entity, language, branch, category and related coding/device metadata. It is not a complete export of aggregates, aliases, preferences or credentials. Raw records already removed by retention cannot be recreated from this export.', reopen: 'Read the CSV in a spreadsheet or analysis tool. The release also supplies upload_heartbeats.py for a compatible API. The test exported one recent fictional heartbeat and imported it into a second disposable account, using pandas 2.3.3. Older timestamps can be rejected by the destination’s maximum-age policy; the test does not establish that three months of history can be imported.', deletion: 'Stop the editor plugin from sending data, revoke/rotate its API key in Settings, and use Settings → Delete account when leaving. Remove any separately published activity shares and exported files. The public leaderboard and external importer are disabled here; do not enable sharing if you want activity to remain restricted.', checked: 'Native CSV export and API import of one current fictional heartbeat passed on 8 October 2026. The upstream upload script failed with pandas 3 in the isolated test environment and passed with pandas 2.3.3.' },
    es: { stored: 'El servidor guarda los registros de actividad de programación que decidís enviar, incluidos metadatos de proyectos y archivos, y resúmenes derivados. La limpieza programada elimina registros originales, duraciones y resúmenes de más de tres meses según la configuración; no es un plazo de borrado instantáneo.', steps: ['Usá download_heartbeats.py del proyecto original y de la versión instalada; esta interfaz web no tiene un botón equivalente para exportar CSV.', 'Indicá https://wakapi.utilibre.org/api como URL, proporcioná tu clave de API en privado, elegí las fechas from/to con formato YYYY-MM-DD y el archivo de salida con --output. Consultá --help para los argumentos exactos. No publiqués la clave en una consulta de soporte ni la dejés en un historial de terminal compartido.'], scope: 'El CSV contiene los registros originales disponibles: hora, proyecto, archivo, lenguaje, rama, categoría y metadatos relacionados de programación y dispositivo. No exporta todos los resúmenes, alias, preferencias ni credenciales. No recupera registros originales que ya se borraron por retención.', reopen: 'Abrí el CSV en una hoja de cálculo o herramienta de análisis. La versión también incluye upload_heartbeats.py para una API compatible. La prueba exportó un registro ficticio reciente y lo importó en otra cuenta descartable con pandas 2.3.3. El destino puede rechazar fechas antiguas según su límite de antigüedad; la prueba no demuestra que se puedan importar tres meses de historial.', deletion: 'Detené los envíos del complemento de tu editor, revocá o renová su clave de API en Settings y usá Settings → Delete account si dejás el servicio. Retirá las publicaciones de actividad y borrá las exportaciones por separado. Acá están desactivados la clasificación pública y el importador externo; no habilités opciones de compartir si querés mantener restringida tu actividad.', checked: 'La exportación CSV y la importación por API de un registro ficticio actual pasaron el 8 de octubre de 2026. El script original de importación falló con pandas 3 en el entorno aislado de prueba y funcionó con pandas 2.3.3.' },
  } },
  { id: 'rallly', name: 'Rallly', version: '4.15.4', source: 'https://github.com/lukevella/rallly/releases/tag/v4.15.4', copy: {
    en: { stored: 'Poll definitions, proposed dates, participants, votes, comments and organizer/account metadata are stored on the server.', steps: ['Sign in as an authorized organizer and open your poll.', 'Open Manage → Export to CSV. Save and inspect the CSV before deleting the poll.'], scope: 'The native CSV lists participant names, available email addresses, response timestamps and votes for the date/time options. It is not a complete poll backup: comments, permissions, organizer settings and account data are not included. CSV export is separate from paid/licensed duplication or scheduling features.', reopen: 'Open the CSV in a compatible spreadsheet and check the displayed timezone and columns. A native CSV-to-poll restore is not offered by the reviewed exporter; recreate a poll manually when needed. No full poll migration is claimed.', deletion: 'Use the organizer’s poll menu → Delete and confirm the correct poll. Closing a poll merely stops voting. Remove collaborators and revoke shared management access where available; downloaded participant lists cannot be recalled. Contact the operator for invited-account retirement.', checked: 'On 9 October 2026, an isolated copy of the installed release downloaded a native organizer CSV with two fictional participants. Names, available email, localized response times and Yes/No/If need be votes matched; participant tokens, description and venue were absent. Anonymous visitors could not open management or its export menu. Publicly visible votes can still be copied. No CSV import or complete poll migration was tested.' },
    es: { stored: 'El servidor guarda definiciones de encuestas, fechas propuestas, participantes, votos, comentarios y metadatos de organización y cuenta.', steps: ['Entrá como organizador autorizado y abrí tu encuesta.', 'Abrí Manage → Export to CSV. Guardá y revisá el CSV antes de borrar la encuesta.'], scope: 'El CSV nativo incluye nombres, correos disponibles, fechas de respuesta y votos para las opciones de fecha y hora. No es un respaldo completo: omite comentarios, permisos, ajustes del organizador y datos de cuenta. La exportación CSV es distinta de las funciones de duplicación o programación sujetas a licencia.', reopen: 'Abrí el CSV en una hoja de cálculo compatible y revisá la zona horaria y las columnas. El exportador revisado no ofrece restaurar una encuesta desde CSV; recreala manualmente si hace falta. No se promete una migración completa.', deletion: 'Usá el menú del organizador → Delete y confirmá la encuesta correcta. Cerrar solo impide seguir votando. Quitá colaboradores y revocá accesos de gestión cuando corresponda; no podés recuperar listas de participantes ya descargadas por otros. Contactá al operador para retirar una cuenta invitada.', checked: 'El 9 de octubre de 2026, una copia aislada de la versión instalada descargó el CSV nativo de gestión con dos participantes ficticios. Coincidieron nombres, correo disponible, horas de respuesta en la zona local y votos Yes/No/If need be; no incluía tokens de participantes, descripción ni lugar. Las visitas anónimas no pudieron abrir la gestión ni su menú de exportación. Los votos visibles públicamente se pueden copiar. No se probó importar CSV ni migrar una encuesta completa.' },
  } },
  { id: 'pollaris', name: 'Pollaris', version: '1.2.3', source: 'https://framagit.org/pollaris/pollaris/-/tree/1.2.3', copy: {
    en: { stored: 'The server stores the poll, choices, participant names and votes. The secret management link grants control without an account.', steps: ['Open the poll’s results page and select Export CSV.', 'Save the CSV and inspect the participant names and responses. Anyone able to read this public poll can also access its CSV; this is not an organizer-only private export.'], scope: 'The CSV is a results table, not a restorable bundle of settings, management credentials, comments or poll history. Treat participant names and responses as shared with anyone who has the public poll link.', reopen: 'Open the CSV in a spreadsheet. No native import of this result file as a new poll was found in the installed version. Create a new poll manually if needed.', deletion: 'Keep the management link private. Open it, use the poll administration controls → Delete, and confirm the correct poll. Anyone holding this link can change or delete the poll. Closing or losing the link is not deletion; retain it until you finish. Participant exports and recipient copies remain.', checked: 'Public creation, anonymous voting, CSV contents, rejection of an incorrect management token and native deletion of the fictional poll passed on 8 October 2026.' },
    es: { stored: 'El servidor guarda la encuesta, opciones, nombres de participantes y votos. El enlace secreto de gestión da control sin cuenta.', steps: ['Abrí los resultados de la encuesta y elegí Exportar CSV.', 'Guardá el CSV y revisá los nombres y respuestas. Quien puede leer esta encuesta pública también puede acceder al CSV; no es una exportación privada exclusiva del organizador.'], scope: 'El CSV es una tabla de resultados, no un paquete restaurable de ajustes, credenciales de gestión, comentarios o historial. Considerá que los nombres y respuestas se comparten con quien tenga el enlace público.', reopen: 'Abrí el CSV en una hoja de cálculo. No se encontró una importación nativa de ese archivo como nueva encuesta en la versión instalada. Creá otra encuesta manualmente si hace falta.', deletion: 'Conservá en privado el enlace de gestión. Abrilo, usá los controles de administración → Borrar y confirmá la encuesta correcta. Cualquiera con ese enlace puede modificarla o eliminarla. Cerrar la encuesta o perder el enlace no equivale a borrarla; conservalo hasta terminar. Las exportaciones y copias de destinatarios permanecen.', checked: 'La creación pública, el voto sin cuenta, el contenido CSV, el rechazo de una clave de gestión incorrecta y el borrado nativo de la encuesta ficticia pasaron el 8 de octubre de 2026.' },
  } },
  { id: 'liberaforms', name: 'LiberaForms', version: '4.11.1-p5', source: 'https://docs.liberaforms.org/user-guide/e2ee/', copy: {
    en: { stored: 'The server stores account details, form definitions, permissions and encrypted answers. Authorized recipients decrypt answers with their own keys; questions and account metadata are not encrypted in the same way.', steps: ['As an authorized form editor or reader, open the form’s Answers view. Restore/unlock your existing E2EE key if requested; generating a new key does not recover old answers.', 'Use the answer table’s export controls for CSV, JSON or PDF. Check filters and selected rows before saving. File attachments are disabled on this instance.', 'Back up the personal encryption key using Profile → E2EE and test the native Restore operation in a separate browser profile. Keep key recovery material separate from a plaintext answer export.'], scope: 'Answer exports are readable data and can omit filtered-out responses. They do not recreate the complete form definition, collaborators, permissions, account settings or all history. This instance does not accept file attachments. On installations that enable them, attachments require a separate download; a CSV/JSON filename does not contain the file. A key backup alone does not contain the answers.', reopen: 'Read CSV in a spreadsheet, JSON in a suitable viewer and PDF in a reader. No answer-export-to-complete-form restore is promised. Native key restoration and decryption were tested separately from answer-file portability.', deletion: 'An authorized editor can delete selected answers, all answers or the form with the native confirmations. Closing public submissions does not erase existing answers. Review collaborators and exports: removing a reader cannot erase their downloaded plaintext or keys. Use the profile’s account deletion process for the account; preserve needed shared forms before confirming.', checked: 'Fictional encrypted answer access, JSON export, key recovery and isolated server restore were previously exercised on 8 October 2026. On 9 October, the installed browser export component produced CSV, JSON and PDF from two fictional answers; reopened files preserved the checked content, including CSV quotes and line breaks. This format check supplied table data after decryption and did not retest authentication or keys. Attachments are disabled here.' },
    es: { stored: 'El servidor guarda cuentas, definiciones de formularios, permisos y respuestas cifradas. Los destinatarios autorizados descifran las respuestas con sus claves; las preguntas y metadatos de cuenta no llevan ese mismo cifrado.', steps: ['Como editor o lector autorizado, abrí Respuestas del formulario. Restaurá o desbloqueá tu clave E2EE existente si se solicita; generar otra no recupera respuestas antiguas.', 'Usá los controles de exportación de la tabla para CSV, JSON o PDF. Revisá filtros y filas seleccionadas antes de guardar. Los archivos adjuntos están desactivados en esta instancia.', 'Respaldá tu clave personal desde Perfil → E2EE y probá Restaurar en otro perfil del navegador. Conservá la recuperación de claves por separado de las respuestas exportadas sin cifrar.'], scope: 'Las exportaciones contienen respuestas legibles y pueden omitir las excluidas por filtros. No recrean toda la definición del formulario, colaboradores, permisos, ajustes de cuenta ni historial completo. Esta instancia no acepta archivos adjuntos. En instalaciones que los habilitan, se descargan por separado: un nombre de archivo en CSV/JSON no contiene el archivo. Un respaldo de claves no incluye las respuestas.', reopen: 'Abrí CSV en una hoja de cálculo, JSON en un visor adecuado y PDF en un lector. No se promete restaurar un formulario completo desde una exportación de respuestas. La restauración de claves y el descifrado se probaron por separado de la portabilidad de archivos de respuestas.', deletion: 'Un editor autorizado puede borrar respuestas seleccionadas, todas las respuestas o el formulario mediante las confirmaciones nativas. Cerrar la recepción no borra respuestas existentes. Revisá colaboradores y exportaciones: retirar un lector no borra sus copias descifradas ni sus claves. Para la cuenta, usá el proceso de borrado del perfil; conservá los formularios compartidos necesarios antes de confirmar.', checked: 'El acceso a respuestas ficticias cifradas, la exportación JSON, la recuperación de claves y la restauración aislada del servidor se probaron el 8 de octubre de 2026. El 9 de octubre, el componente de exportación instalado generó CSV, JSON y PDF con dos respuestas ficticias; los archivos reabiertos conservaron el contenido comprobado, incluidas comillas y saltos de línea en CSV. Esta prueba de formatos usó datos de tabla posteriores al descifrado; no volvió a probar autenticación ni claves. Los adjuntos están desactivados acá.' },
  } },
  { id: 'fmd', name: 'FMD Server', version: '0.17.0-p2', source: 'https://fmd-foss.org/docs/fmd-server/hosted-server/', copy: {
    en: { stored: 'For devices you deliberately register, the server retains encrypted locations and pictures plus device/account and push-routing metadata. This instance caps saved records at 300 locations and 5 pictures per account; a count limit is not a time-retention promise. HTTPS passes through Cloudflare, which handles connection metadata and ordinary HTTP content while application ciphertext remains encrypted. The map requests OpenStreetMap tiles from your browser, revealing connection information and the viewed map area. Push delivery uses the endpoint configured for your device.', steps: ['Sign in to the FMD web application with your own FMD ID and password.', 'Open Settings → Export data. Keep the session open while the browser retrieves and decrypts your saved data, then save the ZIP.'], scope: 'The ZIP contains locations.csv (time, provider, battery, coordinates and available accuracy/altitude/speed/bearing), pictures as PNG files, and info.json with FMD ID and push URL. Zero values in the optional accuracy, altitude, speed and bearing fields are preserved; missing values are blank. It is a decrypted, sensitive export. It does not include all device settings, passwords, encryption recovery material or a full command history. Protect the push URL too.', reopen: 'Open the CSV and pictures locally and inspect info.json privately. No native import of this ZIP as a replacement FMD account is documented in the inspected client; do not treat it as device re-enrolment or key recovery.', deletion: 'Settings has separate Delete locations, Delete photos and Delete account controls. Confirm only your own records. Disconnect the FMD app and revoke its push endpoint/integrations when retiring a device so it cannot continue submitting or receiving commands. Clearing the browser alone does not delete the server account.', checked: 'On 9 October 2026, a disposable account passed public browser login, decrypted ZIP download, local ZIP reopening and exact checks of three fictional locations, a tiny PNG and account metadata, including nonzero, zero and missing optional CSV values. The browser location, photo and account deletion controls passed. Map tiles were replaced with a local fixture for this test. Android recovery, push delivery and importing the ZIP into an FMD account were not tested.' },
    es: { stored: 'Para dispositivos que registrás deliberadamente, el servidor conserva ubicaciones y fotos cifradas, además de metadatos de dispositivo, cuenta y envío de notificaciones. Esta instancia limita cada cuenta a 300 ubicaciones y 5 fotos guardadas; un límite de cantidad no promete un plazo de conservación. HTTPS pasa por Cloudflare, que procesa metadatos de conexión y contenido HTTP común; los datos cifrados por la aplicación siguen cifrados. El mapa solicita imágenes a OpenStreetMap desde tu navegador y revela información de conexión y la zona consultada. Las notificaciones usan el canal configurado para tu dispositivo.', steps: ['Entrá a la aplicación web FMD con tu propio identificador FMD y contraseña.', 'Abrí Settings → Export data. Mantené la sesión abierta mientras el navegador recupera y descifra los datos y guardá el ZIP.'], scope: 'El ZIP contiene locations.csv (hora, proveedor, batería, coordenadas y precisión, altitud, velocidad y rumbo disponibles), fotos PNG e info.json con identificador FMD y URL de notificaciones. Los valores cero de los campos opcionales de precisión, altitud, velocidad y rumbo se conservan; los valores ausentes quedan vacíos. Es una exportación descifrada y sensible. No incluye todos los ajustes del dispositivo, contraseñas, recuperación de claves ni historial completo de órdenes. Protegé también la URL de notificaciones.', reopen: 'Abrí localmente el CSV y las fotos y revisá info.json en privado. El cliente inspeccionado no documenta una importación del ZIP como cuenta FMD de reemplazo; no lo tratés como recuperación de claves ni como registro automático del dispositivo.', deletion: 'Settings ofrece controles separados Delete locations, Delete photos y Delete account. Confirmá solo tus propios registros. Desconectá la app FMD y revocá su canal de notificaciones e integraciones al retirar un dispositivo, para que no siga enviando datos ni recibiendo órdenes. Borrar solo el navegador no elimina la cuenta del servidor.', checked: 'El 9 de octubre de 2026, una cuenta descartable pasó el ingreso público desde el navegador, la descarga del ZIP descifrado, su apertura local y la comprobación exacta de tres ubicaciones ficticias, un PNG diminuto y los metadatos de la cuenta, incluidos valores opcionales del CSV distintos de cero, cero y ausentes. Pasaron los controles del navegador para borrar ubicaciones, fotos y cuenta. Las imágenes del mapa se sustituyeron por un archivo local de prueba. No se probaron la recuperación con Android, las notificaciones ni la importación del ZIP a una cuenta FMD.' },
  } },
];

export function renderYourData(language: Language, t: Translate): HTMLElement {
  const es = language === 'es';
  const main = element('main', 'page-shell your-data-page'); main.id = 'main-content'; main.tabIndex = -1;
  const header = element('header', 'page-header your-data-header');
  header.append(element('h1', '', es ? 'Tus datos: exportar y borrar' : 'Your data: export and delete'));
  const introduction = element('div', 'your-data-introduction');
  introduction.append(element('p', 'page-intro', es
    ? 'Exportá tus datos importantes con regularidad y conservá una copia independiente. Una exportación puede no incluir todos los ajustes, archivos adjuntos, permisos o elementos del historial; cada guía indica su alcance. Protegé los archivos descargados que contengan información personal o confidencial.'
    : 'Export important data regularly and keep an independent copy. An export may not include every setting, attachment, permission, or part of the history; each guide lists its scope. Protect downloaded files containing personal or confidential information.'));
  introduction.append(element('p', 'your-data-instructions', es ? 'Elegí abajo el servicio que usás. Antes de borrar algo, descargá lo que necesitás y comprobá que podás abrirlo; cada guía explica también qué pasa con las copias compartidas y los respaldos.' : 'Choose your service below. Before deleting anything, download what you need and check that you can open it; each guide also explains what happens to shared copies and backups.'));
  header.append(introduction, element('p', 'your-data-review', es ? 'Revisado entre el 8 y el 9 de octubre de 2026; cada procedimiento indica sus comprobaciones. Los nombres de controles corresponden a las interfaces instaladas; algunos siguen en inglés.' : 'Reviewed 8–9 October 2026; each procedure states its checks. Control names refer to the installed interfaces; some remain in English.'));
  main.append(header);
  const table = element('table', 'retention-table');
  const head = element('thead'); const headers = element('tr');
  for (const label of [es ? 'Servicio' : 'Service', es ? 'Versión revisada' : 'Reviewed version', es ? 'Procedimiento' : 'Procedure']) headers.append(element('th', '', label));
  head.append(headers); table.append(head); const body = element('tbody');
  for (const guide of guides) {
    const row = element('tr'); row.append(element('td', '', guide.name), element('td', '', guide.version));
    const cell = element('td'); const link = element('a', 'text-link', es ? 'Exportar y borrar' : 'Export and delete'); link.href = `#${guide.id}`; cell.append(link); row.append(cell); body.append(row);
  }
  for (const id of ['spliit', 'wishlist', 'kitchenowl', 'opengist', 'linkding', 'vikunja', 'bytestash', 'calino', 'radicale', 'gathio', 'razzia', 'chhoto', 'newsletters', 'addy', 'projects', 'trip', 'family-chess', 'donetick', 'beaverhabits']) {
    const entry = catalogEntry(id); const guide = practicalGuides.find(item => item.tools.some(tool => tool.id === id));
    if (!entry || !guide) continue;
    const row = element('tr'); row.append(element('td', '', entry.upstreamProject ?? id), element('td', '', entry.installedVersion ?? ''));
    const cell = element('td'); const link = element('a', 'text-link', es ? 'Guardar, exportar y borrar: alcance y pasos' : 'Save, export and delete: scope and steps'); link.href = practicalGuidePath(guide.id, language); cell.append(link); row.append(cell); body.append(row);
  }
  table.append(body); const scroll = element('div', 'table-scroll your-data-index'); scroll.append(table); main.append(scroll);
  const backups = element('section', 'prose section'); backups.id = 'backups';
  backups.append(element('h2', '', es ? 'Conservación y respaldos' : 'Retention and backups'));
  backups.append(element('p', '', es
    ? 'Borrar datos activos no reescribe respaldos anteriores ni copias de destinatarios. FreshRSS conserva siete generaciones diarias y cuatro generaciones semanales de respaldo; una ejecución manual también cuenta como generación. Los respaldos de Reactive Resume, Penpot, Actual, Wakapi, Rallly, Pollaris, FMD, CryptPad y LiberaForms no tienen eliminación automática configurada. No hay un plazo fijo verificado para que sus datos desaparezcan de esos respaldos.'
    : 'Deleting active data does not rewrite earlier backups or recipient copies. FreshRSS backups retain seven daily generations and four weekly generations; a manual run also consumes a generation. Reactive Resume, Penpot, Actual, Wakapi, Rallly, Pollaris, FMD, CryptPad and LiberaForms backups have no automatic deletion configured. There is no verified fixed deadline for their data to disappear from those backups.'));
  backups.append(element('p', '', es
    ? 'Los respaldos están en la misma máquina virtual y restringidos al operador. Los de CryptPad y LiberaForms están cifrados; los demás conjuntos mencionados son archivos o volcados sin cifrado adicional de respaldo, aunque pueden contener datos ya cifrados por la aplicación. No hay recuperación fuera de esa máquina ensayada. Los plazos de registros del borde y de proveedores siguen sin verificarse; no equivalen a la retención de documentos.'
    : 'Backups are on the same VM with restricted operator access. CryptPad and LiberaForms backup archives are encrypted; the other sets mentioned are archives or dumps without additional backup encryption, although they may contain application-encrypted data. Off-host recovery has not been rehearsed. Edge/provider log retention remains unverified and is separate from document retention.'));
  backups.append(element('p', '', es
    ? 'Spliit, Wishlist, KitchenOwl, Opengist, linkding, Vikunja, ByteStash, el calendario, Gathio, Razzia, Chhoto URL, Kill the Newsletter!, addy.io, Projects, TRIP, Family Chess, Donetick y Beaver también tienen respaldos diarios en esta máquina virtual sin vencimiento automático configurado. Sus guías distinguen lo que podés exportar de los respaldos operativos.'
    : 'Spliit, Wishlist, KitchenOwl, Opengist, linkding, Vikunja, ByteStash, the calendar, Gathio, Razzia, Chhoto URL, Kill the Newsletter!, addy.io, Projects, TRIP, Family Chess, Donetick and Beaver also have daily backups on this VM without configured automatic expiry. Their guides distinguish user exports from operational backups.'));
  main.append(backups);
  for (const guide of guides) {
    const copy = guide.copy[language]; const section = element('section', 'prose section'); section.id = guide.id;
    section.append(element('h2', '', `${guide.name} · ${guide.version}`), element('p', '', copy.stored));
    const steps = element('ol'); for (const step of copy.steps) steps.append(element('li', '', step)); section.append(steps);
    for (const [label, text] of [[es ? 'Qué incluye y qué omite' : 'Included and omitted', copy.scope], [es ? 'Cómo volver a abrirlo' : 'Reopen or import', copy.reopen], [es ? 'Borrado y acceso compartido' : 'Deletion and shared access', copy.deletion], [es ? 'Verificación realizada' : 'Verification performed', copy.checked]]) {
      section.append(element('h3', '', label), element('p', '', text));
    }
    const backupLink = element('a', 'text-link', es ? 'Conservación de respaldos de este servicio' : 'Backup retention for this service'); backupLink.href = '#backups';
    const source = element('a', 'text-link', es ? 'Documentación del proyecto' : 'Upstream documentation'); source.href = guide.source;
    const links = element('div', 'guide-links'); links.append(backupLink, source); section.append(links); main.append(section);
  }
  const temporary = element('section', 'prose section');
  temporary.append(element('h2', '', es ? 'Pastes, notificaciones y pizarras temporales' : 'Pastes, notifications and temporary boards'));
  temporary.append(element('p', '', es ? 'Estos servicios tienen controles y plazos propios. Guardá lo necesario antes de que expire y consultá la guía o las notas del servicio; no todos ofrecen una exportación de cuenta.' : 'These services have their own controls and expiry. Save what you need before it expires and check the guide or service notes; not every service has an account export.'));
  const temporaryLinks = element('div', 'guide-links');
  for (const [label, href] of [
    ['PrivateBin', `/${language}/${es ? 'guias/compartir-codigo' : 'guides/share-code'}`],
    ['Rustpad', practicalGuidePath('shared-code-pad', language)],
    ['WBO', `/${language}/${es ? 'guias/pizarra-compartida' : 'guides/shared-whiteboard'}`],
    ['Yopass', `${routePath('transparency', language)}#privacy-yopass`],
    ['ntfy', `${routePath('transparency', language)}#privacy-ntfy`],
  ] as const) { const link = element('a', 'text-link', label); link.href = href; temporaryLinks.append(link); }
  temporary.append(temporaryLinks); main.append(temporary);
  const closure = element('section', 'prose section'); closure.append(element('h2', '', t('closure.title')), element('p', '', t('closure.body')));
  const status = element('a', 'text-link', es ? 'Consultar el estado' : 'Check service status'); status.href = routePath('status', language); closure.append(status);
  closure.append(element('p', '', es ? 'La página de estado usa esta infraestructura: una caída total también puede impedir que cargue. No dependás de ella como único aviso.' : 'The status page uses this infrastructure: a complete outage can also prevent it from loading. Do not rely on it as your only notice.'));
  main.append(closure); return main;
}
