import type { CatalogEntry, LocalizedText } from './catalog.ts';
import { reviewedFossProviders } from './upstreams.ts';
const text = (en: string, es: string): LocalizedText => ({ en, es });
const p = reviewedFossProviders.addy;

export const addyAdditions: CatalogEntry[] = [{
  id: 'addy', providerId: 'addy', kind: 'service', implementation: 'upstream-application', portalSurface: 'upstream-interface', category: 'service', discoveryGroup: 'privacy', configUrlKey: 'publicAliasesUrl', accountAccess: 'closed-registration',
  name: text('Forward email through aliases · addy.io', 'Reenviar correo mediante alias · addy.io'),
  description: text('Give a website an alias instead of your inbox address, then forward its messages to your verified recipient. An existing account is required.', 'Dale a un sitio un alias en lugar de la dirección de tu buzón y reenviá sus mensajes a tu destinatario verificado. Necesitás una cuenta existente.'),
  launchLabel: text('Manage email aliases', 'Gestionar alias de correo'),
  help: text('Sign in with your separate addy.io account. Use Create Alias, choose a verified recipient and save the generated address. Deactivate an alias to stop forwarding without deleting its record.', 'Iniciá sesión con tu cuenta separada de addy.io. Usá Create Alias, elegí un destinatario verificado y guardá la dirección generada. Desactivá un alias para detener el reenvío sin borrar su registro.'),
  limitation: text('Public registration is closed. Incoming mail is limited to 1 MiB and monthly bandwidth to 100 MiB per user, with 60 forwarded/replied messages and 20 new aliases per hour. Delivery depends on the participating mail providers. The application interface is English.', 'El registro público está cerrado. El correo entrante tiene un máximo de 1 MiB y el tráfico mensual, de 100 MiB por usuario, con 60 mensajes reenviados o respondidos y 20 alias nuevos por hora. La entrega depende de los proveedores de correo participantes. La interfaz de la aplicación está en inglés.'),
  labels: ['server', 'external'], filesUploaded: true,
  dataFlow: text('Email and attachments pass through Utilibre’s Proxmox Mail Gateway and addy.io to the recipient’s mail provider. Utilibre can read mail while processing it. Recipient fields are encrypted at rest with operator-held keys; this is not zero-knowledge storage. The web application uses Caddy on Hetzner infrastructure in Germany. Cloudflare provides DNS for this hostname without its HTTP proxy. Local sender authentication queries domain and signing records through DNS; no message content is sent to a separate scanning service. Retained Postfix blocklist checks query Spamhaus through the configured resolver, sharing SMTP client IP and mail-domain metadata, not message bodies. Their provider retention is unverified.', 'El correo y los adjuntos pasan por Proxmox Mail Gateway y addy.io de Utilibre hasta el proveedor de correo del destinatario. Utilibre puede leer el correo durante el procesamiento. Los campos de destinatarios se cifran en reposo con claves en poder del operador; no es almacenamiento de conocimiento cero. La aplicación web usa Caddy en infraestructura de Hetzner en Alemania. Cloudflare proporciona DNS para este nombre sin su intermediario HTTP. La autenticación local del remitente consulta registros de dominios y firmas mediante DNS; no envía el contenido del mensaje a otro servicio de análisis. Las comprobaciones de listas de bloqueo que conserva Postfix consultan Spamhaus mediante el resolvedor configurado: comparten metadatos de IP del cliente SMTP y dominios de correo, no el cuerpo del mensaje. No se verificó la conservación de esos datos por los proveedores.'),
  upstreamServices: ['Hetzner hosting', 'Cloudflare DNS only', 'Utilibre Proxmox Mail Gateway', 'Sender and destination mail providers', 'Spamhaus DNS blocklists via configured resolver'],
  temporaryStorage: text('The server stores account and recipient settings, aliases, delivery counters and operational records. The persisted mail queue retries for up to five days. Native cleanup removes failed-delivery records and optional saved messages after seven days, on a daily schedule; outbound-message records use seven days with cleanup every six hours. Those limits do not cover all copies or account data.', 'El servidor guarda ajustes de cuentas y destinatarios, alias, contadores de entrega y registros operativos. La cola persistente reintenta la entrega durante un máximo de cinco días. La limpieza nativa quita registros de fallos y mensajes guardados opcionalmente después de siete días, con una tarea diaria; los registros de salida usan siete días con limpieza cada seis horas. Esos límites no abarcan todas las copias ni los datos de la cuenta.'),
  retention: text('Aliases, recipients and account settings have no automatic expiry. Export Alias Data downloads alias records as CSV, not messages or a complete account backup. Native account deletion revokes tokens and removes account records, but inactive shared-domain alias reservations and deleted-username reservations may remain. Delivered mail stays with recipients. Daily backups remain on this VM without automatic expiry; deletion does not erase earlier backups.', 'Los alias, destinatarios y ajustes de cuenta no vencen automáticamente. Export Alias Data descarga registros de alias en CSV, no mensajes ni un respaldo completo de la cuenta. El borrado nativo de la cuenta revoca tokens y quita sus registros, pero pueden quedar reservas inactivas de alias del dominio compartido y del nombre de usuario eliminado. El correo entregado queda con los destinatarios. Los respaldos diarios permanecen en esta máquina virtual sin vencimiento automático; borrar no elimina respaldos anteriores.'),
  logging: text('No visitor analytics. Native web, PHP and mail logs can contain IP addresses, sender/recipient/alias identifiers and request details. Laravel uses 14-day daily-file rotation; an additional size check every five minutes rotates mail and Laravel files at 1 MiB with two older copies. Container output rotates across two 1 MiB files. Gateway access logs are off. Edge, security and mail-provider retention remain separately unverified.', 'Sin analíticas de visitantes. Los registros nativos web, de PHP y de correo pueden incluir direcciones IP, identificadores de remitentes, destinatarios o alias y detalles de solicitudes. Laravel usa rotación diaria de archivos de 14 días; otra comprobación cada cinco minutos rota archivos de correo y Laravel al alcanzar 1 MiB, con dos copias anteriores. La salida de cada contenedor rota en dos archivos de 1 MiB. Los registros de acceso del intermediario están desactivados. La conservación del borde, seguridad y proveedores de correo sigue sin verificarse por separado.'),
  license: p.license, upstreamProject: p.project, upstreamSourceUrl: p.sourceUrl, installedVersion: p.installedVersion, modified: false, operationalStatus: 'operational',
}];
