import type { CatalogEntry, LocalizedText } from './catalog.ts';
import { reviewedFossProviders } from './upstreams.ts';
const text = (en: string, es: string): LocalizedText => ({ en, es });
const provider = reviewedFossProviders.autoredact;
export const autoredactAdditions: CatalogEntry[] = [{
  id: 'autoredact', providerId: 'autoredact', kind: 'service', implementation: 'upstream-application', portalSurface: 'upstream-interface',
  category: 'service', discoveryGroup: 'privacy', configUrlKey: 'publicToolsUrl', launchPath: '/apps/autoredact/',
  name: text('Redact detected text · AutoRedact', 'Ocultar texto detectado · AutoRedact'),
  description: text('Find possible emails, IP addresses and secrets in images with local OCR, then inspect the blacked-out result.', 'Buscá posibles correos, direcciones IP y claves en imágenes con OCR local; después revisá el resultado oculto con bloques negros.'),
  launchLabel: text('Review an image for redaction', 'Revisar una imagen para ocultar datos'),
  help: text('Start with the fictional example. Review Detection Settings and Safe Values, then select images or a PDF. Download and inspect every page; an empty detection count does not prove that a file is safe to share.', 'Empezá con el ejemplo ficticio. Revisá Detection Settings y Safe Values; después seleccioná imágenes o un PDF. Descargá y revisá cada página: que no se detecte nada no demuestra que el archivo se pueda compartir sin riesgo.'),
  limitation: text('Automatic OCR can miss or wrongly identify text. Only the English OCR model is configured; controls are in English. Common addresses in the native Safe Values list are excluded by default. PDFs are limited to 10 MiB and 20 pages and are rasterized, losing searchable text, forms and other document structure.', 'El OCR puede omitir texto o identificarlo mal. Solo está configurado el modelo inglés; los controles están en inglés. Las direcciones comunes de Safe Values se excluyen por defecto. Los PDF se limitan a 10 MiB y 20 páginas y se convierten en imágenes, perdiendo texto seleccionable, formularios y otra estructura del documento.'),
  labels: ['local'], filesUploaded: false,
  dataFlow: text('Images, PDF rasterization, English OCR and exports run in the browser. Workers, WASM, model files and fonts come from Utilibre. The server OCR/API mode is not deployed; input files and recognized text are not uploaded by this build.', 'Las imágenes, la conversión de PDF, el OCR inglés y las exportaciones se procesan en el navegador. Los trabajadores, WASM, modelos y fuentes se descargan de Utilibre. No está desplegado el modo OCR/API del servidor; esta versión no sube archivos ni texto reconocido.'),
  upstreamServices: ['Cloudflare HTTPS proxy', 'Hetzner hosting'],
  temporaryStorage: text('Current files and results stay in page memory. Detection settings, allowlists and custom rule text persist in localStorage. Native OCR model caching in IndexedDB is disabled; normal browser asset caching is separate.', 'Los archivos y resultados actuales quedan en la memoria de la página. Los ajustes, listas de excepciones y reglas personalizadas persisten en localStorage. La caché nativa del modelo OCR en IndexedDB está desactivada; la caché normal de recursos del navegador es independiente.'),
  retention: text('Process Another Image or Reset clears the current result; reloading also clears files. Remove saved custom rules in Detection Settings or clear the tools site’s browser data, which also affects other apps on that origin. PNG, ZIP and image-only PDF downloads remain on your device. There is no Utilibre server copy of input files to recover or delete.', 'Process Another Image o Reset borra el resultado actual; recargar también quita los archivos. Eliminá las reglas guardadas desde Detection Settings o borrá los datos del sitio tools, lo que también afecta otras aplicaciones de ese origen. Las descargas PNG, ZIP y PDF de imágenes quedan en tu dispositivo. Utilibre no tiene una copia de los archivos originales que pueda recuperar o borrar.'),
  logging: text('Recognized-text debug logging is removed. Application delivery still creates connection metadata through Cloudflare, Caddy and hosting infrastructure; those records have separate retention. No visitor analytics is added.', 'Se quitó el registro de depuración del texto reconocido. La descarga de la aplicación genera metadatos de conexión en Cloudflare, Caddy y la infraestructura de alojamiento; esos registros tienen conservación independiente. No se agregan estadísticas de visitantes.'),
  license: provider.license, upstreamProject: provider.project, upstreamSourceUrl: provider.sourceUrl, installedVersion: provider.installedVersion,
  modified: true, operationalStatus: 'operational',
}];
