import type { CatalogEntry, LocalizedText } from './catalog.ts';
import { reviewedFossProviders } from './upstreams.ts';
const text = (en: string, es: string): LocalizedText => ({ en, es });

export const calendarAdditions: CatalogEntry[] = (['calino', 'radicale'] as const).map(id => {
  const provider = reviewedFossProviders[id];
  return {
    id, providerId: id, kind: 'service', implementation: 'upstream-application', portalSurface: 'upstream-interface',
    category: 'service', discoveryGroup: 'planning', accountAccess: 'invite-required', configUrlKey: 'publicCalendarUrl',
    ...(id === 'radicale' ? { launchPath: 'dav/.web/' } : {}),
    name: id === 'calino' ? text('Manage calendars and contacts · Calino', 'Gestionar calendarios y contactos · Calino') : text('Connect a calendar app · Radicale', 'Conectar una aplicación de calendario · Radicale'),
    description: id === 'calino' ? text('Manage calendars and contacts in your browser with an approved Utilibre calendar account.', 'Gestioná calendarios y contactos en el navegador con una cuenta de calendario de Utilibre aprobada.') : text('Synchronize calendars and address books with compatible CalDAV and CardDAV clients.', 'Sincronizá calendarios y libretas con clientes compatibles con CalDAV y CardDAV.'),
    launchLabel: id === 'calino' ? text('Open the calendar', 'Abrir el calendario') : text('Manage collections', 'Gestionar colecciones'),
    help: text('Connect to https://calendar.utilibre.org/dav/ with a dedicated calendar username and password. These are separate from Utilibre OpenID. Use native ICS/VCF collection downloads for independent copies; keep downloaded files private.', 'Conectate a https://calendar.utilibre.org/dav/ con un usuario y una contraseña propios de calendario, distintos de OpenID de Utilibre. Descargá colecciones ICS/VCF para conservar copias independientes; guardá los archivos en privado.'),
    limitation: text('Owner-only collections; no shared-calendar workflow is enabled. Calino saves credentials with reversible obfuscation, not strong encryption. Client exports include loaded records; use collection downloads for full server collections. Limits: 1 MiB per resource and 10 MiB per request.', 'Las colecciones son de acceso exclusivo del propietario; no hay un flujo de calendario compartido habilitado. Calino guarda credenciales con ofuscación reversible, no cifrado fuerte. Sus exportaciones incluyen registros cargados; descargá colecciones para copiar su contenido completo del servidor. Límites: 1 MiB por recurso y 10 MiB por solicitud.'),
    labels: id === 'calino' ? ['local', 'server'] : ['server'], filesUploaded: true,
    dataFlow: text('Calendar/contact records travel over HTTPS through Cloudflare and Caddy to Radicale on Utilibre. The server can read the records. Calino also retains a browser working copy. No external CalDAV proxy or visitor analytics is enabled.', 'Los registros de calendario y contactos viajan por HTTPS a través de Cloudflare y Caddy hacia Radicale en Utilibre. El servidor puede leerlos. Calino también conserva una copia de trabajo en el navegador. No hay proxy CalDAV externo ni estadísticas de visitantes habilitadas.'),
    upstreamServices: ['Cloudflare HTTPS proxy', 'Hetzner hosting'],
    temporaryStorage: text('Radicale stores events, tasks and contacts as filesystem collections. Calino/browser clients can retain records, preferences and credentials after closing. There is no configured automatic content expiry.', 'Radicale guarda eventos, tareas y contactos en colecciones del sistema de archivos. Calino y otros clientes pueden conservar registros, preferencias y credenciales al cerrar. No hay vencimiento automático del contenido configurado.'),
    retention: text('Delete server collections through native controls. A browser reset removes local state only. Account revocation and collection deletion are separate operator actions; synchronized copies remain on devices. Daily same-VM backups have no automatic expiry and can retain deleted records.', 'Borrá colecciones del servidor desde los controles nativos. Restablecer el navegador solo quita el estado local. Revocar la cuenta y borrar colecciones son acciones separadas del operador; las copias sincronizadas quedan en los dispositivos. Los respaldos diarios en la misma máquina virtual no vencen automáticamente y pueden conservar registros borrados.'),
    logging: text('Radicale warning/error diagnostics remain, with password masking and no debug headers/bodies. Gateway access logging is off. Container output rotates by size, two 5 MiB files per container; edge/provider retention is separate and unverified.', 'Radicale conserva diagnósticos de advertencia y error con contraseñas ocultas y sin depuración de cabeceras o cuerpos. El intermediario no registra accesos. La salida de contenedores rota por tamaño, dos archivos de 5 MiB por contenedor; la conservación del borde y los proveedores es independiente y no está verificada.'),
    license: provider.license, upstreamProject: provider.project, upstreamSourceUrl: provider.sourceUrl, installedVersion: provider.installedVersion,
    modified: id === 'calino', operationalStatus: 'operational',
  };
});
