import type { CatalogEntry, LocalizedText } from './catalog.ts';
import { reviewedFossProviders } from './upstreams.ts';
const text = (en: string, es: string): LocalizedText => ({ en, es });
const p = reviewedFossProviders.chhoto;
export const chhotoAdditions: CatalogEntry[] = [{
  id: 'chhoto', providerId: 'chhoto', kind: 'service', implementation: 'upstream-application', portalSurface: 'upstream-interface', category: 'service', discoveryGroup: 'sharing', configUrlKey: 'publicLinksUrl',
  name: text('Shorten a link · Chhoto URL', 'Acortar un enlace · Chhoto URL'),
  description: text('Create a short redirect that expires within 30 days. No account is needed.', 'Creá un enlace corto que vence en un máximo de 30 días. No necesitás cuenta.'),
  launchLabel: text('Shorten a link', 'Acortar un enlace'),
  help: text('Paste the original into Long URL, optionally choose a short name and expiry, then select Shorten! Keep the original and copied short link. Ask through the private contact route for early removal.', 'Pegá el original en Long URL, elegí un nombre corto y vencimiento si querés y pulsá Shorten! Guardá el original y el enlace copiado. Pedí la eliminación anticipada por el canal de contacto privado.'),
  limitation: text('Links expire within 30 days and have no owner account or self-service deletion token. Anyone holding the short link can obtain its destination. Do not submit confidential links. Click statistics are disabled.', 'Los enlaces vencen en un máximo de 30 días y no tienen cuenta de propietario ni token de borrado. Cualquiera con el enlace corto puede obtener el destino. No ingresés enlaces confidenciales. Las estadísticas de clics están desactivadas.'),
  labels: ['server'], filesUploaded: false,
  dataFlow: text('The full destination URL, including query strings, fragments and optional notes, passes through Cloudflare/Caddy to readable SQLite storage on Utilibre. The server redirects visitors without fetching the destination; the destination then receives their request.', 'La URL completa, incluidos parámetros, fragmentos y notas opcionales, pasa por Cloudflare/Caddy a SQLite legible en Utilibre. El servidor redirige sin consultar el destino; después ese destino recibe la solicitud del visitante.'),
  upstreamServices: ['Cloudflare HTTPS proxy', 'Hetzner hosting', 'Destination website after following the redirect'],
  temporaryStorage: text('The native redirect checks expiry on each resolution; hourly cleanup removes expired records. Anonymous links have a maximum 30-day lifetime. Browser sessionStorage caches configuration and login UI state.', 'La redirección comprueba el vencimiento en cada consulta; la limpieza horaria quita registros vencidos. Los enlaces anónimos duran como máximo 30 días. sessionStorage conserva configuración y estado de la interfaz de sesión.'),
  retention: text('An operator can delete a link through native administration. Expiry/deletion does not erase downloaded copies or prior daily backups. Backups remain on this VM without configured automatic expiry.', 'El operador puede borrar un enlace desde la administración nativa. El vencimiento o borrado no elimina descargas ni respaldos diarios anteriores. Los respaldos quedan en esta máquina virtual sin vencimiento automático configurado.'),
  logging: text('Click collection is removed from the redirect handler. Application/container logs and gateway access logs are off; gateway errors rotate by size, two 5 MiB files. Edge/security/provider logs remain separate and their retention is unverified.', 'La función de redirección no recopila clics. Los registros de aplicación, contenedor y acceso del intermediario están desactivados; los errores rotan por tamaño, dos archivos de 5 MiB. Los registros del borde, seguridad y proveedores son independientes y su conservación no está verificada.'),
  license: p.license, upstreamProject: p.project, upstreamSourceUrl: p.sourceUrl, installedVersion: p.installedVersion, modified: true, operationalStatus: 'operational',
}];
