import type { CatalogEntry, LocalizedText } from './catalog.ts';
import { reviewedFossProviders } from './upstreams.ts';
const text = (en: string, es: string): LocalizedText => ({ en, es });
const provider = reviewedFossProviders['family-chess'];
export const familyChessAdditions: CatalogEntry[] = [{
  id: 'family-chess', providerId: 'family-chess', kind: 'service', implementation: 'upstream-application', portalSurface: 'upstream-interface', category: 'service', discoveryGroup: 'sharing', configUrlKey: 'publicChessUrl',
  name: text('Play chess with a friend · Family Chess', 'Jugar al ajedrez con alguien · Family Chess'),
  description: text('Create a game, share its code and choose a side. Other visitors can watch.', 'Creá una partida, compartí su código y elegí un lado. Otras personas pueden mirar.'),
  launchLabel: text('Play chess', 'Jugar al ajedrez'),
  bestFor: text('A casual game with someone you know, without creating an account.', 'Una partida con alguien que conocés, sin crear una cuenta.'),
  help: text('Create New Game opens a room. Share its link, choose White or Black and confirm readiness. Use English or Español in the footer to change language.', 'Create New Game o Crear partida abre una sala. Compartí el enlace, elegí blancas o negras y confirmá que estás listo. Cambiá el idioma con English o Español al pie.'),
  limitation: text('Eight-digit game codes are not private links. Anyone with the code can watch or take a vacant seat. There is no native game export, import or immediate-delete button. This is a small pilot with creation and connection limits.', 'Los códigos de ocho dígitos no son enlaces privados. Quien conozca el código puede mirar u ocupar un lugar libre. No hay exportación, importación ni botón de eliminación inmediata de partidas. Es un piloto acotado, con límites de creación y conexiones.'),
  labels: ['server'], filesUploaded: false,
  dataFlow: text('The server processes and can read board positions, moves, game codes and session/seat state. Players and spectators receive the shared game state. Transport encryption does not make the game end-to-end encrypted. Assets are served by Utilibre; no visitor analytics is added.', 'El servidor procesa y puede leer posiciones, jugadas, códigos y estado de sesiones y lugares. Jugadores y espectadores reciben el estado compartido. El cifrado del transporte no convierte la partida en cifrado de extremo a extremo. Utilibre sirve los recursos y no agrega analíticas de visitantes.'),
  upstreamServices: ['Cloudflare HTTPS proxy', 'Hetzner hosting'],
  temporaryStorage: text('SQLite stores games and sessions. Browser cookies maintain sessions, seat recovery, CSRF protection and language preference. Closing a tab does not delete a game or necessarily clear a restored browser session.', 'SQLite guarda partidas y sesiones. Las cookies mantienen sesiones, recuperación de lugares, protección CSRF e idioma. Cerrar una pestaña no borra la partida ni necesariamente una sesión que el navegador restaure.'),
  retention: text('Native cleanup runs every minute: reservations last three minutes, inactive seats are freed after twenty minutes, and games are deleted seven days after creation. Daily snapshots stay on this VM with no automatic expiry; active deletion does not rewrite them. Participants can keep their own copies.', 'La limpieza nativa se ejecuta cada minuto: las reservas duran tres minutos, los lugares inactivos se liberan a los veinte minutos y las partidas se borran siete días después de crearse. Los respaldos diarios quedan en esta VM sin vencimiento automático; el borrado activo no los modifica. Los participantes pueden conservar sus propias copias.'),
  logging: text('Application and gateway access logs are disabled. Warnings and errors use size-based rotation, two one-MiB files per container, and may include paths or game identifiers. Caddy, Cloudflare and system records have separate retention; no time period is inferred from these size limits.', 'Los registros de acceso de la aplicación y su proxy están desactivados. Avisos y errores rotan por tamaño, dos archivos de un MiB por contenedor, y pueden incluir rutas o identificadores. Caddy, Cloudflare y el sistema conservan registros aparte; estos límites de tamaño no establecen un plazo.'),
  license: provider.license, upstreamProject: provider.project, upstreamSourceUrl: provider.sourceUrl, installedVersion: provider.installedVersion,
  modified: true, operationalStatus: 'operational',
}];
