import type { CatalogEntry, LocalizedText } from './catalog.ts';
import { reviewedFossProviders } from './upstreams.ts';
const text = (en: string, es: string): LocalizedText => ({ en, es });
const logging = text('Loading the application creates connection metadata through Cloudflare and Hetzner. No visitor analytics is added. Static app behavior does not establish edge, security or provider log retention.', 'Cargar la aplicación genera metadatos de conexión a través de Cloudflare y Hetzner. No se agregan analíticas de visitantes. El funcionamiento estático no establece cuánto se conservan los registros del borde, de seguridad o de proveedores.');
export const knitNewtonAdditions: CatalogEntry[] = [
  {
    id: 'knit', providerId: 'knit', kind: 'service', implementation: 'upstream-application', portalSurface: 'upstream-interface', category: 'utility', discoveryGroup: 'creative', configUrlKey: 'publicToolsUrl', launchPath: '/apps/knit/',
    name: text('Follow a knitting pattern · Knit', 'Seguir un patrón de tejido · Knit'),
    description: text('Adjust a built-in knitting pattern and follow its rows. Keep the complete page URL to return to your place.', 'Ajustá un patrón de tejido incluido y seguí sus filas. Conservá la URL completa de la página para volver a tu posición.'),
    launchLabel: text('Open Knit', 'Abrir Knit'),
    help: text('Choose a pattern, adjust its measurements, then use Start knitting and the row arrows. Bookmark or copy the full URL after making progress; its fragment carries the settings and row.', 'Elegí un patrón, ajustá sus medidas y usá Start knitting y las flechas de fila. Guardá en favoritos o copiá la URL completa después de avanzar; su fragmento contiene los ajustes y la fila.'),
    bestFor: text('Following the included cable, capelet, triangle and scarf patterns.', 'Seguir los patrones incluidos de cables, capa corta, triángulos y bufanda.'),
    limitation: text('Native controls and stitch abbreviations are in English. No account, cloud sync, PDF export or saved timing history is provided. A shared URL reveals its pattern settings and row; keep a separate record for important work.', 'Los controles y abreviaturas de puntos están en inglés. No hay cuenta, sincronización en la nube, exportación PDF ni historial guardado de tiempos. Una URL compartida revela sus ajustes y fila; conservá un registro separado del trabajo importante.'),
    labels: ['local'], filesUploaded: false,
    dataFlow: text('Pattern generation and row selection run in your browser. The URL fragment after # is not sent in the HTTP request. The packaged app loads its own scripts only; external connections are blocked. Links deliberately opened are separate navigation.', 'El patrón y la selección de fila se procesan en tu navegador. El fragmento de URL después de # no se envía en la solicitud HTTP. La aplicación carga solo sus propios scripts; las conexiones externas están bloqueadas. Los enlaces que abrís deliberadamente son navegaciones separadas.'),
    upstreamServices: ['Cloudflare HTTPS delivery', 'Hetzner hosting'],
    temporaryStorage: text('Settings and the current row are encoded in the URL fragment. Row visit times stay in page memory. The inspected build does not use localStorage, IndexedDB or cookies for pattern state.', 'Los ajustes y la fila actual se codifican en el fragmento de la URL. Los tiempos de visita a las filas quedan en memoria. La compilación revisada no usa localStorage, IndexedDB ni cookies para el estado del patrón.'),
    retention: text('Browser history, bookmarks and copied links can retain a pattern after tab closure. Open the base URL to start from defaults; remove old bookmarks, links and history separately. Utilibre has no saved pattern account or server copy to restore or delete.', 'El historial del navegador, los favoritos y los enlaces copiados pueden conservar el patrón después de cerrar. Abrí la URL base para volver a los valores iniciales; borrá por separado favoritos, enlaces e historial anteriores. Utilibre no tiene una cuenta de patrones ni una copia en el servidor que recuperar o borrar.'),
    logging, license: reviewedFossProviders.knit.license, upstreamProject: 'Knit', upstreamSourceUrl: 'https://github.com/alefore/knit', installedVersion: '1.0.0-42be1d8-p1', modified: true, operationalStatus: 'operational',
  },
  {
    id: 'newton', providerId: 'newton', kind: 'service', implementation: 'upstream-application', portalSurface: 'upstream-interface', category: 'utility', discoveryGroup: 'planning', configUrlKey: 'publicToolsUrl', launchPath: '/apps/newton/',
    name: text('Organize a darts tournament · NewTon', 'Organizar un torneo de dardos · NewTon'),
    description: text('Register players, draw a bracket and keep match results in your browser. Export tournament JSON to keep an independent copy.', 'Registrá jugadores, armá el cuadro y guardá resultados en tu navegador. Exportá el JSON del torneo para conservar una copia independiente.'),
    launchLabel: text('Open NewTon', 'Abrir NewTon'),
    help: text('Create a tournament, add fictional players to try it and mark participating players as paid before drawing the bracket. Export tournament downloads JSON; import a tournament file restores a compatible copy.', 'Creá un torneo, agregá jugadores ficticios para probarlo y marcá como pagados a quienes participan antes de armar el cuadro. Export tournament descarga JSON; import a tournament file restaura una copia compatible.'),
    bestFor: text('Managing a local darts event on one browser.', 'Organizar un evento local de dardos desde un navegador.'),
    limitation: text('Controls are in English. This browser edition has no server backup, shared live tournament, network handover or Chalker companion. Imported tournament settings do not replace Global Settings. Keep exports; browser storage can be cleared or fail.', 'Los controles están en inglés. Esta edición no tiene respaldo en servidor, torneo compartido en vivo, transferencia por red ni aplicación Chalker. Los ajustes de un torneo importado no reemplazan Global Settings. Conservá exportaciones; el almacenamiento del navegador puede borrarse o fallar.'),
    labels: ['local'], filesUploaded: false,
    dataFlow: text('Tournament editing, JSON imports, player records and darts statistics are processed in the browser. No PHP/API or proprietary network client is installed. The package blocks network connections and uses local assets with system font fallbacks.', 'La edición, las importaciones JSON, los registros de jugadores y las estadísticas de dardos se procesan en el navegador. No se instala PHP, una API ni el cliente propietario de red. La compilación bloquea conexiones de red y usa recursos locales con fuentes del sistema como alternativa.'),
    upstreamServices: ['Cloudflare HTTPS delivery', 'Hetzner hosting'],
    temporaryStorage: text('Tournaments, player records, settings and transaction history persist in localStorage. The separate match/statistics registry uses IndexedDB. Native Analytics describes your darts results, not visitor analytics. Browser storage is not encrypted by this app.', 'Los torneos, jugadores, ajustes e historial de operaciones persisten en localStorage. El registro separado de partidas y estadísticas usa IndexedDB. Analytics describe tus resultados de dardos, no analíticas de visitantes. La aplicación no cifra el almacenamiento del navegador.'),
    retention: text('Export tournament includes players, bracket/matches, included history, a configuration snapshot and the player database; it is not an export of every tournament or the separate Analytics registry. Delete tournaments, Analytics records and player records through their separate controls. Earlier downloads remain. No server-held tournament backup exists in this edition.', 'Export tournament incluye jugadores, cuadro y partidas, historial incluido, una instantánea de configuración y la base de jugadores; no exporta todos los torneos ni el registro separado de Analytics. Borrá torneos, registros de Analytics y jugadores con sus controles separados. Las descargas anteriores permanecen. Esta edición no tiene respaldos de torneos en el servidor.'),
    logging, license: reviewedFossProviders.newton.license, upstreamProject: 'NewTon DC Tournament Manager', upstreamSourceUrl: 'https://github.com/skrodahl/NewTon', installedVersion: '5.4.0-p1', modified: true, operationalStatus: 'operational',
  },
];
