import type { CatalogEntry, LocalizedText } from './catalog.ts';
import { reviewedFossProviders } from './upstreams.ts';
const text = (en: string, es: string): LocalizedText => ({ en, es });
const provider = reviewedFossProviders['kokoro-web'];
export const kokoroWebAdditions: CatalogEntry[] = [{
  id: 'kokoro-web', providerId: 'kokoro-web', kind: 'service', implementation: 'upstream-application', portalSurface: 'upstream-interface',
  category: 'service', discoveryGroup: 'creative', configUrlKey: 'publicToolsUrl', launchPath: '/apps/kokoro-web/',
  name: text('Generate a voice clip · Kokoro Web', 'Generar un audio de voz · Kokoro Web'),
  description: text('Turn English or Spanish text into a WAV file on your device.', 'Convertí texto en inglés o español en un archivo WAV desde tu dispositivo.'),
  launchLabel: text('Generate a voice clip', 'Generar un audio de voz'),
  bestFor: text('Short spoken versions of your own text.', 'Versiones habladas breves de tus propios textos.'),
  help: text('Choose Language accent (region), enter Text to process, then use Generate Voice. Listen with Play before Download audio. Saved profiles include text; Delete profile removes the selected saved entry.', 'Elegí Language accent (region), escribí en Text to process y usá Generate Voice. Escuchá con Play antes de Download audio. Los perfiles guardados incluyen el texto; Delete profile borra el perfil seleccionado.'),
  limitation: text('English controls; one English US voice and one Latin American Spanish voice. First-use model/runtime downloads exceed 100 MB and synthesis uses device CPU/memory. WAV at normal speed only. WebGPU availability varies. Pronunciation and output quality need review; no microphone recording or voice cloning.', 'Controles en inglés; una voz de inglés estadounidense y otra de español latinoamericano. El primer uso descarga más de 100 MB y la síntesis usa CPU y memoria del dispositivo. Solo WAV a velocidad normal. WebGPU depende del navegador. Revisá la pronunciación y la calidad; no graba el micrófono ni clona voces.'),
  labels: ['local'], filesUploaded: false,
  dataFlow: text('Speech synthesis runs in your browser. Code, model, stock voices and runtime files are served by Utilibre. API inference, analytics and remote runtime fallbacks are removed. Text/audio are not sent as application requests in the tested workflow.', 'La síntesis de voz funciona en tu navegador. Utilibre sirve el código, el modelo, las voces y los recursos. Se quitaron la inferencia por API, las estadísticas y las alternativas remotas. En el flujo probado, el texto y el audio no se envían como solicitudes de la aplicación.'),
  upstreamServices: ['Cloudflare HTTPS proxy', 'Hetzner hosting'],
  temporaryStorage: text('Unsaved text and generated audio live in page memory. Native profiles save text/settings in localStorage. Model/voice responses persist in the browser Cache API; theme uses an app-specific localStorage key.', 'El texto sin guardar y el audio generado viven en la memoria de la página. Los perfiles nativos guardan texto y ajustes en localStorage. Los modelos y voces persisten en la caché del navegador; el tema usa una clave propia de localStorage.'),
  retention: text('Closing a tab does not remove saved profiles or cached models. Use Delete profile for one saved entry, or browser site-data controls for all retained browser data. Other tools share this origin and are affected by clearing all its data. Downloads remain until deleted. There is no server account or stored text/audio copy to recover.', 'Cerrar la pestaña no borra los perfiles ni los modelos en caché. Usá Delete profile para un perfil o los controles de datos del sitio para todos los datos guardados. Otras herramientas comparten el origen y también se ven afectadas si borrás todo. Las descargas permanecen hasta que las eliminés. No hay cuenta ni copia del texto o audio en el servidor para recuperar.'),
  logging: text('No text/audio analytics is sent. Static app/model delivery produces connection metadata through Cloudflare, Caddy and hosting infrastructure, with separate retention. Source/author links contact external sites only when followed.', 'No se envían estadísticas del texto ni del audio. La descarga de la aplicación y el modelo genera metadatos de conexión en Cloudflare, Caddy y el alojamiento, con conservación independiente. Los enlaces al código y al autor contactan sitios externos solo cuando los seguís.'),
  license: provider.license, upstreamProject: provider.project, upstreamSourceUrl: provider.sourceUrl, installedVersion: provider.installedVersion,
  modified: true, operationalStatus: 'operational',
}];
