import type { CatalogEntry, LocalizedText } from './catalog.ts';
import { reviewedFossProviders } from './upstreams.ts';
const text = (en: string, es: string): LocalizedText => ({ en, es });
const p = reviewedFossProviders.newsletters;
export const newsletterAdditions: CatalogEntry[] = [{
  id: 'newsletters', providerId: 'newsletters', kind: 'service', implementation: 'upstream-application', portalSurface: 'upstream-interface', category: 'service', discoveryGroup: 'reading', configUrlKey: 'publicNewslettersUrl',
  name: text('Read newsletters in RSS · Kill the Newsletter!', 'Leer boletines por RSS · Kill the Newsletter!'),
  description: text('Create an email address that turns incoming newsletters into an Atom feed. No account is needed.', 'Creá una dirección de correo que convierta los boletines recibidos en un canal Atom. No necesitás cuenta.'),
  launchLabel: text('Create a newsletter feed', 'Crear un canal de boletines'),
  help: text('Enter a feed title, choose Create feed and subscribe to a newsletter with the generated address. Open the Atom URL in your reader. Keep both addresses private.', 'Ingresá un título, elegí Create feed y suscribite a un boletín con la dirección generada. Abrí la URL Atom en tu lector. Conservá ambas direcciones en privado.'),
  limitation: text('The feed link grants access to messages and management controls. Messages are readable on the server, expire after 30 days and can disappear earlier when the feed reaches its size limit. This service cannot reply to mail or forward it to another inbox. The application interface is English.', 'El enlace del canal da acceso a mensajes y controles de gestión. El servidor puede leerlos; vencen a los 30 días y pueden desaparecer antes al alcanzar el límite de tamaño. El servicio no responde correos ni los reenvía a otro buzón. La interfaz de la aplicación está en inglés.'),
  labels: ['server'], filesUploaded: true,
  dataFlow: text('Incoming mail passes through Utilibre’s mail gateway into readable message and attachment storage. Browser and feed-reader requests reach Caddy and this application. Cloudflare supplies DNS for this hostname; its HTTP proxy is disabled. Atom entries can retain remote image and tracking-link references that a reader may contact.', 'El correo entrante pasa por el servidor de correo de Utilibre al almacenamiento legible de mensajes y adjuntos. Las solicitudes del navegador y lector llegan a Caddy y a la aplicación. Cloudflare proporciona DNS para este nombre; su intermediario HTTP está desactivado. Las entradas Atom pueden conservar imágenes externas y enlaces de rastreo que el lector podría consultar.'),
  upstreamServices: ['Hetzner hosting', 'Cloudflare DNS only', 'Sender and mail provider', 'External resources retained in messages, if fetched by the reader'],
  temporaryStorage: text('Incoming messages are limited to 512 KiB. Hourly cleanup removes entries older than 30 days; new mail can remove older entries sooner to keep feed content near 512 KiB. Unlinked attachment files are cleaned up. Feed settings have no automatic expiry.', 'Los mensajes entrantes tienen un límite de 512 KiB. La limpieza horaria quita entradas de más de 30 días; al recibir correo puede quitar entradas antes para mantener el canal cerca de 512 KiB. Se limpian los adjuntos sin referencias. Los ajustes del canal no vencen automáticamente.'),
  retention: text('Use the native feed settings to delete the feed after confirming its title. Unsubscribe from senders separately. Downloaded Atom files, separately saved attachments and other readers’ copies remain. Daily backups stay on this VM without automatic expiry; deletion does not remove earlier backups.', 'Usá los ajustes nativos para borrar el canal tras confirmar su título. Cancelá por separado las suscripciones con los remitentes. Permanecen los archivos Atom descargados, los adjuntos guardados por separado y las copias de otros lectores. Los respaldos diarios quedan en esta máquina virtual sin vencimiento automático; borrar no elimina respaldos anteriores.'),
  logging: text('No visitor analytics. Native receipt logs can include sender and feed/entry identifiers. Container logs rotate by size at 1 MiB across two files per container. Gateway access logging is off; warnings/errors remain. Caddy, security and provider retention are separately unverified.', 'Sin analíticas de visitantes. Los registros nativos de recepción pueden incluir remitentes e identificadores de canales y entradas. Los registros de cada contenedor rotan por tamaño en dos archivos de 1 MiB. El intermediario no registra accesos; conserva advertencias y errores. La conservación de Caddy, seguridad y proveedores no está verificada por separado.'),
  license: p.license, upstreamProject: p.project, upstreamSourceUrl: p.sourceUrl, installedVersion: p.installedVersion, modified: true, operationalStatus: 'operational',
}];
