import type { CatalogEntry, LocalizedText } from './catalog.ts';
import { reviewedFossProviders } from './upstreams.ts';
const text = (en: string, es: string): LocalizedText => ({ en, es });
export const projectsAdditions: CatalogEntry[] = [{
  id: 'projects', providerId: 'projects', kind: 'service', implementation: 'upstream-application', portalSurface: 'upstream-interface', category: 'service', discoveryGroup: 'planning', configUrlKey: 'publicProjectsUrl', accountAccess: 'invite-required',
  name: text('Plan a shared board · Projects', 'Planificar un tablero compartido · Projects'),
  description: text('Organize lists, cards, tasks and attachments with your approved Utilibre account.', 'Organizá listas, tarjetas, tareas y adjuntos con tu cuenta aprobada de Utilibre.'),
  launchLabel: text('Open Projects', 'Abrir Projects'),
  bestFor: text('A shared task board with explicit member access.', 'Un tablero compartido de tareas con acceso por integrantes.'),
  help: text('Sign in with Utilibre, create a project and board, then add lists and cards. The board’s three-dot menu offers Export as CSV. Use Support to find the return link to Utilibre.', 'Iniciá sesión con Utilibre, creá un proyecto y un tablero, y agregá listas y tarjetas. El menú de tres puntos del tablero ofrece Export as CSV. En Support encontrás el enlace para volver a Utilibre.'),
  limitation: text('CSV exports omit task text, comments, attachments and permissions and cannot be re-imported as a board. Native deletion archives some records; deleting a project can leave uploaded files. Controls and CSV headings can remain in English. The gateway limits upload requests to 10 MiB.', 'El CSV omite el texto de tareas, comentarios, adjuntos y permisos, y no se puede reimportar como tablero. El borrado nativo archiva algunos registros; borrar un proyecto puede dejar archivos cargados. Los controles y encabezados CSV pueden quedar en inglés. El intermediario limita las solicitudes de carga a 10 MiB.'),
  labels: ['server'], filesUploaded: true,
  dataFlow: text('The browser sends readable account, board and attachment data through the HTTPS providers to Utilibre. Native sign-in uses the existing Utilibre identity service. Authorized board members and the operator can access stored content; this is not end-to-end encryption. External Markdown images, widgets, mail and webhooks are disabled or blocked in this deployment.', 'El navegador envía datos legibles de cuenta, tableros y adjuntos a Utilibre a través de los proveedores HTTPS. El acceso nativo usa el servicio de identidad existente de Utilibre. Los integrantes autorizados y el operador pueden acceder al contenido guardado; no hay cifrado de extremo a extremo. En este despliegue, las imágenes externas en Markdown, widgets, correo y webhooks están desactivados o bloqueados.'),
  upstreamServices: ['Utilibre identity', 'Cloudflare HTTPS proxy', 'Hetzner hosting'],
  temporaryStorage: text('PostgreSQL stores accounts, board content, permissions, activity, notifications and sessions with connection IP/user-agent metadata. Uploaded files are separate. Login cookies, OIDC state and preferences can remain in browser storage after tab closure. No visitor analytics is configured.', 'PostgreSQL guarda cuentas, contenido, permisos, actividad, notificaciones y sesiones con metadatos de IP y agente del navegador. Los archivos cargados se guardan por separado. Las cookies de sesión, el estado OIDC y las preferencias pueden permanecer en el navegador después de cerrar. No hay analíticas de visitantes configuradas.'),
  retention: text('There is no configured automatic expiry for ordinary content or archived records. Explicit attachment deletion removes its active file; project deletion is not a complete file purge. Account removal is an administrator operation that soft-deletes the account and retains identity fields. Daily database/file backups stay on this VM without automatic expiry, so earlier copies can retain deleted records. Keep independent exports and protect their contents.', 'No hay vencimiento automático configurado para el contenido común ni los registros archivados. Borrar un adjunto explícitamente elimina su archivo activo; borrar un proyecto no purga todos sus archivos. La eliminación de cuenta requiere administración, marca la cuenta como borrada y conserva datos de identidad. Los respaldos diarios de base y archivos quedan en esta VM sin vencimiento automático, por lo que las copias anteriores pueden conservar registros borrados. Guardá exportaciones independientes y protegé su contenido.'),
  logging: text('Gateway access logs are disabled. Application errors can include identifiers or request details. Container logs rotate by size, up to two 1 MiB files per container; this is not a period in days. Session metadata has separate database retention. Edge and provider log retention remain unverified.', 'Los registros de acceso del intermediario están desactivados. Los errores de la aplicación pueden incluir identificadores o detalles de solicitudes. Los registros de contenedores rotan por tamaño, hasta dos archivos de 1 MiB por contenedor; no es un plazo en días. Los metadatos de sesión tienen conservación separada en la base. La conservación de registros del borde y proveedores sigue sin verificarse.'),
  license: reviewedFossProviders.projects.license, upstreamProject: 'La Suite Projects', upstreamSourceUrl: 'https://github.com/suitenumerique/projects', installedVersion: '1.3.0-455aa274-p2', modified: true,
  operationalStatus: 'operational',
}];
