import type { CatalogEntry, LocalizedText } from './catalog.ts';
import { reviewedFossProviders } from './upstreams.ts';
const text = (en: string, es: string): LocalizedText => ({ en, es });
const provider = reviewedFossProviders['13ft'];

export const readerAdditions: CatalogEntry[] = [{
  id: '13ft', providerId: '13ft', kind: 'service', implementation: 'upstream-application', portalSurface: 'upstream-interface',
  category: 'service', discoveryGroup: 'reading', configUrlKey: 'publicReaderUrl',
  name: text('Read a public page · 13ft', 'Leer una página pública · 13ft'),
  description: text('Read text from a public HTML page through Utilibre. Scripts and automatic requests for source resources stay blocked.', 'Leé el texto de una página HTML pública mediante Utilibre. Los scripts y las solicitudes automáticas de recursos del origen quedan bloqueados.'),
  launchLabel: text('Read a public page', 'Leer una página pública'),
  bestFor: text('Reading the text of a public HTML page without its scripts or images.', 'Leer el texto de una página HTML pública sin sus scripts ni imágenes.'),
  help: text('Paste a direct public HTTP(S) URL and choose Submit. The native EN/ES form works without JavaScript. Do not enter passwords, account tokens, private links or confidential queries. The source receives a request from our server. Ordinary outbound links can take you to their destinations when clicked; this reader does not certify their safety.', 'Pegá una URL HTTP(S) pública y directa, y elegí Enviar. El formulario nativo EN/ES funciona sin JavaScript. No ingresés contraseñas, tokens de cuentas, enlaces privados ni consultas confidenciales. El origen recibe una solicitud de nuestro servidor. Los enlaces comunes pueden llevarte a sus destinos cuando los elijás; este lector no certifica su seguridad.'),
  limitation: text('Direct HTTP 200 HTML only, standard ports 80/443, up to 1 MiB decoded content. An eight-second deadline is checked between chunks and a 12-second worker timeout bounds stalled work. Two concurrent requests globally; 12 requests/minute/client with burst 4. No source login, redirects, bot-challenge solving, JavaScript rendering, images or archive/Freedium fallback. Availability and publisher access are not guaranteed.', 'Solo HTML directo con HTTP 200, puertos habituales 80/443 y hasta 1 MiB descomprimido. Se comprueba un plazo de ocho segundos entre bloques y un límite de 12 segundos detiene procesos atascados. Hay dos solicitudes simultáneas en total; 12 solicitudes/minuto/cliente con ráfaga 4. Sin sesión del origen, redirecciones, resolución de desafíos antibots, ejecución de JavaScript, imágenes ni archivos alternativos/Freedium. No se garantizan disponibilidad ni acceso a editores.'),
  labels: ['server', 'external'], filesUploaded: false,
  dataFlow: text('Your URL passes through Cloudflare and Caddy to Utilibre. The server retrieves and processes the source HTML in readable form through a restricted public-destination proxy. The source receives the requested path/query and Utilibre’s connection; configured DNS resolvers receive source hostnames. HTTPS sources use encrypted transport; HTTP sources do not. No visitor analytics or automatic external page resources are enabled.', 'Tu URL pasa por Cloudflare y Caddy hacia Utilibre. El servidor obtiene y procesa el HTML del origen de forma legible mediante un proxy limitado a destinos públicos. El origen recibe la ruta y los parámetros solicitados y la conexión de Utilibre; los resolvedores DNS configurados reciben los nombres de los sitios consultados. HTTPS cifra el transporte hacia el origen; HTTP no. No se habilitan estadísticas de visitantes ni recursos externos automáticos de las páginas.'),
  upstreamServices: ['Requested source websites', 'Cloudflare HTTPS proxy', 'Cloudflare DNS resolver (1.1.1.1)', 'Quad9 DNS resolver (9.9.9.9)', 'Hetzner hosting'],
  temporaryStorage: text('Request URLs and source content exist transiently in worker/proxy memory and your browser. There is no account, article database or persistent article cache. Immediate memory erasure is not guaranteed. Native background-job and cached-article routes are unavailable.', 'Las URL solicitadas y el contenido del origen existen temporalmente en la memoria de los procesos/proxy y en tu navegador. No hay cuentas, base de datos de artículos ni caché persistente de artículos. No se garantiza el borrado inmediato de memoria. No están disponibles las rutas nativas de tareas en segundo plano ni de artículos guardados en caché.'),
  retention: text('There is no stored article identifier, later retrieval/deletion API or article backup. Use ordinary browser print/save controls for an independent copy; missing resources remain missing. Clear browser history/site data and delete saved files separately when needed. Closing a tab does not remove downloads. Source, DNS and infrastructure records have separate retention.', 'No hay identificador de artículo almacenado, API de recuperación/borrado posterior ni respaldo de artículos. Usá imprimir/guardar del navegador para una copia independiente; los recursos ausentes seguirán faltando. Borrá por separado el historial/datos del navegador y los archivos guardados cuando lo necesités. Cerrar una pestaña no elimina descargas. Los registros del origen, DNS e infraestructura tienen conservación independiente.'),
  logging: text('Gateway, Gunicorn and Squid access logs are disabled. Critical operational diagnostics remain in Docker logs rotated by size, 1 MiB per file and two files per container; this is not a time-based retention promise. Separate Caddy/Cloudflare, system/security, hosting, DNS and source records are not covered by an application no-logs claim. Their exact retention is unverified here.', 'Los registros de acceso del intermediario, Gunicorn y Squid están desactivados. Quedan diagnósticos operativos críticos en registros Docker rotados por tamaño: 1 MiB por archivo y dos archivos por contenedor; esto no promete un plazo de conservación. Los registros de Caddy/Cloudflare, sistema/seguridad, alojamiento, DNS y origen son independientes de cualquier afirmación sobre registros de la aplicación. Su conservación exacta no se verificó aquí.'),
  license: provider.license, upstreamProject: provider.project, upstreamSourceUrl: provider.sourceUrl, installedVersion: provider.installedVersion,
  modified: true, operationalStatus: 'operational',
}];
