import type { CatalogEntry, LocalizedText } from './catalog.ts';
import { reviewedFossProviders } from './upstreams.ts';
const text = (en: string, es: string): LocalizedText => ({ en, es });
const provider = reviewedFossProviders.rustpad;

export const rustpadAdditions: CatalogEntry[] = [{
  id: 'rustpad', providerId: 'rustpad', kind: 'service', implementation: 'upstream-application', portalSurface: 'upstream-interface',
  category: 'service', discoveryGroup: 'text-data', configUrlKey: 'publicToolsUrl', launchPath: '/apps/rustpad/',
  name: text('Edit code together · Rustpad', 'Editar código en grupo · Rustpad'),
  description: text('Work on a short text or code snippet together in a shared, temporary editor. Save an independent copy before leaving.', 'Trabajá en grupo sobre un texto o fragmento de código en un editor compartido y temporal. Guardá una copia independiente antes de salir.'),
  launchLabel: text('Open a shared pad', 'Abrir un editor compartido'),
  bestFor: text('Discussing a small code example with people you trust with the whole document.', 'Comentar un ejemplo breve de código con personas a quienes confiás el documento completo.'),
  help: text('Open the editor to generate a sharing link, then use Copy under Share Link or copy the full address. Anyone with that link can read and change the document; there are no accounts, read-only roles or link revocation. Names are display labels, not verified identities. Copy your text into a local file to keep it.', 'Abrí el editor para generar un enlace y usá Copy en Share Link o copiá la dirección completa. Cualquiera que tenga el enlace puede leer y modificar el documento; no hay cuentas, permisos de solo lectura ni revocación del enlace. Los nombres son etiquetas, no identidades verificadas. Copiá el texto a un archivo local para conservarlo.'),
  limitation: text('Temporary, server-readable text; not end-to-end encrypted. Native cleanup removes pads about 24–25 hours after the latest connection, even if an editor remains open; edits do not extend that period. A service restart also loses all pads. Up to 256 KiB of UTF-8 text, 4,096 edits or 1 MiB of edit-history data per pad; 64 pads and 128 connections across the service. Save a copy before a limit or disconnection.', 'Texto temporal que el servidor puede leer, sin cifrado de extremo a extremo. La limpieza nativa elimina los documentos unas 24–25 horas después de la última conexión, aunque un editor siga abierto; editar no prolonga ese plazo. Reiniciar el servicio también pierde todos los documentos. Hasta 256 KiB de texto UTF-8, 4.096 ediciones o 1 MiB de historial por documento; 64 documentos y 128 conexiones en todo el servicio. Guardá una copia antes de alcanzar un límite o desconectarte.'),
  labels: ['server'], filesUploaded: true,
  dataFlow: text('Document text, editing history, display names and cursor positions pass to Utilibre’s server and connected collaborators. HTTPS/WSS encrypt the connection, but the server processes readable content. The editor and its workers are hosted locally; no visitor analytics or third-party editor CDN is enabled. The public connection passes through Cloudflare and the separate Caddy TLS edge on the Hetzner host in Germany.', 'El texto, el historial de edición, los nombres y las posiciones de los cursores pasan al servidor de Utilibre y a las personas conectadas. HTTPS/WSS cifran la conexión, pero el servidor procesa contenido legible. El editor y sus procesos auxiliares se alojan localmente; no se habilitan estadísticas de visitantes ni una CDN externa del editor. La conexión pública pasa por Cloudflare y el intermediario TLS Caddy separado en el servidor de Hetzner en Alemania.'),
  upstreamServices: ['Cloudflare HTTPS proxy', 'Hetzner hosting'],
  temporaryStorage: text('Pads and their edit history exist in server memory without a database. The browser remembers preferences such as your name, color and theme in site storage. Sharing links can remain in browser history or wherever you send them.', 'Los documentos y su historial existen en la memoria del servidor, sin base de datos. El navegador recuerda preferencias como el nombre, el color y el tema en los datos del sitio. Los enlaces compartidos pueden quedar en el historial o donde los enviés.'),
  retention: text('There are no document backups, account exports or recovery after expiry/restart. Clearing all text changes the current document but does not erase earlier in-memory operations or other people’s copies. No per-pad permanent-delete control is available. Close editors and wait for native expiry; clear browser site data and remove local files separately when needed. Immediate memory erasure is not promised.', 'No hay respaldos de documentos, exportaciones de cuentas ni recuperación tras la caducidad o un reinicio. Borrar todo el texto modifica el documento actual, pero no elimina las operaciones anteriores en memoria ni las copias de otras personas. No hay un control de borrado permanente por documento. Cerrá los editores y esperá la caducidad nativa; borrá por separado los datos del navegador y los archivos locales cuando lo necesités. No se promete el borrado inmediato de memoria.'),
  logging: text('Local gateway access logs are disabled and native application logging is restricted to errors. Docker operational logs rotate by size at 1 MiB per file, two files per container. This is not a time-based deletion guarantee; separate public-edge, system/security and hosting logs have their own retention.', 'Los registros de acceso del intermediario local están desactivados y la aplicación solo registra errores. Los registros operativos de Docker rotan por tamaño: 1 MiB por archivo, dos archivos por contenedor. Esto no garantiza un plazo de borrado; los registros del acceso público, sistema/seguridad y alojamiento tienen su propia conservación.'),
  license: provider.license, upstreamProject: provider.project, upstreamSourceUrl: provider.sourceUrl, installedVersion: provider.installedVersion,
  modified: true, operationalStatus: 'operational',
}];
