import type { CatalogEntry } from './catalog.ts';

// Selection guidance and constraints are independent, optional catalogue facts.
export const selectionNotes: Record<string, Pick<CatalogEntry, 'bestFor' | 'limitation'>> = {
  wbo: { limitation: { en: 'The server can read these temporary drawings. Restarting erases them; export SVG regularly.', es: 'El servidor puede leer estos dibujos temporales. Reiniciar los borra; exportá SVG con frecuencia.' } },
  bentopdf: { limitation: { en: 'Check OCR names, accents and numbers against the original. A searchable PDF is not an editable Word layout.', es: 'Compará nombres, tildes y números del OCR con el original. Un PDF con texto seleccionable no es un documento Word editable.' } },
  vert: { limitation: { en: 'Remote video conversion is disabled. Processing components can take time to download.', es: 'La conversión remota de video está deshabilitada. Los componentes pueden tardar en descargarse.' } },
  pairdrop: { limitation: { en: 'Both devices must stay online. Restricted networks may not connect: no relay fallback is configured.', es: 'Ambos dispositivos deben seguir conectados. Las redes restrictivas pueden impedir la transferencia: no hay relay alternativo.' } },
  searxng: { bestFor: { en: 'General web search.', es: 'Búsquedas generales en la web.' }, limitation: { en: 'Your query is sent to selected search engines, which may block or limit results.', es: 'Tu consulta se envía a motores seleccionados, que pueden bloquear o limitar los resultados.' } },
  fourget: { bestFor: { en: 'Choosing the search provider yourself.', es: 'Elegir el proveedor de búsqueda.' }, limitation: { en: 'English interface; results depend on external search providers.', es: 'Interfaz en inglés; los resultados dependen de proveedores externos.' } },
  degoog: { limitation: { en: 'Google CSE and Mwmbl provide web results; providers can limit access or return incomplete results.', es: 'Google CSE y Mwmbl ofrecen resultados web; los proveedores pueden limitar el acceso o devolver resultados incompletos.' } },
  'qr-offline': { bestFor: { en: 'A straightforward QR with PNG, SVG or PDF download.', es: 'Un QR sencillo con descarga en PNG, SVG o PDF.' }, limitation: { en: 'QR codes do not encrypt their contents; QR history is not retained after a reload.', es: 'Los códigos QR no cifran su contenido; el historial de QR no se conserva al recargar.' } },
  miniqr: { bestFor: { en: 'Visual customization or reading a QR from an image.', es: 'Personalizar el diseño o leer un QR desde una imagen.' }, limitation: { en: 'Decoration can make a QR harder to scan. Test it before sharing.', es: 'La decoración puede dificultar la lectura del QR. Probalo antes de compartirlo.' } },
  pollaris: { bestFor: { en: 'Organising a poll without registering.', es: 'Organizar una encuesta sin registrarte.' }, limitation: { en: 'Anyone with the management link can edit or delete the poll. Keep it private.', es: 'Cualquiera que tenga el enlace de gestión puede modificar o eliminar la encuesta. Mantenelo en privado.' } },
  rallly: { bestFor: { en: 'Finding a meeting time when the organizer has an account and guests do not.', es: 'Elegir un horario cuando quien organiza tiene cuenta y los invitados no.' }, limitation: { en: 'Creating polls requires an approved account.', es: 'Para crear encuestas necesitás una cuenta aprobada.' } },
  drawio: { bestFor: { en: 'Structured flowcharts and diagrams.', es: 'Diagramas de flujo y diagramas estructurados.' }, limitation: { en: 'Cloud collaboration and server-side export are disabled; save a local copy.', es: 'La colaboración en la nube y la exportación desde el servidor están desactivadas; guardá una copia local.' } },
  excalidraw: { bestFor: { en: 'Quick sketches and explaining an idea.', es: 'Hacer bocetos rápidos y explicar una idea.' }, limitation: { en: 'No live collaboration. Drawings can persist in browser storage; export an independent copy.', es: 'Sin colaboración en vivo. Los dibujos pueden persistir en el navegador; exportá una copia independiente.' } },
  'omni-compress-image': { bestFor: { en: 'Quick size reduction before uploading or emailing an image.', es: 'Reducir el tamaño antes de subir o enviar una imagen por correo.' }, limitation: { en: 'Large images can need substantial browser memory. Compression can reduce dimensions; check the result. Some controls remain in English.', es: 'Las imágenes grandes pueden requerir bastante memoria del navegador. La compresión puede reducir las dimensiones; revisá el resultado. Algunos controles siguen en inglés.' } },
  'omni-background': { limitation: { en: 'The downloaded model needs substantial browser memory; inspect fine edges before using the result.', es: 'El modelo descargado necesita bastante memoria del navegador; revisá los bordes finos antes de usar el resultado.' } },
  'omni-image-editor': { bestFor: { en: 'Cropping an image or adding text and annotations.', es: 'Recortar una imagen o agregar texto y anotaciones.' } },
  minipaint: { bestFor: { en: 'Editing an image with separate layers.', es: 'Editar una imagen con capas separadas.' }, limitation: { en: 'An exported flat image does not preserve editable layers. Save a project too.', es: 'Una imagen exportada sin capas no conserva las capas editables. Guardá también un proyecto.' } },
  svgedit: { bestFor: { en: 'Drawing or editing SVG graphics that can scale.', es: 'Dibujar o editar gráficos SVG que se pueden ampliar.' } },
  cyberchef: { limitation: { en: 'Network operations and RSA Verify are disabled. Extract EXIF does not work with this instance’s security policy; use Image Scrubber to inspect image metadata.', es: 'Las operaciones de red y RSA Verify están desactivadas. Extract EXIF no funciona con la política de seguridad de esta instancia; usá Image Scrubber para revisar metadatos de imágenes.' } },
  'image-scrubber': { limitation: { en: 'Covering details does not guarantee anonymity. Use opaque paint and inspect the downloaded PNG.', es: 'Tapar detalles no garantiza anonimato. Usá pintura opaca y revisá el PNG descargado.' } },
};
