import type { CatalogEntry, LocalizedText } from './catalog.ts';
import { reviewedFossProviders, type FossProviderId } from './upstreams.ts';
const text = (en: string, es: string): LocalizedText => ({ en, es });
function base(id: FossProviderId, configUrlKey: string): CatalogEntry {
  const p = reviewedFossProviders[id];
  return { id, providerId: id, kind: 'service', implementation: 'upstream-application', portalSurface: 'upstream-interface', category: 'service', discoveryGroup: 'planning', configUrlKey,
    name: text(p.project, p.project), description: text('', ''), labels: ['server'], filesUploaded: false,
    dataFlow: text('', ''), upstreamServices: ['Cloudflare HTTPS proxy', 'Hetzner hosting'], temporaryStorage: text('', ''), retention: text('', ''), logging: text('', ''),
    license: p.license, upstreamProject: p.project, upstreamSourceUrl: p.sourceUrl, installedVersion: p.installedVersion, modified: true, operationalStatus: 'operational' };
}
export const socialAdditions: CatalogEntry[] = [
  {
    ...base('chitchatter', 'publicChatUrl'), discoveryGroup: 'sharing', labels: ['local', 'server'],
    name: text('Chat in a temporary room · Chitchatter', 'Conversar en una sala temporal · Chitchatter'),
    description: text('Share a room link for text, files and direct audio or video calls.', 'Compartí un enlace de sala para conversar, enviar archivos y hacer llamadas directas de audio o video.'),
    launchLabel: text('Open a chat room', 'Abrir una sala'),
    help: text('Use the generated room name and send its link privately. A public-room link grants entry; a native private room also needs the agreed password. Keep both peers online for calls and transfers.', 'Usá el nombre generado y enviá el enlace en privado. El enlace de una sala pública permite entrar; una sala privada también requiere la contraseña acordada. Mantené ambos dispositivos conectados durante llamadas y transferencias.'),
    limitation: text('Peers see each other’s connection addresses. No TURN relay is enabled, so restrictive networks may fail. Large transfers depend on browser memory. Recipients can retain messages and files.', 'Los participantes ven sus direcciones de conexión. No hay retransmisión TURN habilitada; algunas redes restrictivas pueden impedir conectarse. Las transferencias grandes dependen de la memoria del navegador. Los destinatarios pueden conservar mensajes y archivos.'),
    dataFlow: text('Utilibre provides the app, WebSocket peer discovery and STUN. Messages, calls and files use encrypted direct WebRTC between peers; no third-party discovery provider or server message archive is configured. Discovery still processes peer identifiers, offers and connection metadata.', 'Utilibre sirve la aplicación, el descubrimiento de participantes por WebSocket y STUN. Los mensajes, llamadas y archivos usan WebRTC directo cifrado entre participantes; no hay proveedor externo de descubrimiento ni archivo de mensajes en el servidor configurados. El descubrimiento procesa identificadores, ofertas de conexión y metadatos.'),
    temporaryStorage: text('The native transcript holds up to 150 messages in application memory. Identity keys and preferences remain in browser storage; transferred files use browser memory. Discovery peer entries expire after two idle minutes, checked every 30 seconds, or on disconnect.', 'La conversación nativa conserva hasta 150 mensajes en la memoria de la aplicación. Las claves de identidad y preferencias quedan en el navegador; las transferencias usan su memoria. El descubrimiento vence tras dos minutos sin actividad, revisados cada 30 segundos, o al desconectarse.'),
    retention: text('There is no persistent tracker volume or tracker backup. Clear this app’s browser data to remove local identity/preferences. That does not remove other participants’ copies or downloaded files.', 'No hay volumen persistente ni respaldo del descubrimiento. Borrá los datos de esta aplicación en el navegador para quitar identidad y preferencias locales. Eso no elimina las copias de otros participantes ni los archivos descargados.'),
    logging: text('Discovery application/container logs and gateway access logs are disabled; gateway critical errors remain. Edge, STUN, system/security and provider logs have separate retention that is not established by this application check.', 'Los registros de aplicación y contenedor del descubrimiento y los accesos del intermediario están desactivados; quedan errores críticos del intermediario. Los registros del borde, STUN, sistema, seguridad y proveedores tienen una conservación independiente que esta revisión no establece.'),
  },
  {
    ...base('gathio', 'publicEventsUrl'), filesUploaded: true,
    name: text('Share an event · Gathio', 'Compartir un evento · Gathio'),
    description: text('Create an event page with a calendar download. No account needed.', 'Creá una página para tu evento con una descarga de calendario. No necesitás cuenta.'),
    launchLabel: text('Create an event', 'Crear un evento'),
    help: text('Save the private management link when you create an event. Use calendar export for an ICS copy. Importing ICS creates a new event and a new management link.', 'Guardá el enlace privado de gestión al crear un evento. Exportá un archivo ICS desde el calendario. Importarlo crea un evento nuevo con otro enlace de gestión.'),
    limitation: text('Anyone with an unlisted event URL can read it; anyone with its management link can edit or delete it. Email recovery, reminders and federation are disabled. ICS omits attendees, comments, image files and management links.', 'Cualquiera con la URL de un evento sin listar puede leerlo; el enlace de gestión permite editarlo o borrarlo. El correo de recuperación, los recordatorios y la federación están desactivados. ICS omite asistentes, comentarios, imágenes y enlaces de gestión.'),
    dataFlow: text('Event details, optional attendee/contact fields, comments and uploaded images pass through Cloudflare/Caddy to readable storage on Utilibre. No external federation or email delivery is enabled.', 'Los detalles, campos opcionales de asistentes y contacto, comentarios e imágenes pasan por Cloudflare/Caddy a almacenamiento legible en Utilibre. No hay federación externa ni envío de correo habilitados.'),
    temporaryStorage: text('The native daily cleanup deletes events seven days after their end. The application also stores database operation/error logs with identifiers and no configured expiry.', 'La limpieza diaria nativa elimina eventos siete días después de terminar. La aplicación también guarda registros de operaciones y errores con identificadores, sin vencimiento configurado.'),
    retention: text('Delete through the event editor. Downloads and other people’s copies remain. Daily backups on this VM have no automatic expiry; earlier copies can retain deleted events and images.', 'Borrá el evento desde su editor. Las descargas y copias ajenas permanecen. Los respaldos diarios en esta máquina virtual no vencen automáticamente; las copias anteriores pueden conservar eventos e imágenes borrados.'),
    logging: text('Gateway access logs are off. Container and error output rotates by size, two 5 MiB files per container. Native database operation logs have separate, unbounded retention; edge/provider retention is unverified.', 'Los registros de acceso del intermediario están desactivados. La salida de contenedores y errores rota por tamaño, dos archivos de 5 MiB por contenedor. Los registros de operaciones de la base tienen conservación independiente sin vencimiento; la del borde y proveedores no está verificada.'),
  },
  {
    ...base('link-cleaner', 'publicToolsUrl'), launchPath: '/apps/link-cleaner/', discoveryGroup: 'text-data', labels: ['local'],
    name: text('Clean tracking parameters · URL Parameter Cleaner', 'Quitar parámetros de rastreo · URL Parameter Cleaner'),
    description: text('Remove known tracking parameters from links and review the result before sharing.', 'Quitá parámetros de rastreo conocidos y revisá el enlace antes de compartirlo.'),
    launchLabel: text('Clean a link', 'Limpiar un enlace'),
    help: text('Paste links, clean them and compare the result. Keep rules take priority over removal rules. You can export rule profiles and optional reports.', 'Pegá enlaces, limpialos y compará el resultado. Las reglas para conservar tienen prioridad sobre las de quitar. Podés exportar perfiles de reglas e informes opcionales.'),
    limitation: text('Unknown parameters and fragments remain. Cleaning does not check a destination’s safety or remove every possible identifier. Redacted reports still contain domains and paths.', 'Los parámetros desconocidos y los fragmentos permanecen. Limpiar no comprueba la seguridad del destino ni quita todos los identificadores posibles. Los informes redactados todavía contienen dominios y rutas.'),
    dataFlow: text('Pasted links are processed in browser memory. This build never visits their destinations or uploads the links; the app’s own files are downloaded from Utilibre.', 'Los enlaces se procesan en la memoria del navegador. Esta versión no visita sus destinos ni sube los enlaces; los archivos de la aplicación se descargan de Utilibre.'),
    temporaryStorage: text('Inputs and results stay in page memory. The app writes no saved browser history, localStorage, IndexedDB, cookies or service worker.', 'Los datos y resultados quedan en la memoria de la página. La aplicación no guarda historial, localStorage, IndexedDB, cookies ni un trabajador de servicio.'),
    retention: text('Reload clears the current inputs and results. Downloaded profiles/reports remain on your device until you delete them; protect sensitive links and reports.', 'Recargar borra los datos y resultados actuales. Los perfiles e informes descargados quedan en tu dispositivo hasta que los borrés; protegé los enlaces e informes sensibles.'),
    logging: text('Pasted links do not become application requests. Serving the app still creates connection metadata in the hosting path; existing gateway and edge logging notes apply.', 'Los enlaces pegados no se convierten en solicitudes de la aplicación. Descargarla genera metadatos de conexión en la infraestructura; se aplican sus notas de registros del intermediario y borde.'),
  },
];
