import type { CatalogEntry, LocalizedText } from './catalog.ts';
import { reviewedFossProviders } from './upstreams.ts';
const text = (en: string, es: string): LocalizedText => ({ en, es });
const logging = text('Downloading the application creates connection metadata. No visitor analytics or document backend is added. Edge, security and provider log retention is separately unverified.', 'Descargar la aplicación genera metadatos de conexión. No se agregan analíticas de visitantes ni un servidor de documentos. La conservación de registros del borde, de seguridad y de proveedores no está verificada por separado.');
export const standaloneAdditions: CatalogEntry[] = [
  {
    id: 'one-file-core', providerId: 'one-file-core', kind: 'service', implementation: 'upstream-application', portalSurface: 'upstream-interface', category: 'utility', discoveryGroup: 'design', configUrlKey: 'publicToolsUrl', launchPath: '/apps/one-file-core/',
    name: text('Download a diagram file · The One File', 'Descargar un archivo de diagramas · The One File'),
    description: text('Draw nodes and connections in a standalone HTML file, then download an updated copy to keep editing locally.', 'Dibujá nodos y conexiones en un HTML independiente y descargá otra copia actualizada para seguir editando localmente.'),
    launchLabel: text('Download Core and open locally', 'Descargar Core y abrirlo localmente'),
    help: text('Download the HTML, open it in your browser and add a node. Save HTML downloads another editable copy. Reopen that new file and check it before replacing an older copy.', 'Descargá el HTML, abrilo en tu navegador y agregá un nodo. Save HTML descarga otra copia editable. Abrí ese archivo nuevo y revisalo antes de reemplazar una copia anterior.'),
    bestFor: text('Portable diagrams that include their own editor.', 'Diagramas portátiles que incluyen su editor.'),
    limitation: text('Controls are in English. This is the standalone Core edition, with no live monitoring or multiplayer server. Creating encrypted HTML is disabled because upstream saves can leave readable document data in the page; use hat.sh on the completed file if needed. Import only trusted files.', 'Los controles están en inglés. Es la edición Core independiente, sin monitoreo en vivo ni servidor multijugador. Crear HTML cifrado está desactivado porque el guardado original puede dejar datos legibles del documento en la página; usá hat.sh sobre el archivo completo si lo necesitás. Importá solo archivos de confianza.'),
    labels: ['local'], filesUploaded: false,
    dataFlow: text('The website delivers an application download. Diagrams are edited in your locally opened file, not submitted to Utilibre. This package blocks external resources and connections. Links you deliberately open are separate requests.', 'El sitio entrega la aplicación para descargar. Editás los diagramas en el archivo que abrís localmente; no se envían a Utilibre. Esta compilación bloquea recursos y conexiones externas. Los enlaces que abrís deliberadamente generan solicitudes separadas.'),
    upstreamServices: ['Hetzner hosting and Cloudflare HTTP delivery for application downloads'],
    temporaryStorage: text('The editor uses browser memory and IndexedDB autosaves. Local recovery snapshots and edit records can persist after tab closure. These are readable browser data, not server analytics.', 'El editor usa memoria del navegador y borradores en IndexedDB. Las instantáneas de recuperación y los registros locales de edición pueden persistir al cerrar la pestaña. Son datos legibles del navegador, no analíticas del servidor.'),
    retention: text('Use Settings → Clear All for this editor’s working data and recovery state, then save a new empty copy if needed. Delete unwanted downloaded files and independent backups separately. Old HTML copies retain their contents; Utilibre cannot retrieve or delete your local documents. Browser file-storage behavior varies.', 'Usá Settings → Clear All para los datos de trabajo y recuperación de este editor; después guardá otra copia vacía si la necesitás. Borrá por separado las descargas y respaldos independientes que ya no querás. Los HTML anteriores conservan su contenido; Utilibre no puede recuperar ni borrar tus documentos locales. El almacenamiento de archivos en el navegador varía.'),
    logging, license: reviewedFossProviders['one-file-core'].license, upstreamProject: 'The One File Core', upstreamSourceUrl: 'https://github.com/gelatinescreams/The-One-File', installedVersion: '4.1.5-p1', modified: true, operationalStatus: 'operational',
  },
  {
    id: 'tiddlywiki', providerId: 'tiddlywiki', kind: 'service', implementation: 'upstream-application', portalSurface: 'upstream-interface', category: 'utility', discoveryGroup: 'documents', configUrlKey: 'publicToolsUrl', launchPath: '/apps/tiddlywiki/',
    name: text('Download a personal wiki · TiddlyWiki', 'Descargar una wiki personal · TiddlyWiki'),
    description: text('Keep linked notes and their editor together in a portable HTML notebook. Save an updated file after editing.', 'Reuní notas enlazadas y su editor en un cuaderno HTML portátil. Guardá un archivo actualizado después de editar.'),
    launchLabel: text('Download a notebook and open locally', 'Descargar un cuaderno y abrirlo localmente'),
    help: text('Choose the English or Spanish file. Open it locally, create a note with + and confirm it with the check mark. Save changes downloads the updated wiki; reopening the original download does not recover unsaved edits.', 'Elegí el archivo en inglés o español. Abrilo localmente, creá una nota con + y confirmala con la marca de verificación. Guardar cambios descarga la wiki actualizada; abrir la descarga original no recupera ediciones sin guardar.'),
    bestFor: text('A personal notebook you can copy and keep without an account.', 'Un cuaderno personal que podés copiar y conservar sin cuenta.'),
    limitation: text('No server notebook, remote sync or browser-storage plugin is installed. Download changes before closing the tab. Files are not encrypted by default. Import only trusted notes/plugins; external images and plugin-library connections are blocked in this edition.', 'No hay cuaderno en el servidor, sincronización remota ni complemento de almacenamiento del navegador instalado. Descargá los cambios antes de cerrar la pestaña. Los archivos no están cifrados de forma predeterminada. Importá solo notas y complementos de confianza; esta edición bloquea imágenes externas y conexiones a bibliotecas de complementos.'),
    labels: ['local'], filesUploaded: false,
    dataFlow: text('The website delivers a single-file application. Notes are edited in the locally opened HTML and saved through the browser’s download function. The supplied edition blocks external resource requests; it adds no account or document-storage service.', 'El sitio entrega una aplicación en un archivo. Editás las notas en el HTML abierto localmente y las guardás mediante la descarga del navegador. Esta edición bloquea solicitudes de recursos externos; no agrega cuentas ni un servicio para guardar documentos.'),
    upstreamServices: ['Hetzner hosting and Cloudflare HTTP delivery for application downloads'],
    temporaryStorage: text('Unsaved notes remain in the open page’s memory. This build has no local-storage autosave plugin. Optional native password settings can use browser storage; do not assume closing a tab clears every preference.', 'Las notas sin guardar quedan en la memoria de la página abierta. Esta compilación no tiene complemento de autoguardado en almacenamiento local. Los ajustes nativos opcionales de contraseñas pueden usar almacenamiento del navegador; no asumás que cerrar una pestaña borra todas las preferencias.'),
    retention: text('Delete a note through its native edit/delete controls, then download and verify the updated wiki. Earlier HTML copies and backups still contain the deleted note until you delete those copies. There is no Utilibre account or server notebook to erase.', 'Borrá una nota con sus controles nativos de edición y borrado; después descargá y verificá la wiki actualizada. Los HTML y respaldos anteriores conservan la nota borrada hasta que eliminés esas copias. No hay cuenta de Utilibre ni cuaderno en el servidor que borrar.'),
    logging, license: reviewedFossProviders.tiddlywiki.license, upstreamProject: 'TiddlyWiki', upstreamSourceUrl: 'https://github.com/TiddlyWiki/TiddlyWiki5', installedVersion: '5.4.1-p1', modified: true, operationalStatus: 'operational',
  },
];
