import type { CatalogEntry, LocalizedText } from './catalog.ts';
const text = (en: string, es: string): LocalizedText => ({ en, es });
export const tripAdditions: CatalogEntry[] = [{
  id: 'trip', providerId: 'trip', kind: 'service', implementation: 'upstream-application', portalSurface: 'upstream-interface', category: 'service', discoveryGroup: 'planning', configUrlKey: 'publicTripUrl', accountAccess: 'invite-required',
  name: text('Plan a trip · TRIP', 'Planificar un viaje · TRIP'),
  description: text('Keep places, daily plans and PDF travel documents together.', 'Reuní lugares, planes diarios y documentos de viaje en PDF.'),
  launchLabel: text('Open TRIP', 'Abrir TRIP'),
  bestFor: text('A travel plan shared with selected members, with a downloadable account backup.', 'Un plan de viaje compartido con integrantes elegidos y un respaldo de cuenta descargable.'),
  help: text('Use your approved Utilibre account with permission for TRIP. Create a fictional trip first. Export through Settings → Data → Backups. Controls are currently in English and other upstream languages; a Spanish interface is not included in this release.', 'Usá tu cuenta aprobada de Utilibre con permiso para TRIP. Creá primero un viaje ficticio. Exportá desde Settings → Data → Backups. Los controles están en inglés y otros idiomas originales; esta versión no incluye interfaz en español.'),
  limitation: text('Anyone holding an uploaded image URL can open it without signing in. PDF attachments follow trip permissions, with separate explicit sharing controls. Search and route requests leave Utilibre; their shared limit is 30 requests/minute. PDF uploads are limited to 2 MiB each. Remote image downloads, link previews, Google API integration and notifications are disabled.', 'Cualquiera que tenga la URL de una imagen subida puede abrirla sin iniciar sesión. Los adjuntos PDF siguen los permisos del viaje, con controles separados para compartir explícitamente. Las búsquedas y rutas salen de Utilibre; comparten un límite de 30 solicitudes por minuto. Cada PDF puede pesar hasta 2 MiB. Las descargas de imágenes remotas, vistas previas de enlaces, integración de la API de Google y notificaciones están desactivadas.'),
  labels: ['server', 'external'], filesUploaded: true,
  dataFlow: text('Utilibre stores readable trip plans, places, account settings, membership and uploaded files; this is not end-to-end encryption. Your browser requests map tiles from OpenStreetMap through its Fastly CDN, exposing viewed tile coordinates and connection metadata. The server sends search text to komoot Photon and route coordinates to FOSSGIS. The Navigation control opens Google Maps with the selected coordinates. The public hostname uses Cloudflare as an HTTPS proxy, where ordinary HTTP content and connection metadata are processed. The outbound proxy uses Cloudflare and Quad9 DNS resolvers for provider hostnames. No visitor analytics is configured.', 'Utilibre guarda planes, lugares, ajustes de cuenta, membresías y archivos subidos legibles; no hay cifrado de extremo a extremo. Tu navegador pide mapas a OpenStreetMap a través de su CDN Fastly y comunica las coordenadas de las imágenes del mapa y metadatos de conexión. El servidor envía el texto de búsqueda a Photon de komoot y las coordenadas de las rutas a FOSSGIS. El control de navegación abre Google Maps con las coordenadas seleccionadas. El dominio público usa Cloudflare como intermediario HTTPS, que procesa el contenido HTTP común y los metadatos de conexión. El intermediario de salida usa los resolutores DNS de Cloudflare y Quad9 para los dominios de los proveedores. No hay analíticas de visitantes configuradas.'),
  upstreamServices: ['Utilibre identity', 'OpenStreetMap tiles via Fastly', 'komoot Photon', 'FOSSGIS routing', 'Google Maps (chosen navigation)', 'Cloudflare HTTPS proxy and DNS resolver', 'Quad9 DNS resolver', 'Hetzner hosting'],
  temporaryStorage: text('SQLite and local files store account and travel data. Browser sign-in tokens, preferences and app caches can remain after closing a tab. Map tiles use normal browser caching. The server has no proxy content cache.', 'SQLite y archivos locales guardan los datos de cuentas y viajes. Los tokens de sesión, las preferencias y la caché de la aplicación pueden permanecer en el navegador después de cerrar una pestaña. El mapa usa la caché normal del navegador. El intermediario del servidor no guarda una caché de contenido.'),
  retention: text('Ordinary content has no automatic expiry. Native item deletion and administrator account deletion remove the tested active records and files; downloaded or shared copies remain separate. Daily private backups stay on this VM without automatic pruning. Earlier backups can retain deleted data. FOSSGIS states that it logs route requests. Exact deletion periods for OSMF tile logs, Photon queries and FOSSGIS route logs remain unverified; the portal Privacy page distinguishes the separate DNS-resolver policies.', 'El contenido común no vence automáticamente. El borrado nativo de elementos y el borrado administrativo de cuenta eliminan los registros y archivos activos probados; las copias descargadas o compartidas quedan aparte. Los respaldos privados diarios permanecen en esta VM sin purga automática. Las copias anteriores pueden conservar datos borrados. FOSSGIS declara que registra las solicitudes de rutas. Siguen sin verificarse los plazos exactos de borrado de registros de mapas OSMF, consultas Photon y rutas FOSSGIS; la página de privacidad distingue las políticas separadas de los resolutores DNS.'),
  logging: text('Local gateway access logs and application HTTP access/request logging are disabled. Errors and system/security logs remain; errors may contain identifiers or submitted details. Container logs rotate by size, at 2 MiB per file and two files per container. This is not a retention period in days. Public-edge and provider log retention remain unverified.', 'Los registros locales de acceso del intermediario y de solicitudes HTTP de la aplicación están desactivados. Siguen los errores y registros del sistema y seguridad; los errores pueden contener identificadores o datos enviados. Los contenedores rotan por tamaño, con 2 MiB por archivo y dos archivos por contenedor. No es un plazo de conservación en días. La conservación de registros del borde público y los proveedores sigue sin verificarse.'),
  license: 'MIT', upstreamProject: 'TRIP', upstreamSourceUrl: 'https://github.com/itskovacs/trip', installedVersion: '1.50.1-p2', modified: true,
  operationalStatus: 'operational',
}];
