import type { CatalogEntry, LocalizedText } from './catalog.ts';
import { reviewedFossProviders } from './upstreams.ts';
const text = (en: string, es: string): LocalizedText => ({ en, es });
const provider = reviewedFossProviders.unfurl;

export const unfurlAdditions: CatalogEntry[] = [{
  id: 'unfurl', providerId: 'unfurl', kind: 'service', implementation: 'upstream-application', portalSurface: 'upstream-interface',
  category: 'service', discoveryGroup: 'text-data', configUrlKey: 'publicExpandUrl',
  name: text('Expand and inspect a link · Unfurl', 'Expandir e inspeccionar un enlace · Unfurl'),
  description: text('See how a URL is put together and follow HTTP redirects through Utilibre’s server.', 'Revisá las partes de una URL y seguí sus redirecciones HTTP mediante el servidor de Utilibre.'),
  launchLabel: text('Inspect a link', 'Inspeccionar un enlace'),
  help: text('Enter a complete HTTP(S) URL, then inspect Graph, Tree or Text. Text offers Copy tree to clipboard. Do not submit passwords, private tokens or confidential links: requesting a unique or one-time URL can register engagement or consume it. Requests are limited to six per minute per client, with a burst of two.', 'Ingresá una URL HTTP(S) completa y revisá Graph, Tree o Text. En Text podés usar Copy tree to clipboard. No enviés contraseñas, tokens privados ni enlaces confidenciales: consultar una URL única o de un solo uso puede registrar actividad o consumirla. Se permiten seis solicitudes por minuto por cliente, con una ráfaga de dos.'),
  limitation: text('Two simultaneous expansion jobs across this instance, up to ten distinct URLs and 100 graph nodes per job. Only public HTTP(S) destinations on ports 80/443 are eligible. Servers that reject HEAD requests may not expand; there is no GET fallback. JavaScript, meta-refresh, consent-page and authenticated redirects are unsupported. An incomplete chain or missing destination is not a safety verdict.', 'Hay dos tareas de expansión simultáneas en toda la instancia, con hasta diez URL distintas y 100 nodos por tarea. Solo se permiten destinos HTTP(S) públicos en puertos 80/443. Los servidores que rechazan HEAD pueden impedir la expansión; no hay alternativa GET. No se admiten redirecciones JavaScript, meta-refresh, páginas de consentimiento ni acceso autenticado. Una cadena incompleta o un destino ausente no demuestra que el enlace sea seguro.'),
  labels: ['server', 'external'], filesUploaded: false,
  dataFlow: text('Submitted URLs pass through Cloudflare and Caddy to Utilibre. The restricted outbound proxy resolves names and requests destination headers to follow HTTP Location redirects; destinations and DNS resolvers receive those requests. The native query-string route can expose the submitted URL at TLS termination and in browser history. Destination page bodies, scripts and previews are not loaded into your browser. No visitor analytics is enabled.', 'Las URL enviadas pasan por Cloudflare y Caddy hacia Utilibre. El proxy de salida restringido resuelve nombres y solicita cabeceras al destino para seguir redirecciones HTTP Location; los destinos y resolutores DNS reciben esas consultas. La ruta nativa usa parámetros de consulta: la URL puede ser visible donde termina TLS y quedar en el historial del navegador. No se cargan cuerpos de páginas, scripts ni vistas previas del destino en tu navegador. No hay estadísticas de visitantes habilitadas.'),
  upstreamServices: ['Requested destination websites', 'Cloudflare HTTPS proxy', 'Cloudflare DNS resolver (1.1.1.1)', 'Quad9 DNS resolver (9.9.9.9)', 'Hetzner hosting'],
  temporaryStorage: text('URL analysis runs in server memory. The application has no account database, saved request history, content cache or persistent state volume. The displayed URL/results and browser history are separate from server storage; the theme preference persists in localStorage.', 'El análisis usa memoria del servidor. La aplicación no tiene base de cuentas, historial de consultas guardado, caché de contenido ni volumen de estado persistente. La URL y los resultados mostrados y el historial del navegador son distintos del almacenamiento del servidor; la preferencia de tema persiste en localStorage.'),
  retention: text('There is no application request-history database to export or delete and no user-state backup. Copy the result tree from Text when needed. Returning to the tool’s root does not erase browser history; remove relevant history and copied or downloaded results separately. Destination, DNS and infrastructure records have independent retention.', 'No hay una base de historial de consultas para exportar o borrar ni respaldo de estado de usuarios. Copiá el árbol desde Text cuando lo necesités. Volver al inicio no borra el historial del navegador; eliminá por separado el historial pertinente y los resultados copiados o descargados. Los registros de destinos, DNS e infraestructura tienen conservación independiente.'),
  logging: text('Native application, gateway and outbound-proxy access logs are disabled, as are Docker content logs; the outbound proxy has no HTTP cache. This does not establish the absence or retention of Caddy/Cloudflare, kernel/security, hosting-provider, DNS or destination records. No fixed external retention period is verified.', 'Los registros de acceso de la aplicación, el intermediario y el proxy de salida están desactivados, al igual que los registros de contenido de Docker; el proxy no usa caché HTTP. Esto no establece la ausencia ni la conservación de registros de Caddy/Cloudflare, sistema y seguridad, alojamiento, DNS o destinos. No se verificó un plazo fijo de conservación externo.'),
  license: provider.license, upstreamProject: provider.project, upstreamSourceUrl: provider.sourceUrl, installedVersion: provider.installedVersion,
  modified: true, operationalStatus: 'operational',
}];
