import type { Language } from '../i18n';

const en = {
  input: 'Input',
  output: 'Output',
  run: 'Run',
  stop: 'Stop',
  clear: 'Clear',
  copy: 'Copy',
  copied: 'Copied.',
  ready: 'Ready.',
  working: 'Working…',
  done: 'Complete.',
  disconnected: 'Disconnected.',
  invalid: 'Check the input and try again.',
  validationUrl: 'Enter a valid supported URL without embedded credentials.',
  validationRequestHeaders: 'Use no more than 50 valid request headers in Name: value form.',
  validationRequestBody: 'The request body must be no larger than 512 KiB.',
  validationWebSocket: 'Check the WebSocket URL, subprotocols, connection, and message limits.',
  validationEventStream: 'Check the event-stream URL, response type, and session limits.',
  validationWebhookInbox: 'The portal returned invalid inbox details. Create another inbox.',
  validationDnsHostname: 'Enter a valid public hostname no longer than 253 characters.',
  validationWebhookSignature: 'Check the payload, signature, secret, algorithm, and encoding.',
  validationJwt: 'Enter a valid JWT or JSON object and the required HMAC secret.',
  validationOpenApi: 'Enter a valid OpenAPI 3.x or Swagger 2.0 JSON or YAML document no larger than 2 MiB.',
  validationHttpCurl: 'Enter a supported raw HTTP request or conservative cURL command.',
  validationRegex: 'Check the regular-expression pattern, flags, and input limits.',
  validationCron: 'Enter a valid five-field cron expression within the input limit.',
  validationTimestamp: 'Enter a valid timestamp or date no longer than 256 characters.',
  noOutput: 'There is no result to copy yet.',
  clipboardError: 'Clipboard access failed. Select and copy the result manually.',
  serverUnavailable: 'This tool is not available right now.',
  serverRateLimited: 'Too many requests. Wait a little and try again.',
  serverBusy: 'The service is at its temporary capacity. Try again later.',
  serverInvalidRequest: 'The server could not accept that request.',
  requestFailed: 'The request failed.',
  localBoundary: 'This operation runs in this browser tab. Utilibre does not receive the entered content.',
  externalBoundary: 'Your browser connects directly to the destination. Utilibre does not proxy the request.',
  corsBoundary: 'Browser cross-origin rules still apply. Redirects are followed. A visible failure can occur after the destination or a redirect target has already received the request.',
  ephemeralBoundary: 'Working data is kept in this tab and is cleared when the page is reloaded or closed.',
  url: 'URL',
  method: 'Method',
  headers: 'Headers, one Name: value pair per line',
  requestBody: 'Request body',
  sendRequest: 'Send request',
  cancelRequest: 'Cancel request',
  requestLimit: 'Browser cookies and automatic credentials are omitted. Headers you enter, including Authorization, are sent to the destination. Forbidden browser headers cannot be set. Response bodies are displayed up to 1 MiB. Do not use a state-changing method with an endpoint you do not trust, or retry only because the response is hidden.',
  requestStatus: 'Status',
  requestFinalUrl: 'Final URL',
  requestTime: 'Elapsed time',
  requestSize: 'Displayed body size',
  requestRedirected: 'Redirected',
  yes: 'Yes',
  no: 'No',
  truncated: 'truncated',
  query: 'Query',
  contentType: 'Content-Type',
  headersLabel: 'Headers',
  bodyLabel: 'Body',
  rawBodyLabel: 'Raw UTF-8 request body (authoritative)',
  encodedBodyLabel: 'Captured body (Base64 representation)',
  formattedJsonLabel: 'Formatted JSON preview',
  copyRawBody: 'Copy captured UTF-8 text',
  copyEncodedBody: 'Copy Base64 text',
  rawBodyIntegrity: 'This view preserves the captured UTF-8 text and is authoritative; the formatted preview changes whitespace. Clipboard or textarea operations can normalize line endings, so check them before byte-exact signature verification.',
  encodedBodyIntegrity: 'This is a Base64 representation, not the original request bytes. Decode the Base64 and use the resulting bytes—or the original request bytes—for byte-exact signature verification.',
  responseHeaders: 'Response headers visible to this browser',
  responseBody: 'Response body',
  headerInspect: 'Inspect headers',
  headerLimit: 'This sends a direct HEAD request. Only headers exposed by the destination’s CORS policy are visible.',
  connect: 'Connect',
  disconnect: 'Disconnect',
  sendMessage: 'Send message',
  socketUrl: 'WebSocket URL',
  socketProtocols: 'Subprotocols, separated by commas (optional)',
  socketMessage: 'Text message',
  socketLog: 'Session log',
  logEntryTruncated: 'display truncated',
  binaryMessage: 'binary message',
  binaryResponseNotRendered: 'binary response not rendered',
  socketOpened: 'OPEN',
  socketClosed: 'CLOSED',
  socketLimit: 'The browser sends an Origin header and may attach cookies already stored for the destination; the WebSocket API has no omit-credentials control. It sends no custom handshake headers. Outgoing text is limited to 65,536 bytes. The visible log keeps 100 entries and marks text clipped after 65,536 payload characters. The connection closes after 1,000 incoming messages, more than 10 MiB received in total, or any message over 1 MiB. The browser materializes a frame before this page can inspect it, so one oversized frame can allocate memory before the connection closes.',
  streamUrl: 'Event-stream URL',
  streamLog: 'Event log',
  streamLimit: 'The browser connects without cross-origin credentials. The visible log keeps 100 entries and marks clipped event types, IDs, or data. A session stops after 1,000 events, 10 MiB, or an undelimited buffer over 128 KiB.',
  createInbox: 'Create temporary inbox',
  deleteInbox: 'Delete inbox',
  copyInbox: 'Copy receive URL',
  inboxUrl: 'Webhook receive URL',
  inboxExpires: 'Expires',
  inboxEvents: 'Received requests',
  inboxEmpty: 'No requests received yet.',
  inboxSummary: 'Requests are kept only in this portal process. Access ends after 15 minutes; the receive URL permits anyone who has it to submit a request.',
  inboxLimit: 'An inbox accepts POST, PUT, PATCH, and DELETE for 15 minutes. Its process-memory references are removed on the next related request or periodic sweep, normally within one additional minute. It retains the newest events up to 25 events/1 MiB; later accepted events can evict the oldest. Each request body is limited to 12 KiB, and each event keeps at most 32 retained headers totaling 32 KiB. Authorization, Cookie, standard hop-by-hop, and recognized proxy, forwarding, and client-address headers are not retained. Events are read in pages of up to 10. There is no forwarding or replay.',
  inboxSecretWarning: 'The receive URL is a short-lived write capability: anyone who has it can submit requests until it expires or you delete the inbox, and the edge proxy may log its path. Anyone with read access to the inbox can see the retained query, body, and custom headers, including tokens or signatures.',
  inboxHeadersTruncated: 'Some request headers were omitted because the per-event capture limit was reached.',
  inboxCreated: 'Temporary inbox created.',
  inboxDeleted: 'Temporary inbox deleted.',
  inboxExpired: 'The inbox expired or is no longer available. Create another one.',
  payload: 'Payload',
  payloadEncoding: 'Payload encoding',
  payloadUtf8: 'UTF-8 text',
  payloadBase64: 'Base64 bytes',
  secret: 'Secret',
  signature: 'Signature',
  algorithm: 'Algorithm',
  encoding: 'Signature encoding',
  verify: 'Verify signature',
  signatureValid: 'Signature valid',
  signatureInvalid: 'Signature invalid',
  hmacLimit: 'The payload, secret, and signature stay in this tab. Choose UTF-8 text or strict, canonical Base64 bytes for the payload. The decoded payload limit is 1 MiB; the secret limit is 65,536 characters and the signature limit is 4,096 characters. The comparison supports HMAC SHA-256, SHA-384, and SHA-512.',
  jwtToken: 'JWT',
  jwtDecode: 'Decode',
  jwtVerify: 'Decode and verify HMAC',
  jwtHeader: 'Decoded header',
  jwtClaims: 'Decoded claims',
  jwtClaimTable: 'Claim details',
  jwtGenerate: 'Generate signed JWT',
  jwtPayload: 'Claims JSON',
  jwtHeaderInput: 'Additional header JSON (optional)',
  jwtWarning: 'Decoding is not verification. Local signature verification supports HS256, HS384, and HS512 only.',
  jwtSecret: 'HMAC secret (optional for decoding)',
  jwtVerified: 'Signature valid for the supplied secret.',
  jwtNotVerified: 'Signature is not valid for the supplied secret.',
  jwtGenerated: 'JWT generated locally.',
  claim: 'Claim',
  value: 'Value',
  interpretation: 'Interpretation',
  claimAudience: 'audience',
  claimIdentifier: 'identifier',
  claimIssuer: 'issuer',
  claimNumericDate: 'numeric date',
  claimSubject: 'subject',
  claimOther: 'other claim',
  claimTimePast: 'date is in the past',
  claimTimeFuture: 'date is in the future',
  claimTimeNow: 'date is current',
  openApiDocument: 'OpenAPI JSON or YAML',
  openApiFile: 'Choose an OpenAPI file (optional)',
  openApiInspect: 'Inspect document',
  openApiTitle: 'Title',
  openApiVersion: 'Specification',
  openApiApiVersion: 'API version',
  openApiServers: 'Servers declared by the document',
  openApiEndpoints: 'Endpoints',
  openApiRefs: 'References',
  openApiLocalRef: 'local',
  openApiRemoteRef: 'remote',
  openApiNoEndpoints: 'No operations were found in the paths object.',
  openApiLimit: 'Parsing is local and limited to 2 MiB. Remote $ref targets are listed but never fetched.',
  endpointMethod: 'Method',
  endpointPath: 'Path',
  endpointSummary: 'Summary',
  conversionDirection: 'Conversion',
  rawHttpToCurl: 'Raw HTTP request → cURL',
  curlToRawHttp: 'cURL → raw HTTP request',
  convert: 'Convert',
  curlLimit: 'The converter never executes commands. File, credential-file, and unsupported options are rejected.',
  regexPattern: 'Pattern',
  regexFlags: 'Flags',
  regexText: 'Test text',
  regexTest: 'Test expression',
  regexMatches: 'Matches',
  regexNoMatch: 'No matches.',
  regexCaptures: 'captures',
  regexLimit: 'Testing runs in a disposable worker with bounded input and a short timeout. JavaScript regular-expression syntax is used.',
  regexTimedOut: 'The expression exceeded the time limit and was stopped.',
  cronExpression: 'Five-field cron expression',
  cronPreview: 'Preview next times',
  cronTimes: 'Next scheduled times',
  cronZone: 'The expression is evaluated in UTC. Results show UTC and this browser’s local representation.',
  cronHorizon: 'The bounded search ended before it found all requested times. This does not prove the schedule will never run.',
  timestampValue: 'Unix timestamp or date',
  timestampConvert: 'Convert timestamp',
  timestampIso: 'ISO date',
  timestampLocal: 'Local date',
  timestampSeconds: 'Unix seconds',
  timestampMilliseconds: 'Unix milliseconds',
  timestampHelp: 'Numeric input is detected as seconds or milliseconds. Date text is parsed by this browser.',
  textToHash: 'Text to hash',
  calculateHash: 'Calculate hash',
  hashEncoding: 'Output encoding',
  hashWarning: 'SHA-1 is included for compatibility with older systems. It is not collision-resistant and should not be chosen for new security-sensitive uses.',
  uuidValue: 'UUID to inspect',
  uuidGenerate: 'Generate UUIDv4',
  uuidGenerateMany: 'Generate 10 UUIDv4 values',
  uuidInspect: 'Inspect UUID',
  uuidVersion: 'Version',
  uuidVariant: 'Variant',
  uuidCanonical: 'Canonical form',
  uuidValid: 'Valid UUID.',
  uuidInvalid: 'This is not a canonical UUID.',
  dnsName: 'Hostname',
  dnsAscii: 'ASCII hostname',
  dnsType: 'Record type',
  dnsLookup: 'Look up records',
  dnsAnswers: 'DNS answers',
  dnsInvalidName: 'Enter a public hostname, such as example.org.',
  dnsUnsupported: 'That DNS record type is not supported.',
  dnsNoRecords: 'No matching records were returned.',
  dnsTimeout: 'The DNS lookup timed out.',
  dnsFailed: 'The DNS lookup failed without exposing resolver details.',
  dnsLimit: 'Utilibre asks the application VM’s configured resolver. Queries are rate-limited and results are capped.',
} as const;

const es: Record<keyof typeof en, string> = {
  input: 'Entrada',
  output: 'Resultado',
  run: 'Ejecutar',
  stop: 'Detener',
  clear: 'Borrar',
  copy: 'Copiar',
  copied: 'Copiado.',
  ready: 'Listo.',
  working: 'Procesando…',
  done: 'Completado.',
  disconnected: 'Desconectado.',
  invalid: 'Revisa los datos e inténtalo de nuevo.',
  validationUrl: 'Ingresa una URL válida y compatible, sin credenciales incorporadas.',
  validationRequestHeaders: 'Usa como máximo 50 cabeceras válidas con el formato Nombre: valor.',
  validationRequestBody: 'El cuerpo de la solicitud no puede superar 512 KiB.',
  validationWebSocket: 'Revisa la URL de WebSocket, los subprotocolos, la conexión y los límites de los mensajes.',
  validationEventStream: 'Revisa la URL del flujo de eventos, el tipo de respuesta y los límites de la sesión.',
  validationWebhookInbox: 'El portal devolvió datos no válidos para el buzón. Crea otro buzón.',
  validationDnsHostname: 'Ingresa un nombre de host público válido de hasta 253 caracteres.',
  validationWebhookSignature: 'Revisa el contenido, la firma, el secreto, el algoritmo y la codificación.',
  validationJwt: 'Ingresa un JWT u objeto JSON válido y el secreto HMAC requerido.',
  validationOpenApi: 'Ingresa un documento JSON o YAML válido de OpenAPI 3.x o Swagger 2.0 con un máximo de 2 MiB.',
  validationHttpCurl: 'Ingresa una solicitud HTTP sin procesar o un comando cURL conservador y compatible.',
  validationRegex: 'Revisa el patrón de la expresión regular, los indicadores y los límites de entrada.',
  validationCron: 'Ingresa una expresión cron válida de cinco campos dentro del límite de entrada.',
  validationTimestamp: 'Ingresa una marca de tiempo o fecha válida de hasta 256 caracteres.',
  noOutput: 'Todavía no hay un resultado para copiar.',
  clipboardError: 'No fue posible acceder al portapapeles. Selecciona y copia el resultado manualmente.',
  serverUnavailable: 'Esta herramienta no está disponible en este momento.',
  serverRateLimited: 'Hay demasiadas solicitudes. Espera un poco e inténtalo de nuevo.',
  serverBusy: 'El servicio alcanzó temporalmente su capacidad. Inténtalo más tarde.',
  serverInvalidRequest: 'El servidor no pudo aceptar esa solicitud.',
  requestFailed: 'La solicitud falló.',
  localBoundary: 'Esta operación se realiza en esta pestaña. Utilibre no recibe el contenido ingresado.',
  externalBoundary: 'Tu navegador se conecta directamente al destino. Utilibre no retransmite la solicitud.',
  corsBoundary: 'Se aplican las reglas del navegador para solicitudes entre orígenes. Se siguen las redirecciones. Puede aparecer un fallo después de que el destino o el destino de una redirección ya haya recibido la solicitud.',
  ephemeralBoundary: 'Los datos de trabajo se conservan en esta pestaña y se borran al recargarla o cerrarla.',
  url: 'URL',
  method: 'Método',
  headers: 'Cabeceras, una pareja Nombre: valor por línea',
  requestBody: 'Cuerpo de la solicitud',
  sendRequest: 'Enviar solicitud',
  cancelRequest: 'Cancelar solicitud',
  requestLimit: 'Se omiten las cookies y credenciales automáticas del navegador. Las cabeceras que ingreses, incluida Authorization, se envían al destino. No se pueden definir cabeceras prohibidas por el navegador. Se muestra hasta 1 MiB del cuerpo de respuesta. No uses un método que cambie datos con un destino que no sea de confianza ni repitas la solicitud solo porque la respuesta esté oculta.',
  requestStatus: 'Estado',
  requestFinalUrl: 'URL final',
  requestTime: 'Tiempo transcurrido',
  requestSize: 'Tamaño del cuerpo mostrado',
  requestRedirected: 'Redirigida',
  yes: 'Sí',
  no: 'No',
  truncated: 'truncado',
  query: 'Consulta',
  contentType: 'Content-Type',
  headersLabel: 'Cabeceras',
  bodyLabel: 'Cuerpo',
  rawBodyLabel: 'Cuerpo UTF-8 sin procesar (original)',
  encodedBodyLabel: 'Cuerpo capturado (representación Base64)',
  formattedJsonLabel: 'Vista JSON con formato',
  copyRawBody: 'Copiar texto UTF-8 capturado',
  copyEncodedBody: 'Copiar texto Base64',
  rawBodyIntegrity: 'Esta vista conserva el texto UTF-8 capturado y es el original; la vista con formato cambia los espacios. El portapapeles o las áreas de texto pueden normalizar los saltos de línea, así que compruébalos antes de verificar una firma byte por byte.',
  encodedBodyIntegrity: 'Esta es una representación Base64, no los bytes originales de la solicitud. Decodifica el Base64 y usa los bytes resultantes —o los bytes de la solicitud original— para verificar una firma byte por byte.',
  responseHeaders: 'Cabeceras de respuesta visibles para este navegador',
  responseBody: 'Cuerpo de la respuesta',
  headerInspect: 'Examinar cabeceras',
  headerLimit: 'Esto envía una solicitud HEAD directa. Solo son visibles las cabeceras expuestas por la política CORS del destino.',
  connect: 'Conectar',
  disconnect: 'Desconectar',
  sendMessage: 'Enviar mensaje',
  socketUrl: 'URL de WebSocket',
  socketProtocols: 'Subprotocolos separados por comas (opcional)',
  socketMessage: 'Mensaje de texto',
  socketLog: 'Registro de la sesión',
  logEntryTruncated: 'visualización truncada',
  binaryMessage: 'mensaje binario',
  binaryResponseNotRendered: 'respuesta binaria no mostrada',
  socketOpened: 'ABIERTO',
  socketClosed: 'CERRADO',
  socketLimit: 'El navegador envía una cabecera Origin y puede adjuntar cookies ya guardadas para el destino; la API de WebSocket no permite omitir credenciales. No envía cabeceras personalizadas en la conexión. El texto saliente se limita a 65 536 bytes. El registro visible conserva 100 entradas e indica si recorta texto después de 65 536 caracteres del contenido. La conexión se cierra después de 1 000 mensajes recibidos, más de 10 MiB recibidos en total o cualquier mensaje mayor de 1 MiB. El navegador materializa cada trama antes de que esta página pueda examinarla, por lo que una sola trama demasiado grande puede ocupar memoria antes de que se cierre la conexión.',
  streamUrl: 'URL del flujo de eventos',
  streamLog: 'Registro de eventos',
  streamLimit: 'El navegador se conecta sin credenciales entre orígenes. El registro visible conserva 100 entradas e indica si recorta el tipo, el identificador o los datos de un evento. La sesión se detiene después de 1 000 eventos, 10 MiB o un búfer sin delimitador mayor de 128 KiB.',
  createInbox: 'Crear buzón temporal',
  deleteInbox: 'Eliminar buzón',
  copyInbox: 'Copiar URL de recepción',
  inboxUrl: 'URL de recepción del webhook',
  inboxExpires: 'Vence',
  inboxEvents: 'Solicitudes recibidas',
  inboxEmpty: 'Todavía no se han recibido solicitudes.',
  inboxSummary: 'Las solicitudes se conservan solo en la memoria de este proceso del portal. El acceso termina a los 15 minutos; cualquiera que tenga la URL de recepción puede enviar una solicitud.',
  inboxLimit: 'Un buzón acepta POST, PUT, PATCH y DELETE durante 15 minutos. Sus referencias en la memoria del proceso se eliminan con la siguiente solicitud relacionada o el barrido periódico, normalmente dentro del minuto siguiente. Conserva los eventos más recientes hasta un máximo de 25 eventos o 1 MiB; los eventos posteriores aceptados pueden eliminar los más antiguos. El cuerpo de cada solicitud se limita a 12 KiB y cada evento conserva como máximo 32 cabeceras retenidas con un total de 32 KiB. No conserva las cabeceras de autorización, cookies, salto a salto estándar ni las cabeceras reconocidas de proxy, reenvío y dirección del cliente. Los eventos se leen en páginas de hasta 10. No permite reenvío ni repetición.',
  inboxSecretWarning: 'La URL de recepción concede permiso temporal de escritura: cualquiera que la tenga puede enviar solicitudes hasta que venza o elimines el buzón, y el proxy perimetral puede registrar su ruta. Quien tenga acceso de lectura al buzón puede ver la consulta, el cuerpo y las cabeceras personalizadas retenidas, incluidos tokens o firmas.',
  inboxHeadersTruncated: 'Se omitieron algunas cabeceras porque se alcanzó el límite de captura por evento.',
  inboxCreated: 'Buzón temporal creado.',
  inboxDeleted: 'Buzón temporal eliminado.',
  inboxExpired: 'El buzón venció o ya no está disponible. Crea otro.',
  payload: 'Contenido',
  payloadEncoding: 'Codificación del contenido',
  payloadUtf8: 'Texto UTF-8',
  payloadBase64: 'Bytes en Base64',
  secret: 'Secreto',
  signature: 'Firma',
  algorithm: 'Algoritmo',
  encoding: 'Codificación de la firma',
  verify: 'Verificar firma',
  signatureValid: 'Firma válida',
  signatureInvalid: 'Firma no válida',
  hmacLimit: 'El contenido, el secreto y la firma permanecen en esta pestaña. Elige texto UTF-8 o bytes en Base64 canónico y estricto para el contenido. El límite del contenido decodificado es 1 MiB; el del secreto es 65 536 caracteres y el de la firma es 4 096 caracteres. La comparación admite HMAC SHA-256, SHA-384 y SHA-512.',
  jwtToken: 'JWT',
  jwtDecode: 'Decodificar',
  jwtVerify: 'Decodificar y verificar HMAC',
  jwtHeader: 'Cabecera decodificada',
  jwtClaims: 'Atributos decodificados',
  jwtClaimTable: 'Detalles de atributos',
  jwtGenerate: 'Generar JWT firmado',
  jwtPayload: 'Atributos JSON',
  jwtHeaderInput: 'Cabecera JSON adicional (opcional)',
  jwtWarning: 'Decodificar no equivale a verificar. La verificación local admite únicamente HS256, HS384 y HS512.',
  jwtSecret: 'Secreto HMAC (opcional para decodificar)',
  jwtVerified: 'La firma es válida para el secreto proporcionado.',
  jwtNotVerified: 'La firma no es válida para el secreto proporcionado.',
  jwtGenerated: 'JWT generado localmente.',
  claim: 'Atributo',
  value: 'Valor',
  interpretation: 'Interpretación',
  claimAudience: 'audiencia',
  claimIdentifier: 'identificador',
  claimIssuer: 'emisor',
  claimNumericDate: 'fecha numérica',
  claimSubject: 'sujeto',
  claimOther: 'otro atributo',
  claimTimePast: 'la fecha está en el pasado',
  claimTimeFuture: 'la fecha está en el futuro',
  claimTimeNow: 'la fecha corresponde al momento actual',
  openApiDocument: 'OpenAPI en JSON o YAML',
  openApiFile: 'Elegir un archivo OpenAPI (opcional)',
  openApiInspect: 'Examinar documento',
  openApiTitle: 'Título',
  openApiVersion: 'Especificación',
  openApiApiVersion: 'Versión de la API',
  openApiServers: 'Servidores declarados por el documento',
  openApiEndpoints: 'Operaciones',
  openApiRefs: 'Referencias',
  openApiLocalRef: 'local',
  openApiRemoteRef: 'remota',
  openApiNoEndpoints: 'No se encontraron operaciones en el objeto paths.',
  openApiLimit: 'El análisis es local y se limita a 2 MiB. Las referencias $ref remotas se enumeran, pero nunca se solicitan.',
  endpointMethod: 'Método',
  endpointPath: 'Ruta',
  endpointSummary: 'Resumen',
  conversionDirection: 'Conversión',
  rawHttpToCurl: 'Solicitud HTTP sin procesar → cURL',
  curlToRawHttp: 'cURL → solicitud HTTP sin procesar',
  convert: 'Convertir',
  curlLimit: 'El conversor nunca ejecuta comandos. Se rechazan las opciones de archivo, archivo de credenciales y demás opciones no compatibles.',
  regexPattern: 'Patrón',
  regexFlags: 'Indicadores',
  regexText: 'Texto de prueba',
  regexTest: 'Probar expresión',
  regexMatches: 'Coincidencias',
  regexNoMatch: 'No hay coincidencias.',
  regexCaptures: 'grupos',
  regexLimit: 'La prueba se ejecuta en un proceso de navegador descartable con límites de entrada y un plazo breve. Se usa la sintaxis de expresiones regulares de JavaScript.',
  regexTimedOut: 'La expresión superó el plazo y fue detenida.',
  cronExpression: 'Expresión cron de cinco campos',
  cronPreview: 'Mostrar próximas fechas',
  cronTimes: 'Próximas fechas programadas',
  cronZone: 'La expresión se evalúa en UTC. Los resultados muestran UTC y la representación local de este navegador.',
  cronHorizon: 'La búsqueda limitada terminó antes de encontrar todas las fechas solicitadas. Esto no demuestra que la programación nunca se ejecutará.',
  timestampValue: 'Marca de tiempo Unix o fecha',
  timestampConvert: 'Convertir marca de tiempo',
  timestampIso: 'Fecha ISO',
  timestampLocal: 'Fecha local',
  timestampSeconds: 'Segundos Unix',
  timestampMilliseconds: 'Milisegundos Unix',
  timestampHelp: 'La entrada numérica se detecta como segundos o milisegundos. El texto de fecha lo interpreta este navegador.',
  textToHash: 'Texto para calcular el hash',
  calculateHash: 'Calcular hash',
  hashEncoding: 'Codificación del resultado',
  hashWarning: 'SHA-1 se incluye por compatibilidad con sistemas antiguos. No resiste colisiones y no debe elegirse para usos nuevos que dependan de la seguridad.',
  uuidValue: 'UUID que se examinará',
  uuidGenerate: 'Generar UUIDv4',
  uuidGenerateMany: 'Generar 10 UUIDv4',
  uuidInspect: 'Examinar UUID',
  uuidVersion: 'Versión',
  uuidVariant: 'Variante',
  uuidCanonical: 'Forma canónica',
  uuidValid: 'UUID válido.',
  uuidInvalid: 'No es un UUID canónico.',
  dnsName: 'Nombre de host',
  dnsAscii: 'Nombre de host ASCII',
  dnsType: 'Tipo de registro',
  dnsLookup: 'Consultar registros',
  dnsAnswers: 'Respuestas DNS',
  dnsInvalidName: 'Ingresa un nombre de host público, como example.org.',
  dnsUnsupported: 'Ese tipo de registro DNS no es compatible.',
  dnsNoRecords: 'No se devolvieron registros coincidentes.',
  dnsTimeout: 'La consulta DNS superó el plazo.',
  dnsFailed: 'La consulta DNS falló sin exponer detalles del resolvedor.',
  dnsLimit: 'Utilibre consulta el resolvedor configurado en la VM de aplicaciones. Las consultas tienen límites de frecuencia y resultados.',
};

export type DeveloperCopyKey = keyof typeof en;

export function developerText(language: Language, key: DeveloperCopyKey): string {
  return (language === 'es' ? es : en)[key];
}
