[global]
daemonize = no
error_log = /dev/null
[www]
listen = 0.0.0.0:8080
user = nobody
group = nobody
pm = ondemand
pm.max_children = 2
pm.process_idle_timeout = 10s
pm.max_requests = 100
clear_env = no
catch_workers_output = no
request_terminate_timeout = 25s
php_admin_value[memory_limit] = 192M
php_admin_value[max_execution_time] = 20
php_admin_value[post_max_size] = 2M
php_admin_value[upload_max_filesize] = 2M
php_admin_value[variables_order] = EGPCS
php_admin_flag[display_errors] = off
php_admin_flag[log_errors] = off
php_admin_flag[expose_php] = off
php_admin_flag[allow_url_fopen] = off
